version: "2"
linters:
  default: none
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - canonicalheader
    - copyloopvar
    - dupl
    - durationcheck
    - errcheck
    - errname
    - errorlint
    - exhaustive
    - fatcontext
    - forbidigo
    - gocheckcompilerdirectives
    - gochecksumtype
    - goconst
    - gocritic
    - godot
    - gomoddirectives
    - gomodguard
    - goprintffuncname
    - gosec
    - govet
    - iface
    - ineffassign
    - intrange
    - lll
    - loggercheck
    - makezero
    - mirror
    - musttag
    - nakedret
    - nilerr
    - nilnil
    - noctx
    - nolintlint
    - nonamedreturns
    - nosprintfhostport
    - perfsprint
    - prealloc
    - predeclared
    - promlinter
    - protogetter
    - reassign
    - recvcheck
    - revive
    - rowserrcheck
    - spancheck
    - sqlclosecheck
    - staticcheck
    - testableexamples
    - testifylint
    - tparallel
    - unconvert
    - unused
    - usestdlibvars
    - wastedassign
    - whitespace
    - usetesting
  settings:
    cyclop:
      max-complexity: 30
      package-average: 10
    errcheck:
      check-type-assertions: true
      ignore: defer
    exhaustive:
      check:
        - switch
        - map
      default-signifies-exhaustive: true
    exhaustruct:
      exclude:
        - ^net/http.Client$
        - ^net/http.Cookie$
        - ^net/http.Request$
        - ^net/http.Response$
        - ^net/http.Server$
        - ^net/http.Transport$
        - ^net/url.URL$
        - ^os/exec.Cmd$
        - ^reflect.StructField$
        - ^github.com/Shopify/sarama.Config$
        - ^github.com/Shopify/sarama.ProducerMessage$
        - ^github.com/mitchellh/mapstructure.DecoderConfig$
        - ^github.com/prometheus/client_golang/.+Opts$
        - ^github.com/spf13/cobra.Command$
        - ^github.com/spf13/cobra.CompletionOptions$
        - ^github.com/stretchr/testify/mock.Mock$
        - ^github.com/testcontainers/testcontainers-go.+Request$
        - ^github.com/testcontainers/testcontainers-go.FromDockerfile$
        - ^golang.org/x/tools/go/analysis.Analyzer$
        - ^google.golang.org/protobuf/.+Options$
        - ^gopkg.in/yaml.v3.Node$
    funlen:
      lines: 100
      statements: 50
      ignore-comments: true
    gocognit:
      min-complexity: 20
    gochecksumtype:
      default-signifies-exhaustive: false
    gocritic:
      settings:
        captLocal:
          paramsOnly: false
        underef:
          skipRecvDeref: false
    gomoddirectives:
      replace-allow-list:
        - github.com/charmbracelet/bubbletea
    gomodguard:
      blocked:
        modules:
          - github.com/golang/protobuf:
              recommendations:
                - google.golang.org/protobuf
              reason: see https://developers.google.com/protocol-buffers/docs/reference/go/faq#modules
          - github.com/satori/go.uuid:
              recommendations:
                - github.com/google/uuid
              reason: satori's package is not maintained
          - github.com/gofrs/uuid:
              recommendations:
                - github.com/gofrs/uuid/v5
              reason: gofrs' package was not go module before v5
    govet:
      disable:
        - fieldalignment
        - shadow
      enable-all: true
    inamedparam:
      skip-single-param: true
    lll:
      line-length: 170
    nolintlint:
      require-explanation: false
      require-specific: true
    perfsprint:
      strconcat: false
    reassign:
      patterns:
        - .*
    revive:
      rules:
        - name: unused-parameter
          disabled: true
    rowserrcheck:
      packages:
        - github.com/jmoiron/sqlx
    sloglint:
      no-global: all
      context: scope
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - source: (noinspection|TODO)
        linters:
          - godot
      - source: //noinspection
        linters:
          - gocritic
      - path: _test\.go
        linters:
          - bodyclose
          - dupl
          - errcheck
          - funlen
          - goconst
          - gosec
          - noctx
          - prealloc
          - wrapcheck
          - forbidigo
          - lll
      - path: internal/cmd/.*
        text: use of `fmt.Println` forbidden by pattern
        linters:
          - forbidigo
      - path: internal/cmd/.*
        linters:
          - dupl
      - source: "^func "
        linters:
          - lll
      - path: (.+)\.go$
        text: 'ineffectual assignment to ctx'
      - path: (.+)\.go$
        text: 'SA4006: this value of ctx is never used'
      - path: (.+)\.go$
        text: 'assigned to ctx, but never used afterwards'
    paths:
      - internal/experiment
      - third_party$
      - builtin$
      - examples$
      - internal/hsingleflight/group.go

issues:
  max-same-issues: 50
formatters:
  enable:
    - goimports
  exclusions:
    generated: lax
    paths:
      - internal/experiment
      - third_party$
      - builtin$
      - examples$

