//! `go_lint` — per-package go/analysis driver producing serialized facts.
//!
//! Mirrors [`crate::plugingo::driver_compile`] but instead of `go tool compile`
//! it runs the hermetic `heph-govet` binary (an `x/tools` unitchecker, built as
//! an ordinary Go target and staged read-only). It analyzes exactly ONE package:
//!
//!   - dep type info  → export data `.a` archives, via the `lib_*` dep groups
//!     (identical wiring to `go_compile`'s importcfg);
//!   - dep facts      → each dep's `lint.facts`, via the `facts_*` dep groups;
//!   - own facts out  → `lint.facts` (the `facts` output group), consumed by
//!     dependents;
//!   - diagnostics    → `lint-report.json` (the `report` output group), gated by
//!     a separate cheap target so facts are produced/cached even when a package
//!     currently has findings.
//!
//! This is the nogo model. Per-package caching falls out of the engine's
//! content-hashing of inputs: a package re-lints only when its own sources, a
//! dep's archive, or a dep's facts change. Interprocedural analyzers (printf
//! wrappers, lostcancel, …) keep full fidelity because facts cross the boundary —
//! which export-data-only linting cannot do.

use anyhow::Context;
use async_trait::async_trait;
use hcore::debug_hash::DebugHasher;
use hcore::hasync::Cancellable;
use hdriver_support::driver_managed::{ManagedDriver, ManagedRunRequest, ManagedRunResponse};
use hplugin::driver::targetdef::path::{CodegenMode, Content, Path as TPath};
use hplugin::driver::targetdef::{CacheConfig, Input, InputMode, Output, TargetDef};
use hplugin::driver::{
    ApplyTransitiveRequest, ApplyTransitiveResponse, ConfigRequest, ConfigResponse, ParseRequest,
    ParseResponse, TargetAddr,
};
use hplugin::htspec::Spec;
use hproc::proc_exec;
use std::collections::BTreeMap;
use std::collections::HashMap;
use std::ffi::OsString;
use std::hash::{Hash, Hasher};
use std::io::BufRead;
use std::sync::Arc;
use xxhash_rust::xxh3::Xxh3Default;

/// Output filenames (package-relative). Kept in sync between [`build_lint_spec`]
/// (the declared outputs) and [`GoLintDriver::run`] (where they are written).
const LINT_FACTS: &str = "lint.facts";
const LINT_REPORT: &str = "lint-report.json";

/// Dep group carrying the `heph-govet` unitchecker binary.
const GOVET_TOOL_GROUP: &str = "govet_tool";

/// Dep group prefix for a dependency's serialized facts (parallel to the
/// `lib_*` archive groups). `"github.com/foo/bar"` → `"facts_github_com_foo_bar"`.
fn import_path_to_facts_group(import_path: &str) -> String {
    let sanitized: String = import_path
        .chars()
        .map(|c| {
            if c.is_alphanumeric() || c == '_' {
                c
            } else {
                '_'
            }
        })
        .collect();
    format!("facts_{sanitized}")
}

pub struct GoLintDriver;

impl GoLintDriver {
    pub fn new() -> Self {
        Self
    }
}

impl Default for GoLintDriver {
    fn default() -> Self {
        Self::new()
    }
}

/// Config for a `go_lint` target (engine-generated by the Go provider).
#[derive(Spec)]
struct GoLintSpec {
    /// Import path of the package under analysis (cfg `ImportPath`).
    #[spec(required)]
    import_path: String,
    /// Target GOOS.
    #[spec(required)]
    goos: String,
    /// Target GOARCH.
    #[spec(required)]
    goarch: String,
    /// Go release whose semantics drive the analysis (cfg `GoVersion`).
    #[spec(required)]
    go_version: String,
    /// Import paths of the transitive libs, deterministic order — each maps to a
    /// `lib_<sanitized>` dep group (archive, for type info) and, when the dep is
    /// itself linted, a `facts_<sanitized>` group (its serialized facts).
    import_paths: Vec<String>,
    /// Dependencies, grouped by name → list of target addresses.
    deps: HashMap<String, Vec<String>>,
    /// Declared outputs, grouped by name → list of output paths.
    out: HashMap<String, Vec<String>>,
}

#[derive(Clone, serde::Serialize, serde::Deserialize)]
struct GoLintDef {
    import_path: String,
    goos: String,
    goarch: String,
    go_version: String,
    import_paths: Vec<String>,
}

/// Bump to invalidate every cached `go_lint` result whenever the cfg shape or
/// the analyzer set baked into `heph-govet` changes in a way the binary's own
/// input hash does not already capture.
const GO_LINT_FORMAT_VERSION: u32 = 1;

impl Hash for GoLintDef {
    fn hash<H: Hasher>(&self, state: &mut H) {
        GO_LINT_FORMAT_VERSION.hash(state);
        self.import_path.hash(state);
        self.goos.hash(state);
        self.goarch.hash(state);
        self.go_version.hash(state);
        // Order-invariant, exactly as `go_compile` does: the closure walk dedups
        // through a per-process-randomized HashSet, so hash a sorted view or the
        // cache key flips every run.
        let mut import_paths: Vec<&str> = self.import_paths.iter().map(String::as_str).collect();
        import_paths.sort_unstable();
        import_paths.len().hash(state);
        for ip in import_paths {
            ip.hash(state);
        }
        // Sources, archives, facts and the govet binary arrive via inputs; the
        // engine hashes their content, so no per-file hashing here. A change to
        // the analyzer set changes the govet binary's bytes → its input hash →
        // this target's hash.
    }
}

/// cfg.json schema understood by `golang.org/x/tools/go/analysis/unitchecker`.
/// Field names serialize to the PascalCase keys the Go side expects.
#[derive(serde::Serialize)]
#[serde(rename_all = "PascalCase")]
struct UnitcheckerConfig {
    compiler: String,
    dir: String,
    import_path: String,
    go_version: String,
    go_files: Vec<String>,
    non_go_files: Vec<String>,
    ignored_files: Vec<String>,
    import_map: BTreeMap<String, String>,
    package_file: BTreeMap<String, String>,
    standard: BTreeMap<String, bool>,
    package_vetx: BTreeMap<String, String>,
    vetx_only: bool,
    vetx_output: String,
    succeed_on_typecheck_failure: bool,
}

#[async_trait]
impl ManagedDriver for GoLintDriver {
    fn config(&self, _req: ConfigRequest) -> anyhow::Result<ConfigResponse> {
        Ok(ConfigResponse {
            name: "go_lint".to_string(),
        })
    }

    fn schema(&self) -> hplugin::driver::DriverSchema {
        GoLintSpec::schema()
    }

    async fn parse(
        &self,
        req: ParseRequest,
        _ctoken: &(dyn Cancellable + Send + Sync),
    ) -> anyhow::Result<ParseResponse> {
        let pkg = req.target_spec.addr.package.clone();
        let pkg_str = pkg.as_str();
        let spec =
            GoLintSpec::from(req.target_spec.config.clone()).context("parse go_lint config")?;

        let mut inputs: Vec<Input> = Vec::new();
        let mut groups: Vec<&String> = spec.deps.keys().collect();
        groups.sort();
        for group in groups {
            let addrs = spec.deps.get(group).expect("group key from same map");
            // The govet binary is staged read-only (one tool, shared, hardlinked).
            let read_only = group.as_str() == GOVET_TOOL_GROUP;
            let annotations = if read_only {
                BTreeMap::from([(
                    hdriver_support::stage::READ_ONLY_ANNOTATION.to_string(),
                    "true".to_string(),
                )])
            } else {
                BTreeMap::new()
            };
            for (i, addr_str) in addrs.iter().enumerate() {
                inputs.push(Input {
                    r#ref: TargetAddr::parse(addr_str, &pkg)
                        .with_context(|| format!("parse dep addr {addr_str}"))?,
                    mode: InputMode::Standard,
                    origin_id: format!("dep|{group}|{i}"),
                    annotations: annotations.clone(),
                    hashed: true,
                    runtime: true,
                });
            }
        }

        let def = GoLintDef {
            import_path: spec.import_path,
            goos: spec.goos,
            goarch: spec.goarch,
            go_version: spec.go_version,
            import_paths: spec.import_paths,
        };

        let outputs: Vec<Output> = spec
            .out
            .iter()
            .map(|(group, paths)| Output {
                group: group.clone(),
                paths: paths
                    .iter()
                    .map(|p| {
                        let full_path = if pkg_str.is_empty() {
                            p.clone()
                        } else {
                            format!("{pkg_str}/{p}")
                        };
                        TPath {
                            content: Content::FilePath(full_path),
                            codegen_tree: CodegenMode::None,
                            collect: true,
                        }
                    })
                    .collect(),
            })
            .collect();

        let hash = {
            let mut h = DebugHasher::new(Xxh3Default::new(), || {
                format!("go_lint_{}", req.target_spec.addr.format())
            });
            def.hash(&mut h);
            format!("{:x}", h.finish()).into_bytes()
        };

        Ok(ParseResponse {
            target_def: TargetDef {
                addr: req.target_spec.addr.clone(),
                labels: req.target_spec.labels.clone(),
                raw_def: Arc::new(def),
                inputs,
                outputs,
                support_files: vec![],
                cache: CacheConfig::on(true),
                pty: false,
                hash,
                transparent: false,
            },
        })
    }

    async fn apply_transitive(
        &self,
        req: ApplyTransitiveRequest,
        _ctoken: &(dyn Cancellable + Send + Sync),
    ) -> anyhow::Result<ApplyTransitiveResponse> {
        Ok(ApplyTransitiveResponse {
            target_def: req.target_def,
        })
    }

    async fn run<'a, 'io>(
        &self,
        req: ManagedRunRequest<'a, 'io>,
        ctoken: &(dyn Cancellable + Send + Sync),
    ) -> anyhow::Result<ManagedRunResponse> {
        let def = req.request.target.def_de::<GoLintDef>();
        let pkg_dir = &req.sandbox_pkg_dir;

        // The govet binary (single staged file in its group).
        let govet_bin = self
            .single_staged_path(&req, GOVET_TOOL_GROUP)
            .context("locate staged heph-govet binary (govet_tool dep not staged?)")?;

        // Map each transitive import to its staged archive (type info) and, when
        // present, its staged facts (interprocedural analysis input).
        let mut package_file: BTreeMap<String, String> = BTreeMap::new();
        let mut import_map: BTreeMap<String, String> = BTreeMap::new();
        let mut package_vetx: BTreeMap<String, String> = BTreeMap::new();
        for ip in &def.import_paths {
            let lib_group = crate::plugingo::addr_util::import_path_to_dep_group(ip);
            let archive = self
                .single_staged_path(&req, &lib_group)
                .with_context(|| format!("locate staged archive for lib {ip}"))?;
            package_file.insert(ip.clone(), archive);
            import_map.insert(ip.clone(), ip.clone());

            // Facts are optional: stdlib (or any not-yet-linted) deps have no
            // facts group. unitchecker treats a missing PackageVetx entry as
            // "no facts", which is correct — those analyzers degrade to
            // intra-package for that one dependency only.
            let facts_group = import_path_to_facts_group(ip);
            if let Ok(facts) = self.single_staged_path(&req, &facts_group) {
                package_vetx.insert(ip.clone(), facts);
            }
        }

        let go_files = self.group_staged_paths(&req, "");
        let vetx_output = pkg_dir.join(LINT_FACTS);

        let cfg = UnitcheckerConfig {
            compiler: "gc".to_string(),
            dir: pkg_dir.to_string_lossy().into_owned(),
            import_path: def.import_path.clone(),
            go_version: format!("go{}", def.go_version),
            go_files,
            non_go_files: vec![],
            ignored_files: vec![],
            import_map,
            package_file,
            // We do not currently distinguish stdlib here; analyzers that special
            // -case the standard library will treat all deps as non-standard.
            standard: BTreeMap::new(),
            package_vetx,
            vetx_only: false,
            vetx_output: vetx_output.to_string_lossy().into_owned(),
            // A type-check failure is a real error for us — do not mask it.
            succeed_on_typecheck_failure: false,
        };

        let cfg_path = pkg_dir.join("unitchecker.cfg");
        std::fs::write(
            &cfg_path,
            serde_json::to_vec(&cfg).context("serialize unitchecker cfg")?,
        )
        .context("write unitchecker cfg")?;

        // `.golangci.yml` (if staged) selects which analyzers heph-govet runs.
        // It is a hashed input, so a config change re-keys this target and
        // re-lints. Passed by env because unitchecker rejects unknown flags.
        let mut env: HashMap<String, String> = HashMap::new();
        if let Ok(config_path) = self.single_staged_path(&req, "config") {
            env.insert("HEPH_GOVET_GOLANGCI_CONFIG".to_string(), config_path);
        }

        // `-json`: unitchecker writes facts to VetxOutput and prints diagnostics
        // as JSON to stdout, exiting 0 even when findings exist. We capture that
        // JSON as the report; the gate target decides pass/fail. This keeps facts
        // produced and cached regardless of findings.
        let report = self
            .exec_govet(
                std::path::Path::new(&govet_bin),
                vec![
                    OsString::from("-json"),
                    OsString::from(cfg_path.as_os_str()),
                ],
                &env,
                pkg_dir,
                ctoken,
            )
            .await?;
        std::fs::write(pkg_dir.join(LINT_REPORT), report).context("write lint report")?;

        if !vetx_output.exists() {
            anyhow::bail!(
                "go_lint: heph-govet did not produce facts at {vetx_output:?} (cfg or analyzer error)"
            );
        }

        Ok(ManagedRunResponse { artifacts: vec![] })
    }
}

impl GoLintDriver {
    /// All staged file paths for the inputs in dep `group` (origin `dep|group|*`).
    fn group_staged_paths(&self, req: &ManagedRunRequest<'_, '_>, group: &str) -> Vec<String> {
        let prefix = format!("dep|{group}|");
        let mut out: Vec<String> = Vec::new();
        for m in &req.inputs {
            if !m.input.origin_id.starts_with(&prefix) {
                continue;
            }
            let Ok(list_path) = m.require_list_path() else {
                continue;
            };
            if let Ok(f) = std::fs::File::open(list_path) {
                for line in std::io::BufReader::new(f).lines().map_while(Result::ok) {
                    if !line.is_empty() {
                        out.push(line);
                    }
                }
            }
        }
        out
    }

    /// The single staged path for a one-output group (lib archive, facts, tool).
    fn single_staged_path(
        &self,
        req: &ManagedRunRequest<'_, '_>,
        group: &str,
    ) -> anyhow::Result<String> {
        self.group_staged_paths(req, group)
            .into_iter()
            .next()
            .ok_or_else(|| anyhow::anyhow!("no staged file for dep group {group}"))
    }

    /// Run `heph-govet`, returning captured stdout (the `-json` report). A
    /// non-zero exit means the tool itself failed (bad cfg, type-check error) —
    /// findings do NOT fail here, `-json` makes the tool exit 0 for those.
    async fn exec_govet(
        &self,
        govet_bin: &std::path::Path,
        args: Vec<OsString>,
        env: &HashMap<String, String>,
        cwd: &std::path::Path,
        ctoken: &(dyn Cancellable + Send + Sync),
    ) -> anyhow::Result<Vec<u8>> {
        let env_pairs: Vec<(OsString, OsString)> = env
            .iter()
            .map(|(k, v)| (OsString::from(k), OsString::from(v)))
            .collect();
        let spec = proc_exec::Spec {
            program: govet_bin.to_path_buf(),
            args,
            env: env_pairs,
            cwd: cwd.to_path_buf(),
            stdin: proc_exec::StdioSpec::Null,
            stdout: proc_exec::StdioSpec::Piped,
            stderr: proc_exec::StdioSpec::Piped,
            setsid: false,
            ctty: false,
        };
        let output = proc_exec::output(spec, ctoken)
            .await
            .context("wait for heph-govet")?;
        if !output.status.success() {
            let stderr = String::from_utf8_lossy(&output.stderr);
            let stdout = String::from_utf8_lossy(&output.stdout);
            anyhow::bail!(
                "heph-govet failed ({}):\nstderr:\n{}\nstdout:\n{}",
                output.status,
                hplugin::error::last_n_lines(stderr.trim(), 20),
                hplugin::error::last_n_lines(stdout.trim(), 20),
            );
        }
        Ok(output.stdout)
    }
}

// ---------------------------------------------------------------------------
// Gate driver: fails the build when a package's lint report has findings.
//
// `go_lint` (the analyze target, `_lint`) always exits 0 so facts are produced
// and cached even for a package with findings — otherwise dependents could not
// build their own facts. `go_lint_gate` (the user-facing `lint` target) consumes
// the analyze target's `report` output and is the thing that actually fails:
// cheap, cache-keyed on the report bytes, separate from fact production.
// ---------------------------------------------------------------------------

pub struct GoLintGateDriver;

impl GoLintGateDriver {
    pub fn new() -> Self {
        Self
    }
}

impl Default for GoLintGateDriver {
    fn default() -> Self {
        Self::new()
    }
}

#[derive(Spec)]
struct GoLintGateSpec {
    /// Dependencies, grouped by name → list of target addresses. The `report`
    /// group carries the analyze target's `lint-report.json` output.
    deps: HashMap<String, Vec<String>>,
}

#[derive(Clone, serde::Serialize, serde::Deserialize)]
struct GoLintGateDef;

const GO_LINT_GATE_FORMAT_VERSION: u32 = 1;

/// Parse a `unitchecker -json` report into a flat list of human-readable
/// findings. The report shape is `{ "import/path": { "analyzer": [ {"posn":…,
/// "message":…}, … ] } }`; an empty object (`{}`) means no findings.
fn report_findings(json: &[u8]) -> anyhow::Result<Vec<String>> {
    if json.iter().all(u8::is_ascii_whitespace) {
        return Ok(Vec::new());
    }
    let root: serde_json::Value =
        serde_json::from_slice(json).context("parse unitchecker json report")?;
    let Some(by_pkg) = root.as_object() else {
        return Ok(Vec::new());
    };
    let mut out = Vec::new();
    for (pkg, by_analyzer) in by_pkg {
        let Some(by_analyzer) = by_analyzer.as_object() else {
            continue;
        };
        for (analyzer, diags) in by_analyzer {
            let Some(diags) = diags.as_array() else {
                continue;
            };
            for d in diags {
                let posn = d.get("posn").and_then(|v| v.as_str()).unwrap_or("");
                let message = d.get("message").and_then(|v| v.as_str()).unwrap_or("");
                out.push(format!("{posn}: {message} ({analyzer}) [{pkg}]"));
            }
        }
    }
    Ok(out)
}

#[async_trait]
impl ManagedDriver for GoLintGateDriver {
    fn config(&self, _req: ConfigRequest) -> anyhow::Result<ConfigResponse> {
        Ok(ConfigResponse {
            name: "go_lint_gate".to_string(),
        })
    }

    fn schema(&self) -> hplugin::driver::DriverSchema {
        GoLintGateSpec::schema()
    }

    async fn parse(
        &self,
        req: ParseRequest,
        _ctoken: &(dyn Cancellable + Send + Sync),
    ) -> anyhow::Result<ParseResponse> {
        let pkg = req.target_spec.addr.package.clone();
        let spec =
            GoLintGateSpec::from(req.target_spec.config.clone()).context("parse go_lint_gate")?;

        let mut inputs: Vec<Input> = Vec::new();
        let mut groups: Vec<&String> = spec.deps.keys().collect();
        groups.sort();
        for group in groups {
            for (i, addr_str) in spec.deps.get(group).expect("group key").iter().enumerate() {
                inputs.push(Input {
                    r#ref: TargetAddr::parse(addr_str, &pkg)
                        .with_context(|| format!("parse dep addr {addr_str}"))?,
                    mode: InputMode::Standard,
                    origin_id: format!("dep|{group}|{i}"),
                    annotations: BTreeMap::new(),
                    hashed: true,
                    runtime: true,
                });
            }
        }

        let hash = {
            let mut h = DebugHasher::new(Xxh3Default::new(), || {
                format!("go_lint_gate_{}", req.target_spec.addr.format())
            });
            GO_LINT_GATE_FORMAT_VERSION.hash(&mut h);
            format!("{:x}", h.finish()).into_bytes()
        };

        Ok(ParseResponse {
            target_def: TargetDef {
                addr: req.target_spec.addr.clone(),
                labels: req.target_spec.labels.clone(),
                raw_def: Arc::new(GoLintGateDef),
                inputs,
                outputs: vec![],
                support_files: vec![],
                cache: CacheConfig::on(true),
                pty: false,
                hash,
                transparent: false,
            },
        })
    }

    async fn apply_transitive(
        &self,
        req: ApplyTransitiveRequest,
        _ctoken: &(dyn Cancellable + Send + Sync),
    ) -> anyhow::Result<ApplyTransitiveResponse> {
        Ok(ApplyTransitiveResponse {
            target_def: req.target_def,
        })
    }

    async fn run<'a, 'io>(
        &self,
        req: ManagedRunRequest<'a, 'io>,
        _ctoken: &(dyn Cancellable + Send + Sync),
    ) -> anyhow::Result<ManagedRunResponse> {
        // Single staged report file (origin `dep|report|*`).
        let mut report_path: Option<String> = None;
        for m in &req.inputs {
            if !m.input.origin_id.starts_with("dep|report|") {
                continue;
            }
            if let Ok(list_path) = m.require_list_path()
                && let Ok(f) = std::fs::File::open(list_path)
            {
                for line in std::io::BufReader::new(f).lines().map_while(Result::ok) {
                    if !line.is_empty() {
                        report_path = Some(line);
                        break;
                    }
                }
            }
        }
        let report_path =
            report_path.ok_or_else(|| anyhow::anyhow!("go_lint_gate: no lint report staged"))?;
        let bytes = std::fs::read(&report_path)
            .with_context(|| format!("read lint report {report_path}"))?;
        let findings = report_findings(&bytes)?;
        if !findings.is_empty() {
            anyhow::bail!("lint found {} issue(s):\n{}", findings.len(), findings.join("\n"));
        }
        Ok(ManagedRunResponse { artifacts: vec![] })
    }
}

// ---------------------------------------------------------------------------
// Provider-facing spec builder
// ---------------------------------------------------------------------------

use crate::plugingo::addr_util::import_path_to_dep_group;
use crate::plugingo::factors::Factors;
use hcore::htvalue::Value;
use hmodel::htaddr::Addr;
use hplugin::provider::TargetSpec;

/// Parameters for [`build_lint_spec`].
pub struct LintParams<'a> {
    pub addr: Addr,
    /// Import path of the package under analysis.
    pub import_path: &'a str,
    pub factors: &'a Factors,
    pub go_version: &'a str,
    /// `(import_path, build_lib archive addr)` — `lib_*` dep groups + cfg
    /// PackageFile entries (type info for every transitive dependency).
    pub transitive_libs: &'a [(String, Addr)],
    /// `(import_path, lint addr)` — `facts_*` dep groups; the deps whose facts
    /// feed interprocedural analysis. Subset of `transitive_libs` (e.g. omit
    /// stdlib until it is linted too).
    pub facts_libs: &'a [(String, Addr)],
    /// Compile sources (`.go`) → the default (`""`) dep group.
    pub src_addrs: &'a [String],
    /// `build` addr of the `heph-govet` unitchecker binary.
    pub govet_addr: &'a Addr,
    /// `.golangci.yml` file addr → `config` dep group, passed to heph-govet via
    /// `HEPH_GOVET_GOLANGCI_CONFIG`. `None` → the standard analyzer set.
    pub config_addr: Option<&'a Addr>,
}

/// Build a `go_lint` target spec.
pub fn build_lint_spec(p: LintParams) -> TargetSpec {
    let str_one = |a: &Addr| Value::List(vec![Value::String(a.format())]);

    let mut deps: BTreeMap<String, Value> = p
        .transitive_libs
        .iter()
        .map(|(import_path, dep_addr)| (import_path_to_dep_group(import_path), str_one(dep_addr)))
        .collect();
    for (import_path, lint_addr) in p.facts_libs {
        deps.insert(import_path_to_facts_group(import_path), str_one(lint_addr));
    }
    deps.insert(
        String::new(),
        Value::List(p.src_addrs.iter().cloned().map(Value::String).collect()),
    );
    deps.insert(GOVET_TOOL_GROUP.to_string(), str_one(p.govet_addr));
    if let Some(cfg) = p.config_addr {
        deps.insert("config".to_string(), str_one(cfg));
    }

    // Sorted for an order-independent cache key (see GoLintDef::hash).
    let mut import_paths: Vec<String> =
        p.transitive_libs.iter().map(|(ip, _)| ip.clone()).collect();
    import_paths.sort();
    let import_paths: Vec<Value> = import_paths.into_iter().map(Value::String).collect();

    let mut config: HashMap<String, Value> = HashMap::new();
    config.insert(
        "import_path".to_string(),
        Value::String(p.import_path.to_string()),
    );
    config.insert("goos".to_string(), Value::String(p.factors.goos.clone()));
    config.insert(
        "goarch".to_string(),
        Value::String(p.factors.goarch.clone()),
    );
    config.insert(
        "go_version".to_string(),
        Value::String(p.go_version.to_string()),
    );
    config.insert("import_paths".to_string(), Value::List(import_paths));
    config.insert("deps".to_string(), Value::Map(deps.into_iter().collect()));
    config.insert(
        "out".to_string(),
        Value::Map(HashMap::from([
            (
                "facts".to_string(),
                Value::List(vec![Value::String(LINT_FACTS.to_string())]),
            ),
            (
                "report".to_string(),
                Value::List(vec![Value::String(LINT_REPORT.to_string())]),
            ),
        ])),
    );

    TargetSpec {
        addr: p.addr,
        driver: "go_lint".to_string(),
        config,
        labels: vec!["go-lint".to_string()],
        transitive: Default::default(),
    }
}

/// Build the user-facing `lint` gate spec. Depends on the `report` output of the
/// analyze target (`_lint`) and fails the build when it contains findings.
pub fn build_lint_gate_spec(addr: Addr, analyze_addr: &Addr) -> TargetSpec {
    let deps = BTreeMap::from([(
        "report".to_string(),
        Value::List(vec![Value::String(format!(
            "{}|report",
            analyze_addr.format()
        ))]),
    )]);
    let mut config: HashMap<String, Value> = HashMap::new();
    config.insert("deps".to_string(), Value::Map(deps.into_iter().collect()));

    TargetSpec {
        addr,
        driver: "go_lint_gate".to_string(),
        config,
        labels: vec!["go-lint".to_string()],
        transitive: Default::default(),
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use hmodel::htpkg::PkgBuf;

    const V: &str = crate::plugingo::toolchain::DEFAULT_GO_VERSION;

    fn factors() -> Factors {
        Factors {
            goos: "linux".into(),
            goarch: "amd64".into(),
            build_tags: vec![],
        }
    }

    fn addr(name: &str) -> Addr {
        Addr::new(PkgBuf::from("mylib"), name.to_string(), Default::default())
    }

    fn govet() -> Addr {
        Addr::new(
            PkgBuf::from("tools/heph-govet"),
            "build".to_string(),
            Default::default(),
        )
    }

    fn lib(ip: &str, name: &str) -> (String, Addr) {
        (
            ip.to_string(),
            Addr::new(PkgBuf::from("dep"), name.to_string(), Default::default()),
        )
    }

    fn spec(libs: &[(String, Addr)], facts: &[(String, Addr)]) -> TargetSpec {
        spec_cfg(libs, facts, None)
    }

    fn spec_cfg(
        libs: &[(String, Addr)],
        facts: &[(String, Addr)],
        config_addr: Option<&Addr>,
    ) -> TargetSpec {
        let g = govet();
        build_lint_spec(LintParams {
            addr: addr("lint"),
            import_path: "example.com/mylib",
            factors: &factors(),
            go_version: V,
            transitive_libs: libs,
            facts_libs: facts,
            src_addrs: &["//mylib:a.go".to_string()],
            govet_addr: &g,
            config_addr,
        })
    }

    fn deps_map(s: &TargetSpec) -> HashMap<String, Vec<String>> {
        match s.config.get("deps").unwrap() {
            Value::Map(m) => m
                .iter()
                .map(|(k, v)| {
                    let list = match v {
                        Value::List(l) => l
                            .iter()
                            .map(|x| match x {
                                Value::String(s) => s.clone(),
                                _ => panic!("dep entry not a string"),
                            })
                            .collect(),
                        _ => panic!("dep group not a list"),
                    };
                    (k.clone(), list)
                })
                .collect(),
            _ => panic!("deps not a map"),
        }
    }

    #[test]
    fn driver_is_go_lint() {
        assert_eq!(spec(&[], &[]).driver, "go_lint");
    }

    #[test]
    fn sources_in_default_group() {
        assert_eq!(
            deps_map(&spec(&[], &[])).get("").unwrap(),
            &vec!["//mylib:a.go".to_string()]
        );
    }

    #[test]
    fn govet_tool_group_present() {
        assert!(deps_map(&spec(&[], &[])).contains_key(GOVET_TOOL_GROUP));
    }

    #[test]
    fn lib_group_for_each_transitive_archive() {
        let l = lib("fmt", "fmt");
        let s = spec(std::slice::from_ref(&l), &[]);
        assert!(deps_map(&s).contains_key("lib_fmt"));
    }

    // A dep that is itself linted contributes a facts_* group; a dep that is not
    // (e.g. stdlib) contributes only its lib_* archive — facts are optional.
    #[test]
    fn facts_group_only_for_facts_libs() {
        let archive = lib("example.com/dep", "build_lib");
        let factsdep = (
            "example.com/dep".to_string(),
            Addr::new(
                PkgBuf::from("dep"),
                "lint".to_string(),
                Default::default(),
            ),
        );
        let s = spec(
            std::slice::from_ref(&archive),
            std::slice::from_ref(&factsdep),
        );
        let m = deps_map(&s);
        assert!(m.contains_key("lib_example_com_dep"), "archive group");
        assert!(m.contains_key("facts_example_com_dep"), "facts group");
    }

    #[test]
    fn no_facts_group_when_dep_not_linted() {
        let archive = lib("fmt", "build_lib");
        let s = spec(std::slice::from_ref(&archive), &[]);
        assert!(!deps_map(&s).contains_key("facts_fmt"));
    }

    #[test]
    fn declares_facts_and_report_outputs() {
        let s = spec(&[], &[]);
        let out = match s.config.get("out").unwrap() {
            Value::Map(m) => m,
            _ => panic!("out not a map"),
        };
        assert!(out.contains_key("facts"));
        assert!(out.contains_key("report"));
    }

    #[test]
    fn has_go_lint_label() {
        assert!(spec(&[], &[]).labels.contains(&"go-lint".to_string()));
    }

    #[test]
    fn config_group_present_only_when_config_addr_given() {
        assert!(!deps_map(&spec(&[], &[])).contains_key("config"));
        let cfg = Addr::new(PkgBuf::from(""), ".golangci.yml".to_string(), Default::default());
        let s = spec_cfg(&[], &[], Some(&cfg));
        assert!(deps_map(&s).contains_key("config"));
    }

    #[test]
    fn import_path_in_config() {
        match spec(&[], &[]).config.get("import_path").unwrap() {
            Value::String(s) => assert_eq!(s, "example.com/mylib"),
            _ => panic!("import_path not a string"),
        }
    }

    // ---- gate ----

    #[test]
    fn gate_empty_report_has_no_findings() {
        assert!(report_findings(b"{}").unwrap().is_empty());
        assert!(report_findings(b"   \n ").unwrap().is_empty());
        assert!(report_findings(b"").unwrap().is_empty());
    }

    #[test]
    fn gate_extracts_findings_with_posn_and_message() {
        let json = br#"{
            "example.com/mylib": {
                "printf": [
                    {"posn": "a.go:10:2", "message": "Printf format %d has arg s of wrong type string"}
                ],
                "lostcancel": [
                    {"posn": "a.go:20:2", "message": "the cancel function is not used"}
                ]
            }
        }"#;
        let f = report_findings(json).unwrap();
        assert_eq!(f.len(), 2);
        assert!(f.iter().any(|s| s.contains("a.go:10:2") && s.contains("printf")));
        assert!(f.iter().any(|s| s.contains("lostcancel")));
    }

    #[test]
    fn gate_empty_analyzer_arrays_yield_no_findings() {
        let json = br#"{"example.com/mylib": {"printf": []}}"#;
        assert!(report_findings(json).unwrap().is_empty());
    }

    #[test]
    fn gate_spec_driver_and_report_dep() {
        let analyze = Addr::new(
            PkgBuf::from("mylib"),
            "_lint".to_string(),
            Default::default(),
        );
        let s = build_lint_gate_spec(addr("lint"), &analyze);
        assert_eq!(s.driver, "go_lint_gate");
        let deps = match s.config.get("deps").unwrap() {
            Value::Map(m) => m,
            _ => panic!("deps not a map"),
        };
        let report = match deps.get("report").unwrap() {
            Value::List(l) => l,
            _ => panic!("report not a list"),
        };
        match &report[0] {
            Value::String(s) => assert!(
                s.contains(":_lint") && s.ends_with("|report"),
                "gate must depend on the analyze target's report output: {s}"
            ),
            _ => panic!("not a string"),
        }
    }
}
