//! `go_compile` — the single driver that compiles a Go package archive.
//!
//! Replaces the former `sh`-scripted compile *and* the separate `go_embed`
//! target: importcfg generation, `//go:embed` resolution, the asm/symabis/pack
//! pipeline, and `go tool compile` all happen in one target. Folding embed into
//! the compile means embed assets are staged once (here), not also into a
//! separate `go_embed` sandbox — and the `go_embed_src` lane (assets kept out of
//! `_golist`) is resolved in-process against the staged files with the
//! Go-faithful selector in [`crate::plugingo::embed`].
//!
//! Mirrors the exact flag set the old scripts used (`-p`, `-trimpath`, `-pack`,
//! `-shared`, `-symabis`, `-asmhdr`, `-embedcfg`) so archives stay
//! byte-compatible.

use crate::plugingo::embed;
use crate::plugingo::factors::BuildMode;
use crate::plugingo::pkg_analysis::decode_go_package;
use anyhow::Context;
use async_trait::async_trait;
use hcore::debug_hash::DebugHasher;
use hcore::hasync::Cancellable;
use hdriver_support::driver_managed::{ManagedDriver, ManagedRunRequest, ManagedRunResponse};
use hplugin::driver::targetdef::path::{CodegenMode, Content, Path};
use hplugin::driver::targetdef::{CacheConfig, Input, InputMode, Output, TargetDef};
use hplugin::driver::{
    ApplyTransitiveRequest, ApplyTransitiveResponse, ConfigRequest, ConfigResponse, ParseRequest,
    ParseResponse, TargetAddr,
};
use hplugin::htspec::Spec;
use hproc::proc_exec;
use std::collections::BTreeMap;
use std::collections::HashMap;
use std::ffi::OsString;
use std::hash::{Hash, Hasher};
use std::io::BufRead;
use std::sync::Arc;
use xxhash_rust::xxh3::Xxh3Default;

pub struct GoCompileDriver {
    /// Default exec runner for this driver's tool, from the plugin's `runner:`
    /// option in the config yaml. A target's own `runner` field overrides it,
    /// and `"local"` there opts back out. See [`crate::plugingo::runner`].
    default_runner: Option<String>,
    /// Host `go` resolved in whatever environment the runner names — see
    /// [`crate::plugingo::toolchain::HostGoCache`]. Only ever touched by
    /// `gotool = "host"`.
    host_go: crate::plugingo::toolchain::HostGoCache,
}

impl GoCompileDriver {
    pub fn new() -> Self {
        Self {
            default_runner: None,
            host_go: Default::default(),
        }
    }

    /// Set the driver-wide default runner (the plugin's `runner:` option).
    /// `None` and `Some("local")` both mean "spawn on the host".
    #[must_use]
    pub fn with_default_runner(mut self, runner: Option<String>) -> Self {
        self.default_runner = runner;
        self
    }
}

impl Default for GoCompileDriver {
    fn default() -> Self {
        Self::new()
    }
}

/// Which embed set to resolve, matching the variants the old `go_embed` target
/// exposed. `None`-equivalent (no embedcfg) is encoded by leaving
/// `embed_variant` empty in the spec.
#[derive(Clone, Copy, PartialEq, Debug, serde::Serialize, serde::Deserialize)]
pub enum EmbedVariant {
    Embed,
    /// embed ∪ test — `build_test_lib` compiles GoFiles+TestGoFiles together.
    TestEmbed,
    XtestEmbed,
}

impl EmbedVariant {
    fn parse(s: &str) -> Option<Self> {
        match s {
            "embed" => Some(Self::Embed),
            "test_embed" => Some(Self::TestEmbed),
            "xtest_embed" => Some(Self::XtestEmbed),
            _ => None,
        }
    }
    fn hash_tag(self) -> u8 {
        match self {
            Self::Embed => 0,
            Self::TestEmbed => 1,
            Self::XtestEmbed => 2,
        }
    }
}

/// Config for a `go_compile` target (engine-generated by the Go provider).
#[derive(Spec)]
struct GoCompileSpec {
    /// `-p` flag: `main` for main packages, else the import path.
    #[spec(required)]
    p_flag: String,
    /// Output archive filename (package-relative).
    #[spec(required)]
    out_file: String,
    /// Target GOOS.
    #[spec(required)]
    goos: String,
    /// Target GOARCH.
    #[spec(required)]
    goarch: String,
    /// Go release whose staged hermetic SDK provides GOROOT + the `go` binary.
    #[spec(required)]
    go_version: String,
    /// Workspace-relative `go.mod` directory of this package's module, selecting
    /// which module's shared `GOCACHE` the compile runs against. Empty for the
    /// root module and for stdlib.
    go_module: String,
    /// The variant this compile belongs to, from `Factors::variant_id` — the
    /// other half of the cache's `(module, variant)` identity. Absent from
    /// `Hash` for the same reason as `go_module`: it selects a cache, it does
    /// not change the archive.
    go_variant: String,
    /// `GOEXPERIMENT` values from the variant (sorted). Empty → unset.
    goexperiment: Vec<String>,
    /// Extra flags passed verbatim to `go tool compile` (the variant's gcflags).
    gcflags: Vec<String>,
    /// Variant buildmode (`exe`/`pie`); empty → `exe`. Decides whether the
    /// compile/asm steps get `-shared`, which must agree with the link's
    /// `-buildmode=` (see `BuildMode::needs_shared`).
    buildmode: String,
    /// Race-detector build: pass `-race` to `go tool compile`, instrumenting every
    /// memory access in this package. Whole-program — every archive in the link
    /// must agree — so it rides the address and keys this archive's cache.
    race: bool,
    /// Import paths of the transitive libs, in deterministic order — each maps to
    /// a `lib_<sanitized>` dep group carrying that archive, used to build
    /// importcfg.
    import_paths: Vec<String>,
    /// `.s` assembly source names (package-relative). Empty → no asm pipeline.
    s_files: Vec<String>,
    /// Which embed set to resolve (`embed`/`test_embed`/`xtest_embed`), or empty
    /// for no embedcfg.
    embed_variant: Vec<String>,
    /// Dependencies, grouped by name → list of target addresses.
    deps: HashMap<String, Vec<String>>,
    /// Declared outputs, grouped by name → list of output paths.
    out: HashMap<String, Vec<String>>,
    /// Exec runner this tool runs under: a target address producing a
    /// `runner.json`, so the tool runs inside a described environment (a devenv
    /// shell, a container) instead of on the bare host. Absent, or the literal
    /// `"local"`, spawns here as before. A hashed dependency, so changing the
    /// environment re-keys this target.
    runner: String,
}

#[derive(Clone, serde::Serialize, serde::Deserialize)]
struct GoCompileDef {
    p_flag: String,
    out_file: String,
    goos: String,
    goarch: String,
    go_version: String,
    /// Which module's shared `GOCACHE` to use. Deliberately absent from `Hash`,
    /// for the same reason the scratch input is `hashed: false`: a compile
    /// produces the same archive whether its cache is warm, cold or absent, so
    /// folding this in would make moving a package between modules rebuild the
    /// world for no change in output.
    go_module: String,
    /// The variant this compile belongs to, from `Factors::variant_id` — the
    /// other half of the cache's `(module, variant)` identity. Absent from
    /// `Hash` for the same reason as `go_module`: it selects a cache, it does
    /// not change the archive.
    go_variant: String,
    goexperiment: Vec<String>,
    gcflags: Vec<String>,
    buildmode: BuildMode,
    /// See [`GoCompileSpec::race`].
    race: bool,
    import_paths: Vec<String>,
    s_files: Vec<String>,
    embed_variant: Option<EmbedVariant>,
    /// origin_id of the `golist|pkg` input (present iff embed_variant is set).
    golist_origin_id: Option<String>,
    /// origin_ids of the `go_embed_src` inputs (assets `go list` never saw).
    embed_src_origin_ids: Vec<String>,
    /// Exec runner for this target's tool. Deliberately absent from `Hash` —
    /// see `plugingo::runner`: it reaches the cache key through the hashout of
    /// the input `parse` emits, exactly as a `hash_dep` does.
    runner: Option<TargetAddr>,
}

/// Bump to invalidate every cached `go_compile` archive whenever the compile
/// command shape or embed resolution semantics change.
const GO_COMPILE_FORMAT_VERSION: u32 = 4;

impl Hash for GoCompileDef {
    fn hash<H: Hasher>(&self, state: &mut H) {
        GO_COMPILE_FORMAT_VERSION.hash(state);
        self.p_flag.hash(state);
        self.out_file.hash(state);
        self.goos.hash(state);
        self.goarch.hash(state);
        self.go_version.hash(state);
        // Variant toolchain knobs — each changes compiler output, so each must
        // key the cache. `goexperiment` is already sorted at variant-parse time;
        // `gcflags` order is semantically meaningful, so hash as-is.
        self.goexperiment.hash(state);
        self.gcflags.hash(state);
        // `-shared` presence hangs off this, and a `-shared` archive is not
        // interchangeable with a plain one.
        self.buildmode.hash(state);
        // Hashed only when set, so introducing race mode left every ordinary
        // archive's def hash — and the caches holding them — untouched. The
        // marker is a distinct string, so it cannot alias a neighbouring field.
        if self.race {
            "race".hash(state);
        }
        // `import_paths` order is not semantically meaningful — it comes from a
        // closure walk that dedups through a per-process-randomized `HashSet`,
        // and `run()` re-sorts before writing importcfg, so the archive is
        // identical regardless of order. Hash a sorted view so the cache key is
        // order-invariant at the boundary, independent of how the spec was built.
        let mut import_paths: Vec<&str> = self.import_paths.iter().map(String::as_str).collect();
        import_paths.sort_unstable();
        import_paths.len().hash(state);
        for ip in import_paths {
            ip.hash(state);
        }
        self.s_files.hash(state);
        self.embed_variant.map(|v| v.hash_tag()).hash(state);
        self.golist_origin_id.hash(state);
        self.embed_src_origin_ids.hash(state);
        // Archives, sources, SDK arrive via inputs; the engine hashes their
        // content, so no per-file hashing here.
    }
}

#[async_trait]
impl ManagedDriver for GoCompileDriver {
    fn config(&self, _req: ConfigRequest) -> anyhow::Result<ConfigResponse> {
        Ok(ConfigResponse {
            name: "go_compile".to_string(),
        })
    }

    fn schema(&self) -> hplugin::driver::DriverSchema {
        GoCompileSpec::schema()
    }

    async fn parse(
        &self,
        req: ParseRequest,
        _ctoken: &(dyn Cancellable + Send + Sync),
    ) -> anyhow::Result<ParseResponse> {
        let pkg = req.target_spec.addr.package.clone();
        let pkg_str = pkg.as_str();
        let spec =
            GoCompileSpec::from(&req.target_spec.config).context("parse go_compile config")?;

        let mut inputs: Vec<Input> = Vec::new();
        let mut golist_origin_id: Option<String> = None;
        let mut embed_src_origin_ids: Vec<String> = Vec::new();

        let mut groups: Vec<&String> = spec.deps.keys().collect();
        groups.sort();
        for group in groups {
            let addrs = spec.deps.get(group).expect("group key from same map");
            let is_sdk = group.as_str() == crate::plugingo::addr_util::GO_SDK_DEP_GROUP;
            let is_embed_src = group.as_str() == "embed_src";
            // SDK and embed assets are read-only: staged once into the shared
            // stage and hardlinked in. embed_src also goes per-file so the run
            // step can enumerate it from the list.
            let annotations = if is_sdk {
                BTreeMap::from([(
                    hdriver_support::stage::READ_ONLY_ANNOTATION.to_string(),
                    "true".to_string(),
                )])
            } else if is_embed_src {
                BTreeMap::from([
                    (
                        hdriver_support::stage::READ_ONLY_ANNOTATION.to_string(),
                        "true".to_string(),
                    ),
                    (
                        hdriver_support::stage::STAGE_PER_FILE_ANNOTATION.to_string(),
                        "true".to_string(),
                    ),
                ])
            } else {
                BTreeMap::new()
            };
            for (i, addr_str) in addrs.iter().enumerate() {
                let origin_id = format!("dep|{group}|{i}");
                if group == "golist" && golist_origin_id.is_none() {
                    golist_origin_id = Some(origin_id.clone());
                }
                if is_embed_src {
                    embed_src_origin_ids.push(origin_id.clone());
                }
                inputs.push(Input {
                    r#ref: TargetAddr::parse(addr_str, &pkg)
                        .with_context(|| format!("parse dep addr {addr_str}"))?,
                    mode: InputMode::Standard,
                    origin_id,
                    annotations: annotations.clone(),
                    hashed: true,
                    runtime: true,
                });
            }
        }

        let embed_variant = spec
            .embed_variant
            .first()
            .and_then(|s| EmbedVariant::parse(s));

        // Absent (or empty) means the default `exe`; an unrecognized spelling is
        // a hard error rather than a silent fallback — it would change the
        // linkage of the produced binary.
        let buildmode = if spec.buildmode.is_empty() {
            BuildMode::default()
        } else {
            BuildMode::parse(&spec.buildmode).ok_or_else(|| {
                anyhow::anyhow!(
                    "unknown `buildmode` `{}` (allowed: {})",
                    spec.buildmode,
                    BuildMode::NAMES.join(", ")
                )
            })?
        };

        let (runner, runner_input) = super::runner::parse_runner_with_default(
            &spec.runner,
            self.default_runner.as_deref(),
            &pkg,
        )?;
        inputs.extend(runner_input);

        let def = GoCompileDef {
            runner,
            p_flag: spec.p_flag,
            out_file: spec.out_file,
            goos: spec.goos,
            goarch: spec.goarch,
            go_version: spec.go_version,
            go_module: spec.go_module,
            go_variant: spec.go_variant,
            goexperiment: spec.goexperiment,
            gcflags: spec.gcflags,
            buildmode,
            race: spec.race,
            import_paths: spec.import_paths,
            s_files: spec.s_files,
            embed_variant,
            golist_origin_id: if embed_variant.is_some() {
                golist_origin_id
            } else {
                None
            },
            embed_src_origin_ids,
        };

        let outputs: Vec<Output> = spec
            .out
            .iter()
            .map(|(group, paths)| Output {
                group: group.clone(),
                paths: paths
                    .iter()
                    .map(|p| {
                        let full_path = if pkg_str.is_empty() {
                            p.clone()
                        } else {
                            format!("{pkg_str}/{p}")
                        };
                        Path {
                            content: Content::FilePath(full_path),
                            codegen_tree: CodegenMode::None,
                            collect: true,
                        }
                    })
                    .collect(),
            })
            .collect();

        let hash = {
            let mut h = DebugHasher::new(Xxh3Default::new(), || {
                format!("go_compile_{}", req.target_spec.addr.format())
            });
            def.hash(&mut h);
            format!("{:x}", h.finish()).into_bytes()
        };

        // The shared `GOCACHE`, as a scratch reference — one cache per Go module
        // per variant, the same slot the golist targets of that module and
        // variant use (see `plugingo::gocache`). Until recently every compile
        // target created and tore down an *empty* cache inside its own sandbox:
        // the exact pattern the golist sharing was written to remove, left in
        // place here because that fix was driver-local.
        //
        // This used to drop `build_tags` from the key, reasoning that a compile's
        // entries cannot depend on a file set that `go list` already fixed. True
        // in itself, and still the wrong call: `go_golist` *did* key on them, so
        // a tagged variant got two caches and neither warmed the other. The
        // variant now travels whole, from `Factors::variant_id`, so the two
        // drivers cannot key on different subsets. The cost is a cold start on a
        // variant that differs only in a factor its entries ignore; the thing it
        // buys is that "one cache per module per variant" is true rather than
        // approximately true.
        let gocache_key = crate::plugingo::gocache::GocacheKey {
            module: def.go_module.clone(),
            go_version: def.go_version.clone(),
            goos: def.goos.clone(),
            goarch: def.goarch.clone(),
            variant: def.go_variant.clone(),
        };
        let gocache_input = Input {
            r#ref: TargetAddr {
                r#ref: gocache_key.addr(),
                output: None,
                filters: vec![],
            },
            mode: InputMode::Standard,
            origin_id: format!("{}|0", hdriver_support::scratch::SCRATCH_ORIGIN_PREFIX),
            annotations: std::collections::BTreeMap::from([(
                hdriver_support::scratch::SCRATCH_ANNOTATION.to_string(),
                "true".to_string(),
            )]),
            hashed: false,
            runtime: false,
        };

        Ok(ParseResponse {
            target_def: TargetDef {
                addr: req.target_spec.addr.clone(),
                labels: req.target_spec.labels.clone(),
                raw_def: Arc::new(def),
                inputs: inputs.into_iter().chain([gocache_input]).collect(),
                outputs,
                support_files: vec![],
                cache: CacheConfig::on(true),
                pty: false,
                hash,
                transparent: false,
            },
        })
    }

    async fn apply_transitive(
        &self,
        req: ApplyTransitiveRequest,
        _ctoken: &(dyn Cancellable + Send + Sync),
    ) -> anyhow::Result<ApplyTransitiveResponse> {
        Ok(ApplyTransitiveResponse {
            target_def: req.target_def,
        })
    }

    async fn run<'a, 'io>(
        &self,
        req: ManagedRunRequest<'a, 'io>,
        ctoken: &(dyn Cancellable + Send + Sync),
    ) -> anyhow::Result<ManagedRunResponse> {
        let def = req.request.target.def_de::<GoCompileDef>();
        let pkg_dir = &req.sandbox_pkg_dir;
        let ws_root = req.sandbox_ws_dir.to_string_lossy().into_owned();

        // GOROOT / go binary for the selected toolchain — host, target-ref, or
        // hermetic staged SDK (mirrors go_golist, see `resolve_toolchain_go`).
        use crate::plugingo::toolchain::Toolchain;
        let runner = super::runner::runner_ref(req.request.request_id, def.runner.as_ref());
        let (goroot, go_bin) = crate::plugingo::toolchain::resolve_toolchain_go(
            &def.go_version,
            &req.inputs,
            &req.sandbox_ws_dir,
            "go_compile",
            runner,
            &self.host_go,
            ctoken,
        )
        .await?;

        // Resolved and locked by the host from this target's scratch reference.
        //
        // No mount means `--no-scratch`, not an old host: the plugin and the
        // host share one `ABI_SEMVER` and a mismatch fails at `dlopen`. A
        // sandbox-local directory rather than no `GOCACHE`, because Go reads
        // `~/.cache/go-build` when the variable is unset — the audit would then
        // consult and pollute the developer's real cache instead of running
        // cold.
        let gocache = match req.request.scratch.iter().find(|m| m.env == "GOCACHE") {
            Some(mount) => mount.dir.clone(),
            None => {
                let local = pkg_dir.join(".heph-gocache");
                std::fs::create_dir_all(&local)
                    .with_context(|| format!("create gocache dir {local:?}"))?;
                local
            }
        };

        let mut env: HashMap<String, String> = HashMap::new();
        env.insert("GOOS".to_string(), def.goos.clone());
        env.insert("GOARCH".to_string(), def.goarch.clone());
        env.insert("GOROOT".to_string(), goroot.to_string_lossy().into_owned());
        env.insert(
            "GOCACHE".to_string(),
            gocache.to_string_lossy().into_owned(),
        );
        env.insert("GOTOOLCHAIN".to_string(), "local".to_string());
        env.insert("GOWORK".to_string(), "off".to_string());
        // `1` only for a race build off darwin, matching the golist and link
        // sandboxes — see `factors::cgo_required`. The archives this driver
        // produces are pure Go either way; the setting exists so `go tool
        // compile`'s view of the build config matches everyone else's.
        env.insert(
            "CGO_ENABLED".to_string(),
            crate::plugingo::factors::cgo_enabled_value(&def.goos, def.race).to_string(),
        );
        if !def.goexperiment.is_empty() {
            env.insert("GOEXPERIMENT".to_string(), def.goexperiment.join(","));
        }
        // Non-hermetic toolchains (host, or a hostbin/nix target wrapper) may need
        // PATH; hermetic mode omits it to stay PATH-independent.
        if !matches!(
            crate::plugingo::toolchain::classify(&def.go_version),
            Toolchain::Hermetic(_)
        ) && let Ok(v) = std::env::var("PATH")
        {
            env.insert("PATH".to_string(), v);
        }

        // 1. importcfg: one `packagefile <import>=<archive>` per transitive lib,
        //    sorted by import path (matches the old write_importcfg_script).
        let mut import_paths = def.import_paths.clone();
        import_paths.sort();
        let mut importcfg = String::new();
        for ip in &import_paths {
            let group = crate::plugingo::addr_util::import_path_to_dep_group(ip);
            let archive = self
                .single_staged_path(&req, &group)
                .with_context(|| format!("locate staged archive for lib {ip}"))?;
            importcfg.push_str(&format!("packagefile {ip}={archive}\n"));
        }
        let importcfg_path = pkg_dir.join("importcfg");
        std::fs::write(&importcfg_path, &importcfg).context("write importcfg")?;

        // 2. sources response file: every staged `.go` source in the default group.
        let src_paths = self.group_staged_paths(&req, "");
        let rsp_path = pkg_dir.join("gofiles.rsp");
        std::fs::write(&rsp_path, src_paths.join("\n")).context("write sources response file")?;

        // 3. embedcfg (optional): patterns from go list ∪ go_embed_src resolution.
        let has_embed = if let Some(variant) = def.embed_variant {
            let embedcfg = self
                .compute_embedcfg(&req, def, variant)
                .context("compute embedcfg")?;
            std::fs::write(pkg_dir.join("embedcfg"), embedcfg).context("write embedcfg")?;
            true
        } else {
            false
        };

        let has_asm = !def.s_files.is_empty();
        // `-shared` iff the link is PIE — cmd/go couples them the same way, and a
        // mismatch is a link failure, not a slower binary. A race build on linux
        // already had its buildmode forced to `exe` at variant resolution
        // (`BuildMode::for_race`), so it lands here as a plain archive — matching
        // the stdlib `go install -race` produced for that mode.
        let shared: Option<&str> = def.buildmode.needs_shared().then_some("-shared");
        let trimpath = format!("-trimpath={ws_root}");
        let goinc = format!("{}/pkg/include", goroot.to_string_lossy());

        let run_go =
            |args: Vec<String>| -> Vec<OsString> { args.into_iter().map(OsString::from).collect() };

        // Every `go tool` step below runs under the target's exec runner, so a
        // compile configured to happen inside an environment happens there for
        // asm and pack too, not only for the compile itself.

        // 4. asm step 0+1: seed go_asm.h, then -gensymabis → symabis.
        if has_asm {
            std::fs::write(pkg_dir.join("go_asm.h"), b"").context("seed go_asm.h")?;
            let mut args = vec![
                "tool".to_string(),
                "asm".to_string(),
                "-p".to_string(),
                def.p_flag.clone(),
                trimpath.clone(),
                "-I".to_string(),
                ".".to_string(),
                "-I".to_string(),
                goinc.clone(),
                "-D".to_string(),
                format!("GOOS_{}", def.goos),
                "-D".to_string(),
                format!("GOARCH_{}", def.goarch),
            ];
            args.extend(shared.map(str::to_string));
            args.extend([
                "-gensymabis".to_string(),
                "-o".to_string(),
                "symabis".to_string(),
            ]);
            for s in &def.s_files {
                args.push(format!("./{s}"));
            }
            self.exec_go(
                &go_bin,
                run_go(args),
                &env,
                pkg_dir,
                runner,
                ctoken,
                "asm -gensymabis",
            )
            .await?;
        }

        // 5. compile.
        let mut cargs = vec![
            "tool".to_string(),
            "compile".to_string(),
            "-p".to_string(),
            def.p_flag.clone(),
            trimpath.clone(),
            "-pack".to_string(),
            "-importcfg".to_string(),
            importcfg_path.to_string_lossy().into_owned(),
        ];
        // Race instrumentation. Before the variant gcflags so a variant can still
        // override it if it ever needs to, and so the flag order matches what
        // `go build -race` itself emits.
        if def.race {
            cargs.push("-race".to_string());
        }
        // Variant gcflags — raw `go tool compile` flags (what `-gcflags` forwards),
        // in declared order, before the source responses.
        cargs.extend(def.gcflags.iter().cloned());
        if has_asm {
            cargs.push("-symabis".to_string());
            cargs.push("symabis".to_string());
            cargs.push("-asmhdr".to_string());
            cargs.push("go_asm.h".to_string());
        }
        if has_embed {
            cargs.push("-embedcfg".to_string());
            cargs.push("embedcfg".to_string());
        }
        cargs.extend(shared.map(str::to_string));
        cargs.push("-o".to_string());
        cargs.push(def.out_file.clone());
        cargs.push(format!("@{}", rsp_path.to_string_lossy()));
        self.exec_go(
            &go_bin,
            run_go(cargs),
            &env,
            pkg_dir,
            runner,
            ctoken,
            "compile",
        )
        .await?;

        // 6. asm step 3+4: assemble each .s, then pack into the archive.
        if has_asm {
            for s in &def.s_files {
                let obj = format!("{}.o", s.trim_end_matches(".s"));
                let mut args = vec![
                    "tool".to_string(),
                    "asm".to_string(),
                    "-p".to_string(),
                    def.p_flag.clone(),
                    trimpath.clone(),
                    "-I".to_string(),
                    ".".to_string(),
                    "-I".to_string(),
                    goinc.clone(),
                    "-D".to_string(),
                    format!("GOOS_{}", def.goos),
                    "-D".to_string(),
                    format!("GOARCH_{}", def.goarch),
                ];
                args.extend(shared.map(str::to_string));
                args.extend(["-o".to_string(), obj, format!("./{s}")]);
                self.exec_go(&go_bin, run_go(args), &env, pkg_dir, runner, ctoken, "asm")
                    .await?;
            }
            let mut pargs = vec![
                "tool".to_string(),
                "pack".to_string(),
                "r".to_string(),
                def.out_file.clone(),
            ];
            for s in &def.s_files {
                pargs.push(format!("{}.o", s.trim_end_matches(".s")));
            }
            self.exec_go(
                &go_bin,
                run_go(pargs),
                &env,
                pkg_dir,
                runner,
                ctoken,
                "pack",
            )
            .await?;
        }

        Ok(ManagedRunResponse { artifacts: vec![] })
    }
}

impl GoCompileDriver {
    /// All staged file paths for the inputs in dep `group` (origin `dep|group|*`).
    fn group_staged_paths(&self, req: &ManagedRunRequest<'_, '_>, group: &str) -> Vec<String> {
        let prefix = format!("dep|{group}|");
        let mut out: Vec<String> = Vec::new();
        for m in &req.inputs {
            if !m.input.origin_id.starts_with(&prefix) {
                continue;
            }
            let Ok(list_path) = m.require_list_path() else {
                continue;
            };
            if let Ok(f) = std::fs::File::open(list_path) {
                for line in std::io::BufReader::new(f).lines().map_while(Result::ok) {
                    if !line.is_empty() {
                        out.push(line);
                    }
                }
            }
        }
        out
    }

    /// The single staged path for a one-output group (e.g. a lib archive).
    fn single_staged_path(
        &self,
        req: &ManagedRunRequest<'_, '_>,
        group: &str,
    ) -> anyhow::Result<String> {
        self.group_staged_paths(req, group)
            .into_iter()
            .next()
            .ok_or_else(|| anyhow::anyhow!("no staged file for dep group {group}"))
    }

    /// Resolve the embedcfg JSON for `variant`: union Go's authoritative
    /// EmbedFiles (from the `golist` package.bin) with the selector's resolution
    /// of the staged `go_embed_src` assets, then group under each pattern.
    fn compute_embedcfg(
        &self,
        req: &ManagedRunRequest<'_, '_>,
        def: &GoCompileDef,
        variant: EmbedVariant,
    ) -> anyhow::Result<String> {
        let golist_origin = def
            .golist_origin_id
            .as_deref()
            .ok_or_else(|| anyhow::anyhow!("go_compile: embed requested but no golist input"))?;
        let managed = req
            .inputs
            .iter()
            .find(|m| m.input.origin_id == golist_origin)
            .ok_or_else(|| anyhow::anyhow!("go_compile: golist input not found"))?;
        let list_path = managed.require_list_path()?;
        let list_f = std::fs::File::open(list_path)
            .with_context(|| format!("open golist list {list_path:?}"))?;
        let pkg_bin_path = std::io::BufReader::new(list_f)
            .lines()
            .map_while(Result::ok)
            .find(|s| !s.is_empty() && s.ends_with("package.bin"))
            .ok_or_else(|| anyhow::anyhow!("go_compile: package.bin not found in golist input"))?;
        let pkg =
            decode_go_package(std::fs::File::open(&pkg_bin_path).context("open package.bin")?)
                .context("decode package.bin")?;

        let (patterns, go_src_files) = match variant {
            EmbedVariant::Embed => (pkg.embed_patterns.clone(), pkg.embed_files.clone()),
            EmbedVariant::TestEmbed => (
                pkg.embed_patterns
                    .iter()
                    .chain(pkg.test_embed_patterns.iter())
                    .cloned()
                    .collect(),
                pkg.embed_files
                    .iter()
                    .chain(pkg.test_embed_files.iter())
                    .cloned()
                    .collect(),
            ),
            EmbedVariant::XtestEmbed => (
                pkg.xtest_embed_patterns.clone(),
                pkg.xtest_embed_files.clone(),
            ),
        };

        let embed_src_rel = self.collect_embed_src_rel(req, &def.embed_src_origin_ids)?;
        let files = embed::merge_embed_files(go_src_files, &patterns, &embed_src_rel);
        embed::compute_embed_cfg_json(&patterns, &files)
    }

    /// Staged `go_embed_src` files as package-relative, `/`-separated paths.
    fn collect_embed_src_rel(
        &self,
        req: &ManagedRunRequest<'_, '_>,
        origin_ids: &[String],
    ) -> anyhow::Result<Vec<String>> {
        let mut rel: Vec<String> = Vec::new();
        for id in origin_ids {
            // A `go_embed_src` dep can be a query that matched no targets (e.g. a
            // package with only checked-in `go_src` embeds). The engine elides
            // such inputs, so a missing origin here means "no files", not an
            // error — an actually-unresolved embed pattern surfaces downstream
            // in `compute_embed_cfg_json`'s zero-match check.
            let Some(managed) = req.inputs.iter().find(|m| m.input.origin_id == *id) else {
                continue;
            };
            let Ok(list_path) = managed.require_list_path() else {
                continue;
            };
            let f = std::fs::File::open(list_path)
                .with_context(|| format!("open embed_src list {list_path:?}"))?;
            for line in std::io::BufReader::new(f).lines() {
                let line = line.context("read embed_src list line")?;
                if line.is_empty() {
                    continue;
                }
                let abs = std::path::Path::new(&line);
                let r = abs.strip_prefix(&req.sandbox_pkg_dir).unwrap_or(abs);
                rel.push(r.to_string_lossy().replace('\\', "/"));
            }
        }
        Ok(rel)
    }

    #[expect(
        clippy::too_many_arguments,
        reason = "one private helper threading a single `go tool` invocation; \
                  grouping these into a struct would only move the argument list"
    )]
    async fn exec_go(
        &self,
        go_bin: &std::path::Path,
        args: Vec<OsString>,
        env: &HashMap<String, String>,
        cwd: &std::path::Path,
        runner: hexecrunner::RunnerRef<'_>,
        ctoken: &(dyn Cancellable + Send + Sync),
        step: &str,
    ) -> anyhow::Result<()> {
        let env_pairs: Vec<(OsString, OsString)> = env
            .iter()
            .map(|(k, v)| (OsString::from(k), OsString::from(v)))
            .collect();
        let spec = proc_exec::Spec {
            program: go_bin.to_path_buf(),
            args,
            env: env_pairs,
            cwd: cwd.to_path_buf(),
            stdin: proc_exec::StdioSpec::Null,
            stdout: proc_exec::StdioSpec::Piped,
            stderr: proc_exec::StdioSpec::Piped,
            setsid: false,
            ctty: false,
        };
        let output = hexecrunner::output(runner, spec, ctoken)
            .await
            .with_context(|| format!("wait for go {step}"))?;
        if !output.status.success() {
            let stderr = String::from_utf8_lossy(&output.stderr);
            let stdout = String::from_utf8_lossy(&output.stdout);
            anyhow::bail!(
                "go {step} failed ({}):\n{}",
                output.status,
                go_failure_detail(&stdout, &stderr)
            );
        }
        Ok(())
    }
}

/// Build the human-readable detail for a failed `go` invocation. `go tool` writes
/// diagnostics to stderr, but some failures (and the `go` wrapper itself) print on
/// stdout, so a stderr-only message can come back blank — useless. Include both
/// (labelled, last 20 lines each) and fall back to an explicit marker when both
/// are empty, so the error always says something actionable.
fn go_failure_detail(stdout: &str, stderr: &str) -> String {
    let stderr_tail = hplugin::error::last_n_lines(stderr.trim(), 20);
    let stdout_tail = hplugin::error::last_n_lines(stdout.trim(), 20);
    let mut detail = String::new();
    if !stderr_tail.is_empty() {
        detail.push_str("stderr:\n");
        detail.push_str(&stderr_tail);
    }
    if !stdout_tail.is_empty() {
        if !detail.is_empty() {
            detail.push('\n');
        }
        detail.push_str("stdout:\n");
        detail.push_str(&stdout_tail);
    }
    if detail.is_empty() {
        "<no output on stdout or stderr>".to_string()
    } else {
        detail
    }
}

// ---------------------------------------------------------------------------
// Provider-facing spec builder
// ---------------------------------------------------------------------------

use crate::plugingo::addr_util::{go_sdk_dep, import_path_to_dep_group};
use crate::plugingo::factors::Factors;
use hcore::htvalue::Value;
use hmodel::htaddr::Addr;
use hplugin::provider::TargetSpec;

/// Parameters for [`build_compile_spec`]. Groups the (necessarily many) compile
/// inputs so each builder (`target_lib`, `target_test`, `thirdparty`) just fills
/// this in.
pub struct CompileParams<'a> {
    pub addr: Addr,
    /// `-p` flag: `main` for main packages, else the import path.
    pub p_flag: String,
    /// Output archive filename (package-relative).
    pub out_file: String,
    pub factors: &'a Factors,
    pub go_version: &'a str,
    /// Workspace-relative `go.mod` directory selecting the module's `GOCACHE`.
    pub go_module: &'a str,
    /// `(import_path, lib archive addr)` — importcfg entries + `lib_*` dep groups.
    pub transitive_libs: &'a [(String, Addr)],
    /// Compile sources (`.go`) → the default (`""`) dep group.
    pub src_addrs: &'a [String],
    /// `.s` assembly source names (package-relative) driving the asm steps.
    pub s_files: &'a [String],
    /// Addrs that stage the `.s` sources into the sandbox.
    pub s_file_addrs: &'a [String],
    /// `.h` header addrs (next to / `#include`d by the `.s` sources).
    pub hdr_addrs: &'a [String],
    /// `golist|pkg` addr — read for `EmbedPatterns`/`EmbedFiles`. `Some` iff the
    /// package embeds.
    pub golist_addr: Option<&'a Addr>,
    /// `""` for no embed, else `embed` / `test_embed` / `xtest_embed`.
    pub embed_variant: &'a str,
    /// `go_src` embed file addrs (Go resolved) staged for the compile.
    pub embed_file_addrs: &'a [String],
    /// `go_embed_src` lane addrs (assets `go list` never saw), resolved in-driver.
    pub embed_src_addrs: &'a [String],
}

/// Build a `go_compile` target spec. Replaces the former `sh`-script compile and
/// the separate `go_embed` target.
pub fn build_compile_spec(p: CompileParams) -> TargetSpec {
    let mut deps: BTreeMap<String, Value> = p
        .transitive_libs
        .iter()
        .map(|(import_path, dep_addr)| {
            (
                import_path_to_dep_group(import_path),
                Value::List(vec![Value::String(dep_addr.format())]),
            )
        })
        .collect();

    let str_list = |v: &[String]| Value::List(v.iter().cloned().map(Value::String).collect());

    deps.insert(String::new(), str_list(p.src_addrs));
    if !p.s_file_addrs.is_empty() {
        deps.insert("asm".to_string(), str_list(p.s_file_addrs));
    }
    if !p.hdr_addrs.is_empty() {
        deps.insert("hdr".to_string(), str_list(p.hdr_addrs));
    }
    let embedding = !p.embed_variant.is_empty();
    if embedding && let Some(golist) = p.golist_addr {
        deps.insert(
            "golist".to_string(),
            Value::List(vec![Value::String(format!("{}|pkg", golist.format()))]),
        );
    }
    if !p.embed_file_addrs.is_empty() {
        deps.insert("embed_files".to_string(), str_list(p.embed_file_addrs));
    }
    if !p.embed_src_addrs.is_empty() {
        deps.insert("embed_src".to_string(), str_list(p.embed_src_addrs));
    }
    if let Some((sdk_group, sdk_val)) = go_sdk_dep(p.go_version) {
        deps.insert(sdk_group, sdk_val);
    }

    // Sort so the config (and thus the GoCompileDef cache key) is independent of
    // the order `transitive_libs` arrives in. The closure walk dedups imports
    // through a HashSet whose iteration order is randomized per process; without
    // this sort the hash flips every run and the whole graph rebuilds even though
    // run() already sorts before writing importcfg, so the archive is identical.
    let mut import_paths: Vec<String> =
        p.transitive_libs.iter().map(|(ip, _)| ip.clone()).collect();
    import_paths.sort();
    let import_paths: Vec<Value> = import_paths.into_iter().map(Value::String).collect();

    let mut config: HashMap<String, Value> = HashMap::new();
    config.insert("p_flag".to_string(), Value::String(p.p_flag));
    config.insert("out_file".to_string(), Value::String(p.out_file.clone()));
    config.insert("goos".to_string(), Value::String(p.factors.goos.clone()));
    config.insert(
        "goarch".to_string(),
        Value::String(p.factors.goarch.clone()),
    );
    config.insert(
        "go_version".to_string(),
        Value::String(p.go_version.to_string()),
    );
    config.insert(
        "go_module".to_string(),
        Value::String(p.go_module.to_string()),
    );
    // Computed here rather than passed in: `build_compile_spec` already holds the
    // variant, so there is no call site that could hand it a different one.
    config.insert(
        "go_variant".to_string(),
        Value::String(p.factors.variant_id()),
    );
    config.insert(
        "goexperiment".to_string(),
        str_list(&p.factors.goexperiment),
    );
    config.insert("gcflags".to_string(), str_list(&p.factors.gcflags));
    config.insert(
        "buildmode".to_string(),
        Value::String(p.factors.buildmode.as_str().to_string()),
    );
    // Set only for a race build, so an ordinary archive's spec (and def hash) is
    // exactly what it was before race mode existed.
    if p.factors.race {
        config.insert("race".to_string(), Value::Bool(true));
    }
    config.insert("import_paths".to_string(), Value::List(import_paths));
    config.insert("s_files".to_string(), str_list(p.s_files));
    config.insert(
        "embed_variant".to_string(),
        if embedding {
            Value::List(vec![Value::String(p.embed_variant.to_string())])
        } else {
            Value::List(vec![])
        },
    );
    config.insert("deps".to_string(), Value::Map(deps.into_iter().collect()));
    config.insert(
        "out".to_string(),
        Value::Map(HashMap::from([(
            "a".to_string(),
            Value::List(vec![Value::String(p.out_file)]),
        )])),
    );
    // NOTE: unlike the old `sh` compile, GOOS/GOARCH/CGO/GOTOOLCHAIN/GOWORK and
    // read-only/host-env handling are NOT config keys — the managed driver sets
    // env directly in run() and marks read-only via input annotations. Cache
    // correctness rides on GoCompileDef (go_version, goos, goarch, format ver).

    TargetSpec {
        addr: p.addr,
        driver: "go_compile".to_string(),
        config,
        labels: vec!["go-build".to_string()],
        ..Default::default()
    }
}

#[cfg(test)]
mod driver_tests {
    use super::*;
    use crate::plugingo::factors::Factors;
    use hmodel::htpkg::PkgBuf;

    const V: &str = crate::plugingo::toolchain::DEFAULT_GO_VERSION;

    // A failed `go` invocation must never report a blank body. Regression: the
    // message only included stderr, so a failure that printed on stdout (or
    // nowhere) surfaced as `go compile failed:` with nothing after it.
    #[test]
    fn go_failure_detail_surfaces_each_stream() {
        // stderr only
        let d = go_failure_detail("", "boom on stderr");
        assert!(d.contains("stderr:") && d.contains("boom on stderr"), "{d}");
        assert!(!d.contains("stdout:"), "{d}");
        // stdout only — must not come back blank
        let d = go_failure_detail("boom on stdout", "");
        assert!(d.contains("stdout:") && d.contains("boom on stdout"), "{d}");
        // both streams present
        let d = go_failure_detail("out msg", "err msg");
        assert!(d.contains("out msg") && d.contains("err msg"), "{d}");
        // neither — explicit marker, never empty
        let d = go_failure_detail("", "   \n  ");
        assert_eq!(d, "<no output on stdout or stderr>");
    }

    fn factors() -> Factors {
        Factors {
            goos: "linux".into(),
            goarch: "amd64".into(),
            build_tags: vec![],
            ..Default::default()
        }
    }

    async fn parse_def(spec: TargetSpec) -> TargetDef {
        let ct = hcore::hasync::StdCancellationToken::new();
        GoCompileDriver::new()
            .parse(
                ParseRequest {
                    request_id: "t".to_string(),
                    target_spec: std::sync::Arc::new(spec),
                },
                &ct,
            )
            .await
            .unwrap()
            .target_def
    }

    /// The plugin's `runner:` config-yaml option reaches a generated target.
    /// Nothing populates the `runner` spec field for provider-generated Go
    /// targets, so the option is the only path to a non-host runner here.
    #[tokio::test]
    async fn the_driver_default_runner_reaches_the_parsed_inputs() {
        let ct = hcore::hasync::StdCancellationToken::new();
        let def = GoCompileDriver::new()
            .with_default_runner(Some("//tools/devenv:runner".to_string()))
            .parse(
                ParseRequest {
                    request_id: "t".to_string(),
                    target_spec: std::sync::Arc::new(spec_with_buildmode(BuildMode::Exe)),
                },
                &ct,
            )
            .await
            .expect("parse")
            .target_def;
        let runner: Vec<_> = def
            .inputs
            .iter()
            .filter(|i| i.origin_id == crate::plugingo::runner::RUNNER_ORIGIN)
            .collect();
        assert_eq!(
            runner.len(),
            1,
            "expected exactly one runner input, got {}",
            runner.len()
        );
        let input = runner.first().expect("runner input");
        assert_eq!(input.r#ref.r#ref.format(), "//tools/devenv:runner");
        assert!(input.hashed, "must key the cache");
        assert!(!input.runtime, "must not reach the sandbox");
    }

    #[tokio::test]
    async fn parse_embed_src_inputs_are_read_only_per_file_and_capture_golist() {
        let golist = Addr::new(
            PkgBuf::from("mylib"),
            "_golist".to_string(),
            Default::default(),
        );
        let spec = build_compile_spec(CompileParams {
            addr: Addr::new(
                PkgBuf::from("mylib"),
                "build_lib".to_string(),
                Default::default(),
            ),
            p_flag: "example.com/mylib".to_string(),
            out_file: "x.a".to_string(),
            factors: &factors(),
            go_version: V,
            go_module: "",
            transitive_libs: &[],
            src_addrs: &["//mylib:a.go".to_string()],
            s_files: &[],
            s_file_addrs: &[],
            hdr_addrs: &[],
            golist_addr: Some(&golist),
            embed_variant: "embed",
            embed_file_addrs: &[],
            embed_src_addrs: &["//mylib:frontend".to_string()],
        });
        let def = parse_def(spec).await;
        let es = def
            .inputs
            .iter()
            .find(|i| i.origin_id.starts_with("dep|embed_src|"))
            .expect("embed_src input present");
        assert_eq!(
            es.annotations
                .get(hdriver_support::stage::READ_ONLY_ANNOTATION)
                .map(String::as_str),
            Some("true")
        );
        assert_eq!(
            es.annotations
                .get(hdriver_support::stage::STAGE_PER_FILE_ANNOTATION)
                .map(String::as_str),
            Some("true")
        );
        let d = def.def::<GoCompileDef>();
        assert_eq!(d.embed_variant, Some(EmbedVariant::Embed));
        assert!(d.golist_origin_id.is_some(), "golist origin captured");
        assert_eq!(d.embed_src_origin_ids.len(), 1);
    }

    #[tokio::test]
    async fn parse_no_embed_leaves_variant_and_golist_unset() {
        let spec = build_compile_spec(CompileParams {
            addr: Addr::new(
                PkgBuf::from("mylib"),
                "build_lib".to_string(),
                Default::default(),
            ),
            p_flag: "example.com/mylib".to_string(),
            out_file: "x.a".to_string(),
            factors: &factors(),
            go_version: V,
            go_module: "",
            transitive_libs: &[],
            src_addrs: &["//mylib:a.go".to_string()],
            s_files: &[],
            s_file_addrs: &[],
            hdr_addrs: &[],
            golist_addr: None,
            embed_variant: "",
            embed_file_addrs: &[],
            embed_src_addrs: &[],
        });
        let def = parse_def(spec).await;
        let d = def.def::<GoCompileDef>();
        assert_eq!(d.embed_variant, None);
        assert!(d.golist_origin_id.is_none());
    }

    #[tokio::test]
    async fn parse_sdk_input_is_read_only() {
        let spec = build_compile_spec(CompileParams {
            addr: Addr::new(
                PkgBuf::from("mylib"),
                "build_lib".to_string(),
                Default::default(),
            ),
            p_flag: "example.com/mylib".to_string(),
            out_file: "x.a".to_string(),
            factors: &factors(),
            go_version: V,
            go_module: "",
            transitive_libs: &[],
            src_addrs: &["//mylib:a.go".to_string()],
            s_files: &[],
            s_file_addrs: &[],
            hdr_addrs: &[],
            golist_addr: None,
            embed_variant: "",
            embed_file_addrs: &[],
            embed_src_addrs: &[],
        });
        let def = parse_def(spec).await;
        let prefix = format!("dep|{}|", crate::plugingo::addr_util::GO_SDK_DEP_GROUP);
        let sdk = def
            .inputs
            .iter()
            .find(|i| i.origin_id.starts_with(&prefix))
            .expect("sdk input present");
        assert_eq!(
            sdk.annotations
                .get(hdriver_support::stage::READ_ONLY_ANNOTATION)
                .map(String::as_str),
            Some("true")
        );
    }

    fn spec_with_buildmode(buildmode: BuildMode) -> TargetSpec {
        build_compile_spec(CompileParams {
            addr: Addr::new(
                PkgBuf::from("mylib"),
                "build_lib".to_string(),
                Default::default(),
            ),
            p_flag: "example.com/mylib".to_string(),
            out_file: "x.a".to_string(),
            factors: &Factors {
                buildmode,
                ..factors()
            },
            go_version: V,
            go_module: "",
            transitive_libs: &[],
            src_addrs: &["//mylib:a.go".to_string()],
            s_files: &[],
            s_file_addrs: &[],
            hdr_addrs: &[],
            golist_addr: None,
            embed_variant: "",
            embed_file_addrs: &[],
            embed_src_addrs: &[],
        })
    }

    // A `pie` archive is compiled `-shared` and an `exe` one is not; the two are
    // NOT interchangeable (a `-shared` archive fails a non-PIE link). Serving one
    // from a cache entry keyed by the other is a build that cannot link.
    #[tokio::test]
    async fn buildmode_keys_the_compile_cache() {
        let exe = parse_def(spec_with_buildmode(BuildMode::Exe)).await;
        let pie = parse_def(spec_with_buildmode(BuildMode::Pie)).await;
        assert_eq!(exe.def::<GoCompileDef>().buildmode, BuildMode::Exe);
        assert_eq!(pie.def::<GoCompileDef>().buildmode, BuildMode::Pie);
        assert_ne!(
            exe.hash, pie.hash,
            "exe and pie archives must not share a cache key"
        );
    }

    // An unparseable buildmode must fail the parse rather than quietly linking a
    // different kind of binary than the author asked for.
    #[tokio::test]
    async fn unknown_buildmode_is_rejected() {
        let mut spec = spec_with_buildmode(BuildMode::Exe);
        spec.config.insert(
            "buildmode".to_string(),
            Value::String("c-archive".to_string()),
        );
        let ct = hcore::hasync::StdCancellationToken::new();
        let Err(err) = GoCompileDriver::new()
            .parse(
                ParseRequest {
                    request_id: "t".to_string(),
                    target_spec: std::sync::Arc::new(spec),
                },
                &ct,
            )
            .await
        else {
            panic!("an unknown buildmode must not parse");
        };
        assert!(
            format!("{err:#}").contains("unknown `buildmode` `c-archive`"),
            "{err:#}"
        );
    }

    fn def_hash(def: &GoCompileDef) -> u64 {
        let mut h = std::collections::hash_map::DefaultHasher::new();
        def.hash(&mut h);
        h.finish()
    }

    fn spec_with_libs(libs: &[(String, Addr)]) -> TargetSpec {
        build_compile_spec(CompileParams {
            addr: Addr::new(
                PkgBuf::from("mylib"),
                "build_lib".to_string(),
                Default::default(),
            ),
            p_flag: "example.com/mylib".to_string(),
            out_file: "x.a".to_string(),
            factors: &factors(),
            go_version: V,
            go_module: "",
            transitive_libs: libs,
            src_addrs: &["//mylib:a.go".to_string()],
            s_files: &[],
            s_file_addrs: &[],
            hdr_addrs: &[],
            golist_addr: None,
            embed_variant: "",
            embed_file_addrs: &[],
            embed_src_addrs: &[],
        })
    }

    // Regression: the closure walk dedups imports through a HashSet whose order
    // is randomized per process. import_paths must be sorted before it enters
    // the GoCompileDef hash, or the cache key flips every run and the whole graph
    // rebuilds even though the produced archive is byte-identical.
    #[tokio::test]
    async fn import_path_order_does_not_affect_compile_def_hash() {
        let lib = |ip: &str, name: &str| {
            (
                ip.to_string(),
                Addr::new(PkgBuf::from("dep"), name.to_string(), Default::default()),
            )
        };
        let forward = [
            lib("example.com/a", "a"),
            lib("example.com/b", "b"),
            lib("example.com/c", "c"),
        ];
        let reversed = [
            lib("example.com/c", "c"),
            lib("example.com/b", "b"),
            lib("example.com/a", "a"),
        ];

        let def_fwd = parse_def(spec_with_libs(&forward)).await;
        let def_rev = parse_def(spec_with_libs(&reversed)).await;
        let d_fwd = def_fwd.def::<GoCompileDef>();
        let d_rev = def_rev.def::<GoCompileDef>();

        assert_eq!(
            d_fwd.import_paths, d_rev.import_paths,
            "import_paths must be sorted regardless of input order"
        );
        assert_eq!(
            def_hash(d_fwd),
            def_hash(d_rev),
            "cache key must not depend on transitive_libs order"
        );
    }

    // The boundary guarantee: even a spec that somehow arrives with unsorted
    // import_paths (e.g. a stale on-disk spec, or a builder that forgot to sort)
    // must hash identically. This exercises `GoCompileDef::hash` directly,
    // bypassing `build_compile_spec`'s own sort — the regression the HEPH_DEBUG_HASH
    // dumps revealed: import_paths reached the hash in HashSet order and flipped
    // the cache key run-to-run.
    /// The spec only carries `race` when it is on, so an ordinary archive's spec
    /// is exactly what it was before race mode existed.
    #[test]
    fn compile_spec_carries_race_only_when_set() {
        let racy = Factors {
            race: true,
            ..factors()
        };
        assert!(!spec_with_factors(&factors()).config.contains_key("race"));
        assert!(matches!(
            spec_with_factors(&racy).config.get("race"),
            Some(Value::Bool(true))
        ));
    }

    fn spec_with_factors(f: &Factors) -> TargetSpec {
        build_compile_spec(CompileParams {
            addr: Addr::new(
                hmodel::htpkg::PkgBuf::from("mylib"),
                "build_lib".to_string(),
                Default::default(),
            ),
            p_flag: "example.com/mylib".to_string(),
            out_file: "mylib.a".to_string(),
            factors: f,
            go_version: crate::plugingo::toolchain::DEFAULT_GO_VERSION,
            go_module: "",
            transitive_libs: &[],
            src_addrs: &[],
            s_files: &[],
            s_file_addrs: &[],
            hdr_addrs: &[],
            golist_addr: None,
            embed_variant: "",
            embed_file_addrs: &[],
            embed_src_addrs: &[],
        })
    }

    /// Race must key the archive: the same source compiled with and without
    /// instrumentation is two different `.a` files, and mixing them in one link
    /// is a fingerprint mismatch at best.
    #[test]
    fn compile_def_hash_differs_for_race() {
        let plain = compile_def(false);
        let racy = compile_def(true);
        assert_ne!(def_hash(&plain), def_hash(&racy));
    }

    /// …and adding the field must not have moved the hash for ordinary archives,
    /// or every cached Go archive in existence would be invalidated. With
    /// `race: false` the hasher is fed exactly the byte sequence it was fed
    /// before race mode existed, because the new contribution sits behind
    /// `if self.race`.
    ///
    /// Update the constant only alongside a deliberate
    /// `GO_COMPILE_FORMAT_VERSION` bump — an unexplained change here means the
    /// whole archive cache is being thrown away.
    #[test]
    fn compile_def_hash_unchanged_for_non_race() {
        assert_eq!(def_hash(&compile_def(false)), NON_RACE_COMPILE_HASH);
    }

    /// Pinned at `GO_COMPILE_FORMAT_VERSION` 4 (the `buildmode` field's version).
    const NON_RACE_COMPILE_HASH: u64 = 11506013216469835997;

    fn compile_def(race: bool) -> GoCompileDef {
        GoCompileDef {
            runner: None,
            p_flag: "example.com/mylib".to_string(),
            out_file: "x.a".to_string(),
            goos: "linux".to_string(),
            goarch: "amd64".to_string(),
            go_version: crate::plugingo::toolchain::HASH_GOLDEN_GO_VERSION.to_string(),
            go_module: String::new(),
            go_variant: String::new(),
            goexperiment: vec![],
            gcflags: vec![],
            buildmode: BuildMode::default(),
            race,
            import_paths: vec!["fmt".to_string()],
            s_files: vec![],
            embed_variant: None,
            golist_origin_id: None,
            embed_src_origin_ids: vec![],
        }
    }

    #[test]
    fn compile_def_hash_invariant_under_import_path_permutation() {
        let mk = |ips: &[&str]| GoCompileDef {
            runner: None,
            p_flag: "example.com/mylib".to_string(),
            out_file: "x.a".to_string(),
            goos: "linux".to_string(),
            goarch: "amd64".to_string(),
            go_version: crate::plugingo::toolchain::HASH_GOLDEN_GO_VERSION.to_string(),
            go_module: String::new(),
            go_variant: String::new(),
            goexperiment: vec![],
            gcflags: vec![],
            buildmode: BuildMode::default(),
            race: false,
            import_paths: ips.iter().map(|s| s.to_string()).collect(),
            s_files: vec![],
            embed_variant: None,
            golist_origin_id: None,
            embed_src_origin_ids: vec![],
        };
        let a = mk(&["net", "os", "errors", "io", "crypto/rand"]);
        let b = mk(&["crypto/rand", "io", "net", "errors", "os"]);
        assert_eq!(
            def_hash(&a),
            def_hash(&b),
            "cache key must be invariant under import_paths order at the hash boundary"
        );
        // Sanity: a genuinely different import set still hashes differently.
        let c = mk(&["net", "os", "errors", "io"]);
        assert_ne!(
            def_hash(&a),
            def_hash(&c),
            "different import set must differ"
        );
    }
}

/// Shared helpers for asserting on `go_compile` specs from the builders' tests.
#[cfg(test)]
pub(crate) mod test_support {
    use hcore::htvalue::Value;
    use hplugin::provider::TargetSpec;
    use std::collections::HashMap;

    pub(crate) fn cfg_str(spec: &TargetSpec, k: &str) -> String {
        match spec
            .config
            .get(k)
            .unwrap_or_else(|| panic!("missing config {k}"))
        {
            Value::String(s) => s.clone(),
            v => panic!("{k} not a string: {v:?}"),
        }
    }

    pub(crate) fn cfg_list(spec: &TargetSpec, k: &str) -> Vec<String> {
        match spec
            .config
            .get(k)
            .unwrap_or_else(|| panic!("missing config {k}"))
        {
            Value::List(l) => l
                .iter()
                .map(|x| match x {
                    Value::String(s) => s.clone(),
                    _ => panic!("{k} entry not a string"),
                })
                .collect(),
            v => panic!("{k} not a list: {v:?}"),
        }
    }

    pub(crate) fn deps_map(spec: &TargetSpec) -> HashMap<String, Vec<String>> {
        match spec.config.get("deps").unwrap() {
            Value::Map(m) => m
                .iter()
                .map(|(k, v)| {
                    let list = match v {
                        Value::List(l) => l
                            .iter()
                            .map(|x| match x {
                                Value::String(s) => s.clone(),
                                _ => panic!("dep entry not a string"),
                            })
                            .collect(),
                        _ => panic!("dep group not a list"),
                    };
                    (k.clone(), list)
                })
                .collect(),
            _ => panic!("deps not a map"),
        }
    }
}
