//! `go_lint` — per-package go/analysis driver producing serialized facts.
//!
//! Mirrors [`crate::plugingo::driver_compile`] but instead of `go tool compile`
//! it runs the hermetic `heph-govet` binary (an `x/tools` unitchecker, built as
//! an ordinary Go target and staged read-only). It analyzes exactly ONE package:
//!
//!   - dep type info  → export data `.a` archives, via the `lib_*` dep groups
//!     (identical wiring to `go_compile`'s importcfg);
//!   - dep facts      → each dep's `lint.facts`, via the `facts_*` dep groups;
//!   - own facts out  → `lint.facts` (the `facts` output group), consumed by
//!     dependents;
//!   - diagnostics    → `lint-report.json` (the `report` output group), gated by
//!     a separate cheap target so facts are produced/cached even when a package
//!     currently has findings.
//!
//! Two user-facing targets sit on that one analyze unit:
//!
//!   - `lint-check` (`go_lint_gate`) — the read-only checker: consumes the report,
//!     fails on findings, writes nothing;
//!   - `lint` (`go_lint_fix`) — the fixer: applies the report's suggested fixes
//!     back into the sources (`codegen=in_place`).
//!
//! This is the nogo model. Per-package caching falls out of the engine's
//! content-hashing of inputs: a package re-lints only when its own sources, a
//! dep's archive, or a dep's facts change. Interprocedural analyzers (printf
//! wrappers, lostcancel, …) keep full fidelity because facts cross the boundary —
//! which export-data-only linting cannot do.

use anyhow::Context;
use async_trait::async_trait;
use hcore::debug_hash::DebugHasher;
use hcore::hasync::Cancellable;
use hdriver_support::driver_managed::{ManagedDriver, ManagedRunRequest, ManagedRunResponse};
use hplugin::driver::targetdef::path::{CodegenMode, Content, Path as TPath};
use hplugin::driver::targetdef::{CacheConfig, Input, InputMode, Output, TargetDef};
use hplugin::driver::{
    ApplyTransitiveRequest, ApplyTransitiveResponse, ConfigRequest, ConfigResponse, ParseRequest,
    ParseResponse, TargetAddr,
};
use hplugin::htspec::Spec;
use hproc::proc_exec;
use std::collections::BTreeMap;
use std::collections::HashMap;
use std::ffi::OsString;
use std::hash::{Hash, Hasher};
use std::io::BufRead;
use std::sync::Arc;
use xxhash_rust::xxh3::Xxh3Default;

/// Output filenames (package-relative). Kept in sync between [`build_lint_spec`]
/// (the declared outputs) and [`GoLintDriver::run`] (where they are written).
const LINT_FACTS: &str = "lint.facts";
const LINT_REPORT: &str = "lint-report.json";

/// Dep group carrying the `heph-govet` unitchecker binary.
const GOVET_TOOL_GROUP: &str = "govet_tool";

/// Dep group prefix for a dependency's serialized facts (parallel to the
/// `lib_*` archive groups). `"github.com/foo/bar"` → `"facts_github_com_foo_bar"`.
fn import_path_to_facts_group(import_path: &str) -> String {
    let sanitized: String = import_path
        .chars()
        .map(|c| {
            if c.is_alphanumeric() || c == '_' {
                c
            } else {
                '_'
            }
        })
        .collect();
    format!("facts_{sanitized}")
}

pub struct GoLintDriver;

impl GoLintDriver {
    pub fn new() -> Self {
        Self
    }
}

impl Default for GoLintDriver {
    fn default() -> Self {
        Self::new()
    }
}

/// Config for a `go_lint` target (engine-generated by the Go provider).
#[derive(Spec)]
struct GoLintSpec {
    /// Import path of the package under analysis (cfg `ImportPath`).
    #[spec(required)]
    import_path: String,
    /// Target GOOS.
    #[spec(required)]
    goos: String,
    /// Target GOARCH.
    #[spec(required)]
    goarch: String,
    /// Go release whose semantics drive the analysis (cfg `GoVersion`).
    #[spec(required)]
    go_version: String,
    /// Variant build tags (affect which files are analyzed).
    build_tags: Vec<String>,
    /// Variant `GOEXPERIMENT` values (sorted).
    goexperiment: Vec<String>,
    /// Import paths of the transitive libs, deterministic order — each maps to a
    /// `lib_<sanitized>` dep group (archive, for type info) and, when the dep is
    /// itself linted, a `facts_<sanitized>` group (its serialized facts).
    import_paths: Vec<String>,
    /// Dependencies, grouped by name → list of target addresses.
    deps: HashMap<String, Vec<String>>,
    /// Declared outputs, grouped by name → list of output paths.
    out: HashMap<String, Vec<String>>,
}

#[derive(Clone, serde::Serialize, serde::Deserialize)]
struct GoLintDef {
    import_path: String,
    goos: String,
    goarch: String,
    go_version: String,
    build_tags: Vec<String>,
    goexperiment: Vec<String>,
    import_paths: Vec<String>,
}

/// Bump to invalidate every cached `go_lint` result whenever the cfg shape or
/// the analyzer set baked into `heph-govet` changes in a way the binary's own
/// input hash does not already capture.
const GO_LINT_FORMAT_VERSION: u32 = 1;

impl Hash for GoLintDef {
    fn hash<H: Hasher>(&self, state: &mut H) {
        GO_LINT_FORMAT_VERSION.hash(state);
        self.import_path.hash(state);
        self.goos.hash(state);
        self.goarch.hash(state);
        self.go_version.hash(state);
        self.build_tags.hash(state);
        self.goexperiment.hash(state);
        // Order-invariant, exactly as `go_compile` does: the closure walk dedups
        // through a per-process-randomized HashSet, so hash a sorted view or the
        // cache key flips every run.
        let mut import_paths: Vec<&str> = self.import_paths.iter().map(String::as_str).collect();
        import_paths.sort_unstable();
        import_paths.len().hash(state);
        for ip in import_paths {
            ip.hash(state);
        }
        // Sources, archives, facts and the govet binary arrive via inputs; the
        // engine hashes their content, so no per-file hashing here. A change to
        // the analyzer set changes the govet binary's bytes → its input hash →
        // this target's hash.
    }
}

/// cfg.json schema understood by `golang.org/x/tools/go/analysis/unitchecker`.
/// Field names serialize to the PascalCase keys the Go side expects.
#[derive(serde::Serialize)]
#[serde(rename_all = "PascalCase")]
struct UnitcheckerConfig {
    compiler: String,
    dir: String,
    import_path: String,
    go_version: String,
    go_files: Vec<String>,
    non_go_files: Vec<String>,
    ignored_files: Vec<String>,
    import_map: BTreeMap<String, String>,
    package_file: BTreeMap<String, String>,
    standard: BTreeMap<String, bool>,
    package_vetx: BTreeMap<String, String>,
    vetx_only: bool,
    vetx_output: String,
    succeed_on_typecheck_failure: bool,
}

#[async_trait]
impl ManagedDriver for GoLintDriver {
    fn config(&self, _req: ConfigRequest) -> anyhow::Result<ConfigResponse> {
        Ok(ConfigResponse {
            name: "go_lint".to_string(),
        })
    }

    fn schema(&self) -> hplugin::driver::DriverSchema {
        GoLintSpec::schema()
    }

    async fn parse(
        &self,
        req: ParseRequest,
        _ctoken: &(dyn Cancellable + Send + Sync),
    ) -> anyhow::Result<ParseResponse> {
        let pkg = req.target_spec.addr.package.clone();
        let pkg_str = pkg.as_str();
        let spec =
            GoLintSpec::from(req.target_spec.config.clone()).context("parse go_lint config")?;

        let mut inputs: Vec<Input> = Vec::new();
        let mut groups: Vec<&String> = spec.deps.keys().collect();
        groups.sort();
        for group in groups {
            let addrs = spec.deps.get(group).expect("group key from same map");
            // The govet binary is staged read-only (one tool, shared, hardlinked)
            // and **per-file**: without that, staging symlinks the whole subtree in
            // and records only its root *directory* in the list file, so
            // `single_staged_path` would hand a directory to exec (EACCES). Per-file
            // staging hardlinks each file and lists it, so the path we exec is the
            // binary itself.
            let read_only = group.as_str() == GOVET_TOOL_GROUP;
            let annotations = if read_only {
                BTreeMap::from([
                    (
                        hdriver_support::stage::READ_ONLY_ANNOTATION.to_string(),
                        "true".to_string(),
                    ),
                    (
                        hdriver_support::stage::STAGE_PER_FILE_ANNOTATION.to_string(),
                        "true".to_string(),
                    ),
                ])
            } else {
                BTreeMap::new()
            };
            for (i, addr_str) in addrs.iter().enumerate() {
                inputs.push(Input {
                    r#ref: TargetAddr::parse(addr_str, &pkg)
                        .with_context(|| format!("parse dep addr {addr_str}"))?,
                    mode: InputMode::Standard,
                    origin_id: format!("dep|{group}|{i}"),
                    annotations: annotations.clone(),
                    hashed: true,
                    runtime: true,
                });
            }
        }

        let def = GoLintDef {
            import_path: spec.import_path,
            goos: spec.goos,
            goarch: spec.goarch,
            go_version: spec.go_version,
            build_tags: spec.build_tags,
            goexperiment: spec.goexperiment,
            import_paths: spec.import_paths,
        };

        let outputs: Vec<Output> = spec
            .out
            .iter()
            .map(|(group, paths)| Output {
                group: group.clone(),
                paths: paths
                    .iter()
                    .map(|p| {
                        let full_path = if pkg_str.is_empty() {
                            p.clone()
                        } else {
                            format!("{pkg_str}/{p}")
                        };
                        TPath {
                            content: Content::FilePath(full_path),
                            codegen_tree: CodegenMode::None,
                            collect: true,
                        }
                    })
                    .collect(),
            })
            .collect();

        let hash = {
            let mut h = DebugHasher::new(Xxh3Default::new(), || {
                format!("go_lint_{}", req.target_spec.addr.format())
            });
            def.hash(&mut h);
            format!("{:x}", h.finish()).into_bytes()
        };

        Ok(ParseResponse {
            target_def: TargetDef {
                addr: req.target_spec.addr.clone(),
                labels: req.target_spec.labels.clone(),
                raw_def: Arc::new(def),
                inputs,
                outputs,
                support_files: vec![],
                cache: CacheConfig::on(true),
                pty: false,
                hash,
                transparent: false,
            },
        })
    }

    async fn apply_transitive(
        &self,
        req: ApplyTransitiveRequest,
        _ctoken: &(dyn Cancellable + Send + Sync),
    ) -> anyhow::Result<ApplyTransitiveResponse> {
        Ok(ApplyTransitiveResponse {
            target_def: req.target_def,
        })
    }

    async fn run<'a, 'io>(
        &self,
        req: ManagedRunRequest<'a, 'io>,
        ctoken: &(dyn Cancellable + Send + Sync),
    ) -> anyhow::Result<ManagedRunResponse> {
        let def = req.request.target.def_de::<GoLintDef>();
        let pkg_dir = &req.sandbox_pkg_dir;

        // The govet binary (single staged file in its group).
        let govet_bin = self
            .single_staged_path(&req, GOVET_TOOL_GROUP)
            .context("locate staged heph-govet binary (govet_tool dep not staged?)")?;

        // Map each transitive import to its staged archive (type info) and, when
        // present, its staged facts (interprocedural analysis input).
        let mut package_file: BTreeMap<String, String> = BTreeMap::new();
        let mut import_map: BTreeMap<String, String> = BTreeMap::new();
        let mut package_vetx: BTreeMap<String, String> = BTreeMap::new();
        for ip in &def.import_paths {
            let lib_group = crate::plugingo::addr_util::import_path_to_dep_group(ip);
            let archive = self
                .single_staged_path(&req, &lib_group)
                .with_context(|| format!("locate staged archive for lib {ip}"))?;
            package_file.insert(ip.clone(), archive);
            import_map.insert(ip.clone(), ip.clone());

            // Facts are optional: stdlib (or any not-yet-linted) deps have no
            // facts group. unitchecker treats a missing PackageVetx entry as
            // "no facts", which is correct — those analyzers degrade to
            // intra-package for that one dependency only.
            let facts_group = import_path_to_facts_group(ip);
            if let Ok(facts) = self.single_staged_path(&req, &facts_group) {
                // unitchecker gob-decodes whatever this points at, so a wrong file
                // surfaces as a cryptic "decoding facts: unexpected EOF". The dep
                // selects `|facts`, so the only staged file is the facts one — assert
                // it rather than trust it.
                anyhow::ensure!(
                    facts.ends_with(LINT_FACTS),
                    "staged facts for {ip} is {facts}, not a {LINT_FACTS} — the facts dep must \
                     select the analyze target's `facts` output group"
                );
                package_vetx.insert(ip.clone(), facts);
            }
        }

        // `unsafe` is a pseudo-package: it has no archive, so `go list` never reports
        // it as a lib and it has no `lib_*` dep group. unitchecker still resolves it
        // through ImportMap like any other import (the gc importer then returns
        // `types.Unsafe` without opening a file), so a package importing `unsafe`
        // fails with `can't resolve import ""` unless the map carries it.
        import_map.insert("unsafe".to_string(), "unsafe".to_string());

        let go_files = self.group_staged_paths(&req, "");
        let vetx_output = pkg_dir.join(LINT_FACTS);

        let cfg = UnitcheckerConfig {
            compiler: "gc".to_string(),
            dir: pkg_dir.to_string_lossy().into_owned(),
            import_path: def.import_path.clone(),
            go_version: format!("go{}", def.go_version),
            go_files,
            non_go_files: vec![],
            ignored_files: vec![],
            import_map,
            package_file,
            // We do not currently distinguish stdlib here; analyzers that special
            // -case the standard library will treat all deps as non-standard.
            standard: BTreeMap::new(),
            package_vetx,
            vetx_only: false,
            vetx_output: vetx_output.to_string_lossy().into_owned(),
            // A type-check failure is a real error for us — do not mask it.
            succeed_on_typecheck_failure: false,
        };

        let cfg_path = pkg_dir.join("unitchecker.cfg");
        std::fs::write(
            &cfg_path,
            serde_json::to_vec(&cfg).context("serialize unitchecker cfg")?,
        )
        .context("write unitchecker cfg")?;

        // `.golangci.yml` (if staged) selects which analyzers heph-govet runs.
        // It is a hashed input, so a config change re-keys this target and
        // re-lints. Passed by env because unitchecker rejects unknown flags.
        let mut env: HashMap<String, String> = HashMap::new();
        if let Ok(config_path) = self.single_staged_path(&req, "config") {
            env.insert("HEPH_GOVET_GOLANGCI_CONFIG".to_string(), config_path);
        }

        // `-json`: unitchecker writes facts to VetxOutput and prints diagnostics
        // as JSON to stdout, exiting 0 even when findings exist. We capture that
        // JSON as the report; the gate target decides pass/fail. This keeps facts
        // produced and cached regardless of findings.
        let report = self
            .exec_govet(
                std::path::Path::new(&govet_bin),
                vec![
                    OsString::from("-json"),
                    OsString::from(cfg_path.as_os_str()),
                ],
                &env,
                pkg_dir,
                ctoken,
            )
            .await?;
        // unitchecker reports absolute paths into *this* sandbox (the `posn`
        // strings and each suggested-fix `filename`). The gate that prints them
        // runs in a *different* sandbox where those paths no longer exist, so
        // rewrite them to workspace-root-relative here, at production time —
        // where the sandbox root is known and the report is cached. Basenames
        // are preserved, so the fixer's `report_edits` keying still holds.
        let report = relativize_report_paths(&report, &req.sandbox_ws_dir);
        std::fs::write(pkg_dir.join(LINT_REPORT), report).context("write lint report")?;

        if !vetx_output.exists() {
            anyhow::bail!(
                "go_lint: heph-govet did not produce facts at {vetx_output:?} (cfg or analyzer error)"
            );
        }

        Ok(ManagedRunResponse { artifacts: vec![] })
    }
}

impl GoLintDriver {
    /// All staged file paths for the inputs in dep `group` (origin `dep|group|*`).
    fn group_staged_paths(&self, req: &ManagedRunRequest<'_, '_>, group: &str) -> Vec<String> {
        let prefix = format!("dep|{group}|");
        let mut out: Vec<String> = Vec::new();
        for m in &req.inputs {
            if !m.input.origin_id.starts_with(&prefix) {
                continue;
            }
            let Ok(list_path) = m.require_list_path() else {
                continue;
            };
            if let Ok(f) = std::fs::File::open(list_path) {
                for line in std::io::BufReader::new(f).lines().map_while(Result::ok) {
                    if !line.is_empty() {
                        out.push(line);
                    }
                }
            }
        }
        out
    }

    /// The single staged path for a one-output group (lib archive, facts, tool).
    ///
    /// Rejects a directory: read-only staging lists only a subtree *root* unless the
    /// input opts into per-file staging, and handing that directory to `exec` fails
    /// as a bare `Permission denied` far from the cause. Fail with the reason here.
    fn single_staged_path(
        &self,
        req: &ManagedRunRequest<'_, '_>,
        group: &str,
    ) -> anyhow::Result<String> {
        let path = self
            .group_staged_paths(req, group)
            .into_iter()
            .next()
            .ok_or_else(|| anyhow::anyhow!("no staged file for dep group {group}"))?;
        anyhow::ensure!(
            !std::path::Path::new(&path).is_dir(),
            "staged path for dep group {group} is a directory ({path}), not a file — the input \
             must opt into per-file staging (STAGE_PER_FILE_ANNOTATION) for its files to be listed"
        );
        Ok(path)
    }

    /// Run `heph-govet`, returning captured stdout (the `-json` report). A
    /// non-zero exit means the tool itself failed (bad cfg, type-check error) —
    /// findings do NOT fail here, `-json` makes the tool exit 0 for those.
    async fn exec_govet(
        &self,
        govet_bin: &std::path::Path,
        args: Vec<OsString>,
        env: &HashMap<String, String>,
        cwd: &std::path::Path,
        ctoken: &(dyn Cancellable + Send + Sync),
    ) -> anyhow::Result<Vec<u8>> {
        let env_pairs: Vec<(OsString, OsString)> = env
            .iter()
            .map(|(k, v)| (OsString::from(k), OsString::from(v)))
            .collect();
        let spec = proc_exec::Spec {
            program: govet_bin.to_path_buf(),
            args,
            env: env_pairs,
            cwd: cwd.to_path_buf(),
            stdin: proc_exec::StdioSpec::Null,
            stdout: proc_exec::StdioSpec::Piped,
            stderr: proc_exec::StdioSpec::Piped,
            setsid: false,
            ctty: false,
        };
        let output = proc_exec::output(spec, ctoken)
            .await
            .context("wait for heph-govet")?;
        if !output.status.success() {
            let stderr = String::from_utf8_lossy(&output.stderr);
            let stdout = String::from_utf8_lossy(&output.stdout);
            anyhow::bail!(
                "heph-govet failed ({}):\nstderr:\n{}\nstdout:\n{}",
                output.status,
                hplugin::error::last_n_lines(stderr.trim(), 20),
                hplugin::error::last_n_lines(stdout.trim(), 20),
            );
        }
        Ok(output.stdout)
    }
}

// ---------------------------------------------------------------------------
// Gate driver: fails the build when a package's lint report has findings.
//
// `go_lint` (the analyze target, `_lint-analyze`) always exits 0 so facts are produced
// and cached even for a package with findings — otherwise dependents could not
// build their own facts. `go_lint_gate` (the user-facing `lint` target) consumes
// the analyze target's `report` output and is the thing that actually fails:
// cheap, cache-keyed on the report bytes, separate from fact production.
// ---------------------------------------------------------------------------

pub struct GoLintGateDriver;

impl GoLintGateDriver {
    pub fn new() -> Self {
        Self
    }
}

impl Default for GoLintGateDriver {
    fn default() -> Self {
        Self::new()
    }
}

#[derive(Spec)]
struct GoLintGateSpec {
    /// Dependencies, grouped by name → list of target addresses. The `report`
    /// group carries the analyze target's `lint-report.json` output.
    deps: HashMap<String, Vec<String>>,
}

#[derive(Clone, serde::Serialize, serde::Deserialize)]
struct GoLintGateDef;

const GO_LINT_GATE_FORMAT_VERSION: u32 = 1;

/// Rewrite every absolute sandbox path in a `unitchecker -json` report to be
/// relative to the sandbox workspace root (`ws_root`), leaving the rest of the
/// JSON untouched. Two path-bearing fields are rewritten:
///
///   - each diagnostic's `posn` (`"<file>:<line>:<col>"`), printed by the gate;
///   - each suggested fix edit's `filename`, consumed by the fixer.
///
/// This runs in the `_lint-analyze` sandbox, the only place the absolute paths are valid
/// and the workspace root is known — the gate and fixer that consume the report
/// run in different sandboxes. A path not under `ws_root` (there should be none)
/// is left as-is. On any JSON parse error the original bytes are returned
/// unchanged, so a malformed report surfaces at the consumer rather than here.
fn relativize_report_paths(json: &[u8], ws_root: &std::path::Path) -> Vec<u8> {
    let mut prefix = ws_root.to_string_lossy().into_owned();
    if !prefix.ends_with('/') {
        prefix.push('/');
    }
    let strip = |s: &str| -> Option<String> { s.strip_prefix(&prefix).map(str::to_string) };

    let Ok(mut root) = serde_json::from_slice::<serde_json::Value>(json) else {
        return json.to_vec();
    };
    if let Some(by_pkg) = root.as_object_mut() {
        for by_analyzer in by_pkg.values_mut() {
            let Some(by_analyzer) = by_analyzer.as_object_mut() else {
                continue;
            };
            for diags in by_analyzer.values_mut() {
                let Some(diags) = diags.as_array_mut() else {
                    continue;
                };
                for d in diags {
                    // `posn` = "<file>:<line>:<col>"; only the file part is a path.
                    if let Some(posn) = d.get("posn").and_then(|v| v.as_str())
                        && let Some(rel) = strip(posn)
                    {
                        d["posn"] = serde_json::Value::String(rel);
                    }
                    let Some(fixes) = d.get_mut("suggested_fixes").and_then(|v| v.as_array_mut())
                    else {
                        continue;
                    };
                    for fix in fixes {
                        let Some(edits) = fix.get_mut("edits").and_then(|v| v.as_array_mut())
                        else {
                            continue;
                        };
                        for e in edits {
                            if let Some(fname) = e.get("filename").and_then(|v| v.as_str())
                                && let Some(rel) = strip(fname)
                            {
                                e["filename"] = serde_json::Value::String(rel);
                            }
                        }
                    }
                }
            }
        }
    }
    serde_json::to_vec(&root).unwrap_or_else(|_| json.to_vec())
}

/// The golangci-lint linter NAME that owns an analyzer, so a finding prints the
/// name a user would put in a `//nolint:` directive. golangci v2 folded gosimple
/// and stylecheck into `staticcheck`, so every honnef check (SA/S/ST — the codes
/// all start with an uppercase `S`) reports as `staticcheck`. Everything else is
/// a `go vet` pass (`printf`, `lostcancel`, … — lowercase names), exposed as
/// `govet`. Mirrors heph-govet's own analyzer→linter map (`nolintLinterName`).
fn golangci_linter_of(analyzer: &str) -> &str {
    if analyzer.starts_with('S') {
        "staticcheck"
    } else {
        "govet"
    }
}

/// Parse a `unitchecker -json` report into a flat list of human-readable
/// findings. The report shape is `{ "import/path": { "analyzer": [ {"posn":…,
/// "message":…}, … ] } }`; an empty object (`{}`) means no findings. Each
/// finding names the golangci linter that produced it and the underlying check.
fn report_findings(json: &[u8]) -> anyhow::Result<Vec<String>> {
    if json.iter().all(u8::is_ascii_whitespace) {
        return Ok(Vec::new());
    }
    let root: serde_json::Value =
        serde_json::from_slice(json).context("parse unitchecker json report")?;
    let Some(by_pkg) = root.as_object() else {
        return Ok(Vec::new());
    };
    let mut out = Vec::new();
    for (pkg, by_analyzer) in by_pkg {
        let Some(by_analyzer) = by_analyzer.as_object() else {
            continue;
        };
        for (analyzer, diags) in by_analyzer {
            let Some(diags) = diags.as_array() else {
                continue;
            };
            for d in diags {
                let posn = d.get("posn").and_then(|v| v.as_str()).unwrap_or("");
                let message = d.get("message").and_then(|v| v.as_str()).unwrap_or("");
                let linter = golangci_linter_of(analyzer);
                out.push(format!("{posn}: {message} ({linter}: {analyzer}) [{pkg}]"));
            }
        }
    }
    Ok(out)
}

#[async_trait]
impl ManagedDriver for GoLintGateDriver {
    fn config(&self, _req: ConfigRequest) -> anyhow::Result<ConfigResponse> {
        Ok(ConfigResponse {
            name: "go_lint_gate".to_string(),
        })
    }

    fn schema(&self) -> hplugin::driver::DriverSchema {
        GoLintGateSpec::schema()
    }

    async fn parse(
        &self,
        req: ParseRequest,
        _ctoken: &(dyn Cancellable + Send + Sync),
    ) -> anyhow::Result<ParseResponse> {
        let pkg = req.target_spec.addr.package.clone();
        let spec =
            GoLintGateSpec::from(req.target_spec.config.clone()).context("parse go_lint_gate")?;

        let mut inputs: Vec<Input> = Vec::new();
        let mut groups: Vec<&String> = spec.deps.keys().collect();
        groups.sort();
        for group in groups {
            for (i, addr_str) in spec.deps.get(group).expect("group key").iter().enumerate() {
                inputs.push(Input {
                    r#ref: TargetAddr::parse(addr_str, &pkg)
                        .with_context(|| format!("parse dep addr {addr_str}"))?,
                    mode: InputMode::Standard,
                    origin_id: format!("dep|{group}|{i}"),
                    annotations: BTreeMap::new(),
                    hashed: true,
                    // The golangci config is a hash-only input: it re-keys the
                    // target on any `.golangci.yml` change without staging the
                    // file (this target never reads it — it only consumes the
                    // analyze report). Every other dep is staged as usual.
                    runtime: group.as_str() != "config",
                });
            }
        }

        let hash = {
            let mut h = DebugHasher::new(Xxh3Default::new(), || {
                format!("go_lint_gate_{}", req.target_spec.addr.format())
            });
            GO_LINT_GATE_FORMAT_VERSION.hash(&mut h);
            format!("{:x}", h.finish()).into_bytes()
        };

        Ok(ParseResponse {
            target_def: TargetDef {
                addr: req.target_spec.addr.clone(),
                labels: req.target_spec.labels.clone(),
                raw_def: Arc::new(GoLintGateDef),
                inputs,
                outputs: vec![],
                support_files: vec![],
                cache: CacheConfig::on(true),
                pty: false,
                hash,
                transparent: false,
            },
        })
    }

    async fn apply_transitive(
        &self,
        req: ApplyTransitiveRequest,
        _ctoken: &(dyn Cancellable + Send + Sync),
    ) -> anyhow::Result<ApplyTransitiveResponse> {
        Ok(ApplyTransitiveResponse {
            target_def: req.target_def,
        })
    }

    async fn run<'a, 'io>(
        &self,
        req: ManagedRunRequest<'a, 'io>,
        _ctoken: &(dyn Cancellable + Send + Sync),
    ) -> anyhow::Result<ManagedRunResponse> {
        // Single staged report file (origin `dep|report|*`).
        let mut report_path: Option<String> = None;
        for m in &req.inputs {
            if !m.input.origin_id.starts_with("dep|report|") {
                continue;
            }
            if let Ok(list_path) = m.require_list_path()
                && let Ok(f) = std::fs::File::open(list_path)
            {
                for line in std::io::BufReader::new(f).lines().map_while(Result::ok) {
                    if !line.is_empty() {
                        report_path = Some(line);
                        break;
                    }
                }
            }
        }
        let report_path =
            report_path.ok_or_else(|| anyhow::anyhow!("go_lint_gate: no lint report staged"))?;
        let bytes = std::fs::read(&report_path)
            .with_context(|| format!("read lint report {report_path}"))?;
        let findings = report_findings(&bytes)?;
        if !findings.is_empty() {
            anyhow::bail!(
                "lint found {} issue(s):\n{}",
                findings.len(),
                findings.join("\n")
            );
        }
        Ok(ManagedRunResponse { artifacts: vec![] })
    }
}

// ---------------------------------------------------------------------------
// Fix driver: applies go/analysis suggested fixes back into source (codegen).
//
// `_lint-analyze`'s `-json` report already carries each diagnostic's `suggested_fixes`
// (byte-offset text edits). `go_lint_fix` (the user-facing `lint` target)
// consumes that report plus the package's own `.go` sources, applies the edits,
// and declares the rewritten sources as `codegen=in_place` outputs — so the
// engine writes them back over the tracked source files. Purely mechanical: no
// re-analysis, and it reuses `_lint-analyze`'s cache.
// ---------------------------------------------------------------------------

/// A single suggested-fix text edit: replace bytes `[start, end)` of `file`
/// (basename) with `new`. `start`/`end` are 0-based byte offsets into the file
/// as the analyzer parsed it; `_lint-analyze` and `lint` stage byte-identical
/// sources, so the offsets line up.
struct FixEdit {
    start: usize,
    end: usize,
    new: String,
}

/// Parse a `unitchecker -json` report into edits grouped by source-file
/// basename. Only the FIRST suggested fix of each diagnostic is taken — extra
/// fixes are alternatives, not additional edits (the go/analysis convention an
/// auto-fixer follows). Diagnostics without a suggested fix contribute nothing.
///
/// Files are keyed by basename because the report's `filename` is a
/// sandbox-relative path (see [`relativize_report_paths`]); a package's Go files
/// are flat (one directory), so basenames are unique within it.
fn report_edits(json: &[u8]) -> anyhow::Result<HashMap<String, Vec<FixEdit>>> {
    let mut out: HashMap<String, Vec<FixEdit>> = HashMap::new();
    if json.iter().all(u8::is_ascii_whitespace) {
        return Ok(out);
    }
    let root: serde_json::Value =
        serde_json::from_slice(json).context("parse unitchecker json report")?;
    let Some(by_pkg) = root.as_object() else {
        return Ok(out);
    };
    for by_analyzer in by_pkg.values() {
        let Some(by_analyzer) = by_analyzer.as_object() else {
            continue;
        };
        for diags in by_analyzer.values() {
            let Some(diags) = diags.as_array() else {
                continue;
            };
            for d in diags {
                let Some(first) = d
                    .get("suggested_fixes")
                    .and_then(|v| v.as_array())
                    .and_then(|f| f.first())
                else {
                    continue;
                };
                let Some(edits) = first.get("edits").and_then(|v| v.as_array()) else {
                    continue;
                };
                for e in edits {
                    let filename = e.get("filename").and_then(|v| v.as_str()).unwrap_or("");
                    let new = e.get("new").and_then(|v| v.as_str()).unwrap_or("");
                    let (Some(start), Some(end)) = (
                        e.get("start")
                            .and_then(serde_json::Value::as_u64)
                            .and_then(|v| usize::try_from(v).ok()),
                        e.get("end")
                            .and_then(serde_json::Value::as_u64)
                            .and_then(|v| usize::try_from(v).ok()),
                    ) else {
                        continue;
                    };
                    if filename.is_empty() || end < start {
                        continue;
                    }
                    let base = std::path::Path::new(filename).file_name().map_or_else(
                        || filename.to_string(),
                        |s| s.to_string_lossy().into_owned(),
                    );
                    out.entry(base).or_default().push(FixEdit {
                        start,
                        end,
                        new: new.to_string(),
                    });
                }
            }
        }
    }
    Ok(out)
}

/// Apply `edits` to `src`, returning the rewritten bytes, or `None` when nothing
/// applies. Edits are sorted by start offset; any that fall out of range or
/// overlap an already-accepted edit are dropped (keeping the earliest — the same
/// conflict rule go/analysis' own fix applier uses). The accepted, non-
/// overlapping edits are then spliced in a single left-to-right pass.
fn apply_edits(src: &[u8], edits: &mut [FixEdit]) -> Option<Vec<u8>> {
    if edits.is_empty() {
        return None;
    }
    edits.sort_by(|a, b| a.start.cmp(&b.start).then(a.end.cmp(&b.end)));
    let mut accepted: Vec<&FixEdit> = Vec::with_capacity(edits.len());
    let mut last_end = 0usize;
    for e in edits.iter() {
        if e.start > e.end || e.end > src.len() {
            continue;
        }
        // Overlaps the previously accepted edit → drop (earliest wins).
        if !accepted.is_empty() && e.start < last_end {
            continue;
        }
        accepted.push(e);
        last_end = e.end;
    }
    if accepted.is_empty() {
        return None;
    }
    let mut out = Vec::with_capacity(src.len());
    let mut cursor = 0usize;
    for e in accepted {
        out.extend_from_slice(src.get(cursor..e.start).unwrap_or_default());
        out.extend_from_slice(e.new.as_bytes());
        cursor = e.end;
    }
    out.extend_from_slice(src.get(cursor..).unwrap_or_default());
    Some(out)
}

/// All staged file paths for the inputs in dep `group` (origin `dep|group|*`).
/// Free-function form used by the fix driver (mirrors [`GoLintDriver`]'s method).
pub(crate) fn staged_paths_in_group(req: &ManagedRunRequest<'_, '_>, group: &str) -> Vec<String> {
    let prefix = format!("dep|{group}|");
    let mut out: Vec<String> = Vec::new();
    for m in &req.inputs {
        if !m.input.origin_id.starts_with(&prefix) {
            continue;
        }
        let Ok(list_path) = m.require_list_path() else {
            continue;
        };
        if let Ok(f) = std::fs::File::open(list_path) {
            for line in std::io::BufReader::new(f).lines().map_while(Result::ok) {
                if !line.is_empty() {
                    out.push(line);
                }
            }
        }
    }
    out
}

pub struct GoLintFixDriver;

impl GoLintFixDriver {
    pub fn new() -> Self {
        Self
    }
}

impl Default for GoLintFixDriver {
    fn default() -> Self {
        Self::new()
    }
}

#[derive(Spec)]
struct GoLintFixSpec {
    /// Dependencies, grouped by name → list of target addresses. The `report`
    /// group carries the analyze target's `lint-report.json`; the default (`""`)
    /// group the package `.go` sources rewritten in place.
    deps: HashMap<String, Vec<String>>,
    /// Declared outputs, grouped by name → list of package-relative paths (the
    /// `.go` files, written back in place).
    out: HashMap<String, Vec<String>>,
}

#[derive(Clone, serde::Serialize, serde::Deserialize)]
struct GoLintFixDef;

const GO_LINT_FIX_FORMAT_VERSION: u32 = 1;

#[async_trait]
impl ManagedDriver for GoLintFixDriver {
    fn config(&self, _req: ConfigRequest) -> anyhow::Result<ConfigResponse> {
        Ok(ConfigResponse {
            name: "go_lint_fix".to_string(),
        })
    }

    fn schema(&self) -> hplugin::driver::DriverSchema {
        GoLintFixSpec::schema()
    }

    async fn parse(
        &self,
        req: ParseRequest,
        _ctoken: &(dyn Cancellable + Send + Sync),
    ) -> anyhow::Result<ParseResponse> {
        let pkg = req.target_spec.addr.package.clone();
        let pkg_str = pkg.as_str();
        let spec =
            GoLintFixSpec::from(req.target_spec.config.clone()).context("parse go_lint_fix")?;

        let mut inputs: Vec<Input> = Vec::new();
        let mut groups: Vec<&String> = spec.deps.keys().collect();
        groups.sort();
        for group in groups {
            for (i, addr_str) in spec.deps.get(group).expect("group key").iter().enumerate() {
                inputs.push(Input {
                    r#ref: TargetAddr::parse(addr_str, &pkg)
                        .with_context(|| format!("parse dep addr {addr_str}"))?,
                    mode: InputMode::Standard,
                    origin_id: format!("dep|{group}|{i}"),
                    annotations: BTreeMap::new(),
                    hashed: true,
                    // The golangci config is a hash-only input: it re-keys the
                    // target on any `.golangci.yml` change without staging the
                    // file (this target never reads it — it only consumes the
                    // analyze report). Every other dep is staged as usual.
                    runtime: group.as_str() != "config",
                });
            }
        }

        // The rewritten `.go` files are `codegen=in_place` outputs: the engine
        // writes them back over the tracked source files after a top-level run.
        let outputs: Vec<Output> = spec
            .out
            .iter()
            .map(|(group, paths)| Output {
                group: group.clone(),
                paths: paths
                    .iter()
                    .map(|p| {
                        let full_path = if pkg_str.is_empty() {
                            p.clone()
                        } else {
                            format!("{pkg_str}/{p}")
                        };
                        TPath {
                            content: Content::FilePath(full_path),
                            codegen_tree: CodegenMode::InPlace,
                            collect: true,
                        }
                    })
                    .collect(),
            })
            .collect();

        let hash = {
            let mut h = DebugHasher::new(Xxh3Default::new(), || {
                format!("go_lint_fix_{}", req.target_spec.addr.format())
            });
            GO_LINT_FIX_FORMAT_VERSION.hash(&mut h);
            format!("{:x}", h.finish()).into_bytes()
        };

        Ok(ParseResponse {
            target_def: TargetDef {
                addr: req.target_spec.addr.clone(),
                labels: req.target_spec.labels.clone(),
                raw_def: Arc::new(GoLintFixDef),
                inputs,
                outputs,
                support_files: vec![],
                cache: CacheConfig::on(true),
                pty: false,
                hash,
                transparent: false,
            },
        })
    }

    async fn apply_transitive(
        &self,
        req: ApplyTransitiveRequest,
        _ctoken: &(dyn Cancellable + Send + Sync),
    ) -> anyhow::Result<ApplyTransitiveResponse> {
        Ok(ApplyTransitiveResponse {
            target_def: req.target_def,
        })
    }

    async fn run<'a, 'io>(
        &self,
        req: ManagedRunRequest<'a, 'io>,
        _ctoken: &(dyn Cancellable + Send + Sync),
    ) -> anyhow::Result<ManagedRunResponse> {
        // The analyze target's `-json` report (single staged file, dep|report|*).
        let report_path = staged_paths_in_group(&req, "report")
            .into_iter()
            .next()
            .ok_or_else(|| anyhow::anyhow!("go_lint_fix: no lint report staged"))?;
        let report = std::fs::read(&report_path)
            .with_context(|| format!("read lint report {report_path}"))?;
        let mut edits_by_file = report_edits(&report)?;

        // Apply the edits to each staged source, rewriting it in place. The
        // default (`""`) group is staged as a plain writable copy (not read-only,
        // so not hardlinked to a cache blob), so an in-place overwrite is safe.
        for src in staged_paths_in_group(&req, "") {
            let base = std::path::Path::new(&src)
                .file_name()
                .map(|s| s.to_string_lossy().into_owned());
            let Some(mut edits) = base.and_then(|b| edits_by_file.remove(&b)) else {
                continue;
            };
            let orig = std::fs::read(&src).with_context(|| format!("read source for fix {src}"))?;
            if let Some(fixed) = apply_edits(&orig, &mut edits)
                && fixed != orig
            {
                std::fs::write(&src, &fixed)
                    .with_context(|| format!("write fixed source {src}"))?;
            }
        }

        Ok(ManagedRunResponse { artifacts: vec![] })
    }
}

// ---------------------------------------------------------------------------
// Provider-facing spec builder
// ---------------------------------------------------------------------------

use crate::plugingo::addr_util::import_path_to_dep_group;
use crate::plugingo::factors::Factors;
use hcore::htvalue::Value;
use hmodel::htaddr::Addr;
use hplugin::provider::TargetSpec;

/// Parameters for [`build_lint_spec`].
pub struct LintParams<'a> {
    pub addr: Addr,
    /// Import path of the package under analysis.
    pub import_path: &'a str,
    pub factors: &'a Factors,
    pub go_version: &'a str,
    /// `(import_path, build_lib archive addr)` — `lib_*` dep groups + cfg
    /// PackageFile entries (type info for every transitive dependency).
    pub transitive_libs: &'a [(String, Addr)],
    /// `(import_path, lint addr)` — `facts_*` dep groups; the deps whose facts
    /// feed interprocedural analysis. Subset of `transitive_libs` (e.g. omit
    /// stdlib until it is linted too).
    pub facts_libs: &'a [(String, Addr)],
    /// Compile sources (`.go`) → the default (`""`) dep group.
    pub src_addrs: &'a [String],
    /// `build` addr of the `heph-govet` unitchecker binary.
    pub govet_addr: &'a Addr,
    /// `.golangci.yml` file addr → `config` dep group, passed to heph-govet via
    /// `HEPH_GOVET_GOLANGCI_CONFIG`. `None` → the standard analyzer set.
    pub config_addr: Option<&'a Addr>,
}

/// Build a `go_lint` target spec.
pub fn build_lint_spec(p: LintParams) -> TargetSpec {
    let str_one = |a: &Addr| Value::List(vec![Value::String(a.format())]);

    let mut deps: BTreeMap<String, Value> = p
        .transitive_libs
        .iter()
        .map(|(import_path, dep_addr)| (import_path_to_dep_group(import_path), str_one(dep_addr)))
        .collect();
    for (import_path, lint_addr) in p.facts_libs {
        // `|facts` selects the analyze target's facts output ONLY. Without it the
        // whole `_lint-analyze` target stages — facts *and* `lint-report.json` — and the
        // consumer, which takes the single staged path of the group, gets whichever
        // sorts first: `lint-report.json` (`-` < `.`). unitchecker then gob-decodes
        // the JSON report as facts ("unexpected EOF"). The gate is explicit the same
        // way (`|report`).
        deps.insert(
            import_path_to_facts_group(import_path),
            Value::List(vec![Value::String(format!("{}|facts", lint_addr.format()))]),
        );
    }
    deps.insert(
        String::new(),
        Value::List(p.src_addrs.iter().cloned().map(Value::String).collect()),
    );
    deps.insert(GOVET_TOOL_GROUP.to_string(), str_one(p.govet_addr));
    if let Some(cfg) = p.config_addr {
        deps.insert("config".to_string(), str_one(cfg));
    }

    // Sorted for an order-independent cache key (see GoLintDef::hash).
    let mut import_paths: Vec<String> =
        p.transitive_libs.iter().map(|(ip, _)| ip.clone()).collect();
    import_paths.sort();
    let import_paths: Vec<Value> = import_paths.into_iter().map(Value::String).collect();

    let mut config: HashMap<String, Value> = HashMap::new();
    config.insert(
        "import_path".to_string(),
        Value::String(p.import_path.to_string()),
    );
    config.insert("goos".to_string(), Value::String(p.factors.goos.clone()));
    config.insert(
        "goarch".to_string(),
        Value::String(p.factors.goarch.clone()),
    );
    config.insert(
        "go_version".to_string(),
        Value::String(p.go_version.to_string()),
    );
    if !p.factors.build_tags.is_empty() {
        config.insert(
            "build_tags".to_string(),
            Value::List(
                p.factors
                    .build_tags
                    .iter()
                    .map(|t| Value::String(t.clone()))
                    .collect(),
            ),
        );
    }
    if !p.factors.goexperiment.is_empty() {
        config.insert(
            "goexperiment".to_string(),
            Value::List(
                p.factors
                    .goexperiment
                    .iter()
                    .map(|t| Value::String(t.clone()))
                    .collect(),
            ),
        );
    }
    config.insert("import_paths".to_string(), Value::List(import_paths));
    config.insert("deps".to_string(), Value::Map(deps.into_iter().collect()));
    config.insert(
        "out".to_string(),
        Value::Map(HashMap::from([
            (
                "facts".to_string(),
                Value::List(vec![Value::String(LINT_FACTS.to_string())]),
            ),
            (
                "report".to_string(),
                Value::List(vec![Value::String(LINT_REPORT.to_string())]),
            ),
        ])),
    );

    TargetSpec {
        addr: p.addr,
        driver: "go_lint".to_string(),
        config,
        // No labels: `_lint-analyze` is the analyze unit `lint` / `lint-check` consume, not
        // a target anyone selects. Labels are the selection surface, so it has none
        // — it is reached only as a dep.
        labels: vec![],
        transitive: Default::default(),
        approval: Default::default(),
    }
}

/// Build the user-facing `lint` gate spec. Depends on the `report` output of the
/// analyze target (`_lint-analyze`) and fails the build when it contains findings.
///
/// `config_addr` (the module's `.golangci.yml`) is attached as a hash-only dep
/// so any config change re-keys the gate directly — not just transitively
/// through `_lint-analyze`'s report.
pub fn build_lint_gate_spec(
    addr: Addr,
    analyze_addr: &Addr,
    config_addr: Option<&Addr>,
) -> TargetSpec {
    let mut deps = BTreeMap::from([(
        "report".to_string(),
        Value::List(vec![Value::String(format!(
            "{}|report",
            analyze_addr.format()
        ))]),
    )]);
    if let Some(cfg) = config_addr {
        deps.insert(
            "config".to_string(),
            Value::List(vec![Value::String(cfg.format())]),
        );
    }
    let mut config: HashMap<String, Value> = HashMap::new();
    config.insert("deps".to_string(), Value::Map(deps.into_iter().collect()));

    TargetSpec {
        addr,
        driver: "go_lint_gate".to_string(),
        config,
        // The read-only checker (`lint-check`): `go-lint-check` selects it among go
        // targets, `lint-check` selects every language's checker at once
        // (`--label lint-check //...`). The plain `lint` label belongs to the fixer.
        labels: vec!["go-lint-check".to_string(), "lint-check".to_string()],
        transitive: Default::default(),
        approval: Default::default(),
    }
}

/// Build the user-facing `lint` (fixer) spec. Depends on the `report` output of the
/// analyze target (`_lint-analyze`) plus the package's own `.go` sources, applies each
/// diagnostic's suggested fix, and rewrites the sources in place (codegen).
///
/// `src_addrs` are the source file target addresses (the `""` dep group, staged
/// writable and rewritten); `go_files` are their basenames (the declared
/// `in_place` outputs). The two are the same files viewed as addr vs. filename.
pub fn build_lint_fix_spec(
    addr: Addr,
    analyze_addr: &Addr,
    src_addrs: &[String],
    go_files: &[String],
    config_addr: Option<&Addr>,
) -> TargetSpec {
    let mut deps = BTreeMap::from([
        (
            "report".to_string(),
            Value::List(vec![Value::String(format!(
                "{}|report",
                analyze_addr.format()
            ))]),
        ),
        (
            String::new(),
            Value::List(src_addrs.iter().cloned().map(Value::String).collect()),
        ),
    ]);
    // Hash-only dep: a `.golangci.yml` change re-keys the fixer directly.
    if let Some(cfg) = config_addr {
        deps.insert(
            "config".to_string(),
            Value::List(vec![Value::String(cfg.format())]),
        );
    }

    let mut config: HashMap<String, Value> = HashMap::new();
    config.insert("deps".to_string(), Value::Map(deps.into_iter().collect()));
    config.insert(
        "out".to_string(),
        Value::Map(HashMap::from([(
            "src".to_string(),
            Value::List(go_files.iter().cloned().map(Value::String).collect()),
        )])),
    );

    TargetSpec {
        addr,
        driver: "go_lint_fix".to_string(),
        config,
        // The plain `lint` target is the FIXER, so it owns the plain labels:
        // `go-lint` (this language's) and `lint` (every language's), plus `fix` for
        // a fixers-only sweep. Checking without rewriting is `lint-check`.
        labels: vec!["go-lint".to_string(), "lint".to_string(), "fix".to_string()],
        transitive: Default::default(),
        approval: Default::default(),
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use hmodel::htpkg::PkgBuf;

    const V: &str = crate::plugingo::toolchain::DEFAULT_GO_VERSION;

    fn factors() -> Factors {
        Factors {
            goos: "linux".into(),
            goarch: "amd64".into(),
            build_tags: vec![],
            ..Default::default()
        }
    }

    fn addr(name: &str) -> Addr {
        Addr::new(PkgBuf::from("mylib"), name.to_string(), Default::default())
    }

    fn govet() -> Addr {
        Addr::new(
            PkgBuf::from("tools/heph-govet"),
            "build".to_string(),
            Default::default(),
        )
    }

    fn lib(ip: &str, name: &str) -> (String, Addr) {
        (
            ip.to_string(),
            Addr::new(PkgBuf::from("dep"), name.to_string(), Default::default()),
        )
    }

    fn spec(libs: &[(String, Addr)], facts: &[(String, Addr)]) -> TargetSpec {
        spec_cfg(libs, facts, None)
    }

    fn spec_cfg(
        libs: &[(String, Addr)],
        facts: &[(String, Addr)],
        config_addr: Option<&Addr>,
    ) -> TargetSpec {
        let g = govet();
        build_lint_spec(LintParams {
            addr: addr("lint"),
            import_path: "example.com/mylib",
            factors: &factors(),
            go_version: V,
            transitive_libs: libs,
            facts_libs: facts,
            src_addrs: &["//mylib:a.go".to_string()],
            govet_addr: &g,
            config_addr,
        })
    }

    fn deps_map(s: &TargetSpec) -> HashMap<String, Vec<String>> {
        match s.config.get("deps").unwrap() {
            Value::Map(m) => m
                .iter()
                .map(|(k, v)| {
                    let list = match v {
                        Value::List(l) => l
                            .iter()
                            .map(|x| match x {
                                Value::String(s) => s.clone(),
                                _ => panic!("dep entry not a string"),
                            })
                            .collect(),
                        _ => panic!("dep group not a list"),
                    };
                    (k.clone(), list)
                })
                .collect(),
            _ => panic!("deps not a map"),
        }
    }

    #[test]
    fn driver_is_go_lint() {
        assert_eq!(spec(&[], &[]).driver, "go_lint");
    }

    #[test]
    fn sources_in_default_group() {
        assert_eq!(
            deps_map(&spec(&[], &[])).get("").unwrap(),
            &vec!["//mylib:a.go".to_string()]
        );
    }

    #[test]
    fn govet_tool_group_present() {
        assert!(deps_map(&spec(&[], &[])).contains_key(GOVET_TOOL_GROUP));
    }

    #[test]
    fn lib_group_for_each_transitive_archive() {
        let l = lib("fmt", "fmt");
        let s = spec(std::slice::from_ref(&l), &[]);
        assert!(deps_map(&s).contains_key("lib_fmt"));
    }

    // A dep that is itself linted contributes a facts_* group; a dep that is not
    // (e.g. stdlib) contributes only its lib_* archive — facts are optional.
    #[test]
    fn facts_group_only_for_facts_libs() {
        let archive = lib("example.com/dep", "build_lib");
        let factsdep = (
            "example.com/dep".to_string(),
            Addr::new(PkgBuf::from("dep"), "lint".to_string(), Default::default()),
        );
        let s = spec(
            std::slice::from_ref(&archive),
            std::slice::from_ref(&factsdep),
        );
        let m = deps_map(&s);
        assert!(m.contains_key("lib_example_com_dep"), "archive group");
        assert!(m.contains_key("facts_example_com_dep"), "facts group");
    }

    /// A facts dep must select the analyze target's `facts` output group. Staging the
    /// whole `_lint-analyze` target would also stage `lint-report.json`, which sorts *before*
    /// `lint.facts` (`-` < `.`), so the consumer — which takes the single staged path
    /// of the group — would hand the JSON report to unitchecker as gob facts and fail
    /// with "unexpected EOF".
    #[test]
    fn facts_deps_select_the_facts_output_group() {
        let factsdep = (
            "example.com/dep".to_string(),
            Addr::new(
                PkgBuf::from("dep"),
                "_lint-analyze".to_string(),
                Default::default(),
            ),
        );
        let s = spec(&[], std::slice::from_ref(&factsdep));
        let m = deps_map(&s);
        let facts = m
            .get("facts_example_com_dep")
            .and_then(|v| v.first())
            .expect("one facts dep");
        assert!(
            facts.ends_with("|facts"),
            "facts dep must select the facts output, else the report stages too: {facts}"
        );
    }

    #[test]
    fn no_facts_group_when_dep_not_linted() {
        let archive = lib("fmt", "build_lib");
        let s = spec(std::slice::from_ref(&archive), &[]);
        assert!(!deps_map(&s).contains_key("facts_fmt"));
    }

    #[test]
    fn declares_facts_and_report_outputs() {
        let s = spec(&[], &[]);
        let out = match s.config.get("out").unwrap() {
            Value::Map(m) => m,
            _ => panic!("out not a map"),
        };
        assert!(out.contains_key("facts"));
        assert!(out.contains_key("report"));
    }

    /// `_lint-analyze` is the analyze unit `lint`/`lint-check` consume, not something anyone
    /// selects: no labels at all, so no label sweep can reach it.
    #[test]
    fn analyze_unit_has_no_labels() {
        assert!(spec(&[], &[]).labels.is_empty());
    }

    /// `lint` fixes and `lint-check` only reports, and the labels say so: the fixer
    /// owns the plain `go-lint`/`lint` labels (plus `fix`), the checker owns
    /// `go-lint-check`/`lint-check`. So `--label lint-check` can never rewrite source.
    #[test]
    fn check_and_fix_labels_separate_checking_from_fixing() {
        let analyze = Addr::new(
            PkgBuf::from("mylib"),
            "_lint-analyze".to_string(),
            Default::default(),
        );
        let check = build_lint_gate_spec(addr("lint-check"), &analyze, None);
        assert_eq!(check.labels, vec!["go-lint-check", "lint-check"]);

        let fix = build_lint_fix_spec(
            addr("lint"),
            &analyze,
            &["//mylib:a.go".to_string()],
            &["a.go".to_string()],
            None,
        );
        assert_eq!(fix.labels, vec!["go-lint", "lint", "fix"]);
        assert!(
            !check.labels.contains(&"fix".to_string()),
            "a `--label fix` sweep must not pick up the read-only checker"
        );
    }

    #[test]
    fn config_group_present_only_when_config_addr_given() {
        assert!(!deps_map(&spec(&[], &[])).contains_key("config"));
        let cfg = Addr::new(
            PkgBuf::from(""),
            ".golangci.yml".to_string(),
            Default::default(),
        );
        let s = spec_cfg(&[], &[], Some(&cfg));
        assert!(deps_map(&s).contains_key("config"));
    }

    #[test]
    fn import_path_in_config() {
        match spec(&[], &[]).config.get("import_path").unwrap() {
            Value::String(s) => assert_eq!(s, "example.com/mylib"),
            _ => panic!("import_path not a string"),
        }
    }

    // ---- gate ----

    #[test]
    fn gate_empty_report_has_no_findings() {
        assert!(report_findings(b"{}").unwrap().is_empty());
        assert!(report_findings(b"   \n ").unwrap().is_empty());
        assert!(report_findings(b"").unwrap().is_empty());
    }

    #[test]
    fn gate_extracts_findings_with_posn_and_message() {
        let json = br#"{
            "example.com/mylib": {
                "printf": [
                    {"posn": "a.go:10:2", "message": "Printf format %d has arg s of wrong type string"}
                ],
                "lostcancel": [
                    {"posn": "a.go:20:2", "message": "the cancel function is not used"}
                ]
            }
        }"#;
        let f = report_findings(json).unwrap();
        assert_eq!(f.len(), 2);
        assert!(
            f.iter()
                .any(|s| s.contains("a.go:10:2") && s.contains("printf"))
        );
        assert!(f.iter().any(|s| s.contains("lostcancel")));
    }

    #[test]
    fn gate_empty_analyzer_arrays_yield_no_findings() {
        let json = br#"{"example.com/mylib": {"printf": []}}"#;
        assert!(report_findings(json).unwrap().is_empty());
    }

    #[test]
    fn gate_finding_names_the_golangci_linter() {
        let json = br#"{
            "example.com/mylib": {
                "ST1000": [{"posn": "a.go:1:1", "message": "package comment"}],
                "printf": [{"posn": "b.go:2:2", "message": "wrong arg"}]
            }
        }"#;
        let f = report_findings(json).unwrap();
        // golangci v2 folds stylecheck into staticcheck, so ST1000's nolint name
        // is `staticcheck`.
        assert!(
            f.iter().any(|s| s.contains("(staticcheck: ST1000)")),
            "ST1000 must name the staticcheck linter (v2): {f:?}"
        );
        assert!(
            f.iter().any(|s| s.contains("(govet: printf)")),
            "vet passes must name govet: {f:?}"
        );
    }

    #[test]
    fn golangci_linter_mapping() {
        // v2: all honnef families (SA/S/ST) report as staticcheck.
        assert_eq!(golangci_linter_of("SA1000"), "staticcheck");
        assert_eq!(golangci_linter_of("ST1000"), "staticcheck");
        assert_eq!(golangci_linter_of("S1002"), "staticcheck");
        assert_eq!(golangci_linter_of("printf"), "govet");
        assert_eq!(golangci_linter_of("lostcancel"), "govet");
        assert_eq!(golangci_linter_of("shadow"), "govet");
        assert_eq!(golangci_linter_of("slog"), "govet");
    }

    // ---- relativize ----

    #[test]
    fn relativize_strips_ws_root_from_posn_and_filenames() {
        let ws = std::path::Path::new("/sandbox/abc/ws");
        let json = br#"{
            "example.com/mylib": {
                "gosimple": [
                    {
                        "posn": "/sandbox/abc/ws/mylib/a.go:10:2",
                        "message": "should omit comparison",
                        "suggested_fixes": [
                            {"edits": [
                                {"filename": "/sandbox/abc/ws/mylib/a.go", "start": 5, "end": 7, "new": ""}
                            ]}
                        ]
                    }
                ]
            }
        }"#;
        let out = relativize_report_paths(json, ws);
        let v: serde_json::Value = serde_json::from_slice(&out).unwrap();
        let diag = &v["example.com/mylib"]["gosimple"][0];
        assert_eq!(diag["posn"], "mylib/a.go:10:2");
        assert_eq!(
            diag["suggested_fixes"][0]["edits"][0]["filename"],
            "mylib/a.go"
        );
        // The findings the gate prints are now package-relative.
        let findings = report_findings(&out).unwrap();
        assert!(
            findings.iter().all(|f| !f.contains("/sandbox/")),
            "findings still carry an absolute path: {findings:?}"
        );
        // And the fixer still keys edits by basename.
        assert!(report_edits(&out).unwrap().contains_key("a.go"));
    }

    #[test]
    fn relativize_leaves_paths_outside_ws_root_and_bad_json_untouched() {
        let ws = std::path::Path::new("/sandbox/abc/ws");
        let json = br#"{"p": {"printf": [{"posn": "/elsewhere/a.go:1:1", "message": "m"}]}}"#;
        let out = relativize_report_paths(json, ws);
        let v: serde_json::Value = serde_json::from_slice(&out).unwrap();
        assert_eq!(v["p"]["printf"][0]["posn"], "/elsewhere/a.go:1:1");

        // Non-JSON input is returned verbatim so the consumer sees the real error.
        assert_eq!(relativize_report_paths(b"not json", ws), b"not json");
        assert_eq!(relativize_report_paths(b"{}", ws), b"{}");
    }

    #[test]
    fn gate_spec_driver_and_report_dep() {
        let analyze = Addr::new(
            PkgBuf::from("mylib"),
            "_lint-analyze".to_string(),
            Default::default(),
        );
        let s = build_lint_gate_spec(addr("lint-check"), &analyze, None);
        assert_eq!(s.driver, "go_lint_gate");
        let deps = match s.config.get("deps").unwrap() {
            Value::Map(m) => m,
            _ => panic!("deps not a map"),
        };
        let report = match deps.get("report").unwrap() {
            Value::List(l) => l,
            _ => panic!("report not a list"),
        };
        match &report[0] {
            Value::String(s) => assert!(
                s.contains(":_lint-analyze") && s.ends_with("|report"),
                "gate must depend on the analyze target's report output: {s}"
            ),
            _ => panic!("not a string"),
        }
    }

    #[tokio::test]
    async fn gate_and_fix_take_golangci_config_as_hash_only_dep() {
        let analyze = Addr::new(
            PkgBuf::from("mylib"),
            "_lint-analyze".to_string(),
            Default::default(),
        );
        let cfg = Addr::new(PkgBuf::from(""), "file".to_string(), Default::default());

        let gate = build_lint_gate_spec(addr("lint-check"), &analyze, Some(&cfg));
        assert!(
            deps_map(&gate).contains_key("config"),
            "gate must depend on the golangci config so a config change re-keys it"
        );
        // Without a config addr, no config dep (keeps the no-config path clean).
        let gate_none = build_lint_gate_spec(addr("lint-check"), &analyze, None);
        assert!(!deps_map(&gate_none).contains_key("config"));

        let fix = build_lint_fix_spec(
            addr("lint"),
            &analyze,
            &["//mylib:a.go".to_string()],
            &["a.go".to_string()],
            Some(&cfg),
        );
        assert!(deps_map(&fix).contains_key("config"));

        // parse() marks the `config` group hash-only (runtime:false): it re-keys
        // the target but is never staged (the gate never reads the file).
        let token = hcore::hasync::StdCancellationToken::new();
        let parsed = GoLintGateDriver
            .parse(
                ParseRequest {
                    request_id: "t".to_string(),
                    target_spec: Arc::new(gate),
                },
                &token,
            )
            .await
            .unwrap();
        let cfg_input = parsed
            .target_def
            .inputs
            .iter()
            .find(|i| i.origin_id.starts_with("dep|config|"))
            .expect("config input present");
        assert!(cfg_input.hashed, "config must contribute to the hash");
        assert!(!cfg_input.runtime, "config must not be staged (hash-only)");
    }

    // ---- fix ----

    // The report's byte offsets index the file the analyzer parsed; edits are
    // keyed by basename because the report's `filename` is an absolute sandbox
    // path. Here `s1002` rewrites `if b == true` → `if b`.
    #[test]
    fn fix_extracts_edits_by_basename() {
        let json = br#"{
            "example.com/mylib": {
                "gosimple": [
                    {"posn": "/sandbox/mylib/a.go:3:5", "message": "S1002",
                     "suggested_fixes": [
                       {"message": "remove", "edits": [
                         {"filename": "/sandbox/mylib/a.go", "start": 5, "end": 14, "new": "b"}
                       ]}
                     ]}
                ]
            }
        }"#;
        let edits = report_edits(json).unwrap();
        let a = edits.get("a.go").expect("keyed by basename");
        assert_eq!(a.len(), 1);
        assert_eq!(a[0].start, 5);
        assert_eq!(a[0].end, 14);
        assert_eq!(a[0].new, "b");
    }

    #[test]
    fn fix_ignores_diagnostics_without_suggested_fixes() {
        let json = br#"{"m": {"printf": [{"posn": "a.go:1:1", "message": "no fix"}]}}"#;
        assert!(report_edits(json).unwrap().is_empty());
    }

    #[test]
    fn fix_takes_only_the_first_suggested_fix() {
        // Two alternative fixes for one diagnostic: only the first applies.
        let json = br#"{"m": {"l": [{"posn": "a.go:1:1", "message": "x",
            "suggested_fixes": [
              {"message": "one", "edits": [{"filename": "a.go", "start": 0, "end": 1, "new": "A"}]},
              {"message": "two", "edits": [{"filename": "a.go", "start": 2, "end": 3, "new": "B"}]}
            ]}]}}"#;
        let edits = report_edits(json).unwrap();
        let a = edits.get("a.go").unwrap();
        assert_eq!(a.len(), 1, "only the first fix's edits are taken");
        assert_eq!(a[0].new, "A");
    }

    #[test]
    fn apply_edits_splices_in_offset_order() {
        let src = b"hello world";
        let mut edits = vec![
            FixEdit {
                start: 6,
                end: 11,
                new: "rust".into(),
            },
            FixEdit {
                start: 0,
                end: 5,
                new: "bye".into(),
            },
        ];
        assert_eq!(apply_edits(src, &mut edits).unwrap(), b"bye rust");
    }

    #[test]
    fn apply_edits_drops_overlapping_keeping_earliest() {
        let src = b"abcdef";
        // Second edit [1,4) overlaps the first [0,3): the earliest wins, second dropped.
        let mut edits = vec![
            FixEdit {
                start: 0,
                end: 3,
                new: "X".into(),
            },
            FixEdit {
                start: 1,
                end: 4,
                new: "Y".into(),
            },
        ];
        assert_eq!(apply_edits(src, &mut edits).unwrap(), b"Xdef");
    }

    #[test]
    fn apply_edits_drops_out_of_range() {
        let src = b"abc";
        let mut edits = vec![FixEdit {
            start: 2,
            end: 99,
            new: "Z".into(),
        }];
        assert!(apply_edits(src, &mut edits).is_none());
    }

    #[test]
    fn apply_edits_none_when_empty() {
        assert!(apply_edits(b"abc", &mut []).is_none());
    }

    #[test]
    fn apply_edits_pure_insertion() {
        // Zero-width edit (start == end) inserts without deleting.
        let src = b"ac";
        let mut edits = vec![FixEdit {
            start: 1,
            end: 1,
            new: "b".into(),
        }];
        assert_eq!(apply_edits(src, &mut edits).unwrap(), b"abc");
    }

    #[test]
    fn fix_spec_driver_deps_and_in_place_outputs() {
        let analyze = Addr::new(
            PkgBuf::from("mylib"),
            "_lint-analyze".to_string(),
            Default::default(),
        );
        let s = build_lint_fix_spec(
            addr("lint"),
            &analyze,
            &["//mylib:a.go".to_string()],
            &["a.go".to_string()],
            None,
        );
        assert_eq!(s.driver, "go_lint_fix");

        // Depends on `_lint-analyze`'s report + the sources (default group).
        let deps = match s.config.get("deps").unwrap() {
            Value::Map(m) => m,
            _ => panic!("deps not a map"),
        };
        match deps.get("report").unwrap() {
            Value::List(l) => match &l[0] {
                Value::String(v) => {
                    assert!(
                        v.contains(":_lint-analyze") && v.ends_with("|report"),
                        "report dep: {v}"
                    );
                }
                _ => panic!("report not string"),
            },
            _ => panic!("report not list"),
        }
        match deps.get("").unwrap() {
            Value::List(l) => assert_eq!(l, &vec![Value::String("//mylib:a.go".to_string())]),
            _ => panic!("sources not list"),
        }

        // Declares the `.go` files as outputs.
        match s.config.get("out").unwrap() {
            Value::Map(m) => match m.get("src").unwrap() {
                Value::List(l) => assert_eq!(l, &vec![Value::String("a.go".to_string())]),
                _ => panic!("src not list"),
            },
            _ => panic!("out not map"),
        }
    }

    // The crux of the feature: parse() must mark the rewritten sources as
    // `codegen=in_place` (pkg-prefixed) so the engine writes them back over the
    // tracked source files.
    #[tokio::test]
    async fn fix_parse_declares_in_place_pkg_relative_outputs() {
        let analyze = Addr::new(
            PkgBuf::from("mylib"),
            "_lint-analyze".to_string(),
            Default::default(),
        );
        let spec = build_lint_fix_spec(
            addr("lint"),
            &analyze,
            &["//mylib:a.go".to_string()],
            &["a.go".to_string()],
            None,
        );
        let req = ParseRequest {
            request_id: "t".to_string(),
            target_spec: Arc::new(spec),
        };
        let token = hcore::hasync::StdCancellationToken::new();
        let resp = GoLintFixDriver::new().parse(req, &token).await.unwrap();
        let out = &resp.target_def.outputs;
        let path = out
            .iter()
            .flat_map(|o| &o.paths)
            .next()
            .expect("one output path");
        assert_eq!(path.codegen_tree, CodegenMode::InPlace);
        assert!(path.collect);
        match &path.content {
            Content::FilePath(p) => assert_eq!(p, "mylib/a.go", "output is pkg-relative"),
            other => panic!("expected FilePath, got {other}"),
        }
    }
}
