use crate::plugingo::pkg_analysis::{
    GoPackage, encode_go_package, encode_package_addrs, resolve_package_addrs,
};
use anyhow::Context;
use async_trait::async_trait;
use hcore::debug_hash::DebugHasher;
use hcore::hasync::Cancellable;
use hcore::htvalue::signature::ParamType;
use hdriver_support::driver_managed::{ManagedDriver, ManagedRunRequest, ManagedRunResponse};
use hplugin::driver::targetdef::path::{CodegenMode, Content, Path};
use hplugin::driver::targetdef::{CacheConfig, Input, InputMode, Output, TargetDef};
use hplugin::driver::{
    ApplyTransitiveRequest, ApplyTransitiveResponse, ConfigRequest, ConfigResponse, ParseRequest,
    ParseResponse, TargetAddr,
};
use hplugin::htspec::Spec;
use hproc::proc_exec;
use std::collections::HashMap;
use std::ffi::OsString;
use std::hash::{Hash, Hasher};
use std::sync::Arc;
use xxhash_rust::xxh3::Xxh3Default;

/// The `-json=` field selection every `go list` in this plugin asks for. Named
/// rather than inlined so the shape stays in one place: the field set is part of
/// what a shared `GOCACHE` entry is keyed by, so two call sites that drifted
/// apart would quietly stop sharing cache entries.
const GOLIST_JSON_FIELDS: &str = "-json=Dir,ImportPath,Name,GoFiles,SFiles,HFiles,TestGoFiles,XTestGoFiles,EmbedPatterns,EmbedFiles,TestEmbedPatterns,TestEmbedFiles,XTestEmbedPatterns,XTestEmbedFiles,Imports,TestImports,XTestImports,Standard,Module,Match,Incomplete,Error";

pub struct GoGolistDriver {
    /// Resolves the `GOCACHE` each golist run uses — shared across sandboxes
    /// when the engine handed us a home dir. See
    /// [`crate::plugingo::golist_gocache`] for why sharing it is both sound and
    /// the only thing that moves cold wall time.
    gocache: crate::plugingo::golist_gocache::GolistGocache,
}

/// Config for a `go_golist` target (engine-generated by the Go provider).
/// `#[derive(Spec)]` provides the parser and the LSP schema. The hermetic Go SDK
/// arrives as a normal dep (group `gosdk`); the driver derives GOROOT and the
/// `go` binary from its staged path — nothing is read from the host.
#[derive(Spec)]
struct GoGolistSpec {
    /// Go import path of the package to analyze.
    #[spec(required)]
    import_path: String,
    /// Target GOOS.
    #[spec(required)]
    goos: String,
    /// Target GOARCH.
    #[spec(required)]
    goarch: String,
    /// Go release whose staged hermetic SDK provides GOROOT + the `go` binary.
    #[spec(required)]
    go_version: String,
    /// Go build tags.
    build_tags: Vec<String>,
    /// `GOEXPERIMENT` values from the variant (sorted). Empty → unset.
    goexperiment: Vec<String>,
    /// Race-detector build: pass `-race` to `go list`. Changes both the file set
    /// (`//go:build race`) and the import graph, so the listing must be done in
    /// the same mode the archives will be compiled in.
    race: bool,
    /// Pass `-test` to `go list` — needed only when the package has `_test.go`
    /// files whose imports and embed patterns must be resolved. See
    /// [`crate::plugingo::target_golist`] for who sets it.
    with_test: bool,
    /// For thirdparty packages: the `download` target whose filtered outputs are
    /// staged into consumers' sandboxes.
    #[spec(ty = ParamType::String)]
    thirdparty_download_addr: Option<String>,
    /// True for a package in the user's own module, whose `.go` sources are
    /// staged into the sandbox as declared deps. Stdlib and thirdparty packages
    /// read their sources from GOROOT / the module cache instead, so an empty
    /// sandbox says nothing about them.
    firstparty: bool,
    /// Source/mod dependencies, grouped by name → list of target addresses.
    deps: HashMap<String, Vec<String>>,
    /// Declared outputs, grouped by name → list of output paths.
    out: HashMap<String, Vec<String>>,
    /// Exec runner this tool runs under: a target address producing a
    /// `runner.json`, so the tool runs inside a described environment (a devenv
    /// shell, a container) instead of on the bare host. Absent, or the literal
    /// `"local"`, spawns here as before. A hashed dependency, so changing the
    /// environment re-keys this target.
    runner: String,
}

impl GoGolistDriver {
    /// Sandbox-local `GOCACHE`, the pre-sharing behaviour. For in-process
    /// constructions (tests, the e2e harness) that have no engine home dir to
    /// share a cache through.
    pub fn new() -> Self {
        Self {
            gocache: crate::plugingo::golist_gocache::GolistGocache::new(None),
        }
    }

    /// Share one `GOCACHE` per toolchain across golist sandboxes, under
    /// `gocache_root` — a directory the caller owns and heph may write to (the
    /// engine home dir). A plugin is handed its writable locations rather than
    /// discovering them, so this is the only way sharing is turned on.
    pub fn with_gocache_root(gocache_root: std::path::PathBuf) -> Self {
        Self {
            gocache: crate::plugingo::golist_gocache::GolistGocache::new(Some(gocache_root)),
        }
    }
}

impl Default for GoGolistDriver {
    fn default() -> Self {
        Self::new()
    }
}

#[derive(Clone, serde::Serialize, serde::Deserialize)]
struct GoGolistDef {
    import_path: String,
    goos: String,
    goarch: String,
    go_version: String,
    build_tags: Vec<String>,
    goexperiment: Vec<String>,
    /// See [`GoGolistSpec::race`].
    race: bool,
    with_test: bool,
    dep_inputs: Vec<Input>,
    /// For thirdparty packages: the `download` target whose filtered outputs
    /// will be staged into consumers' sandboxes. Threaded through so
    /// `resolve_package_addrs` emits download-filter refs instead of pluginfs
    /// file refs for per-file addresses.
    thirdparty_download_addr: Option<String>,
    /// See [`GoGolistSpec::firstparty`].
    firstparty: bool,
    /// Exec runner for this target's tool. Deliberately absent from `Hash` —
    /// see `plugingo::runner`: it reaches the cache key through the hashout of
    /// the input `parse` emits, exactly as a `hash_dep` does.
    runner: Option<TargetAddr>,
}

/// Bump to invalidate every cached `_golist` artifact whenever the driver's
/// output format (package.bin layout, package_addrs.bin schema, …) OR the
/// embed/compile behavior that consumes it changes. v15: the compile+embed
/// integration (PR #121) reshaped how `EmbedFiles`/`EmbedPatterns` flow into
/// `go_compile`; cached `_golist` artifacts from intermediate builds of that
/// work could carry empty `EmbedFiles` for a now-resolvable embed, surfacing as
/// `compute embedcfg: //go:embed pattern(s) matched no files` until evicted.
/// v17: `firstparty` joined the def, changing every golist target's def hash.
const GO_GOLIST_FORMAT_VERSION: u32 = 17;

impl Hash for GoGolistDef {
    fn hash<H: Hasher>(&self, state: &mut H) {
        GO_GOLIST_FORMAT_VERSION.hash(state);
        self.import_path.hash(state);
        self.goos.hash(state);
        self.goarch.hash(state);
        self.go_version.hash(state);
        self.build_tags.hash(state);
        self.goexperiment.hash(state);
        // Hashed only when set, so introducing race mode left every ordinary
        // `_golist` def hash — and therefore every cached listing — untouched.
        // The marker is a distinct string, so it cannot alias a neighbouring
        // field's contribution.
        if self.race {
            "race".hash(state);
        }
        // Flips the `go list` command line, and with it which fields come back
        // populated — so it must key the cache.
        self.with_test.hash(state);
        self.dep_inputs.hash(state);
        self.thirdparty_download_addr.hash(state);
        self.firstparty.hash(state);
        // The hermetic SDK arrives via dep_inputs (group `gosdk`); the engine
        // hashes its content, so no separate goroot/go_bin field is hashed here.
    }
}

#[async_trait]
impl ManagedDriver for GoGolistDriver {
    fn config(&self, _req: ConfigRequest) -> anyhow::Result<ConfigResponse> {
        Ok(ConfigResponse {
            name: "go_golist".to_string(),
        })
    }

    fn schema(&self) -> hplugin::driver::DriverSchema {
        GoGolistSpec::schema()
    }

    async fn parse(
        &self,
        req: ParseRequest,
        _ctoken: &(dyn Cancellable + Send + Sync),
    ) -> anyhow::Result<ParseResponse> {
        let pkg = req.target_spec.addr.package.clone();
        let pkg_str = pkg.as_str();

        let spec = GoGolistSpec::from(&req.target_spec.config).context("parse go_golist config")?;

        // Parse deps (srcfiles, modfiles) — no go_bin here
        let dep_strings = spec.deps;

        let mut dep_groups: Vec<&String> = dep_strings.keys().collect();
        dep_groups.sort();
        let mut dep_inputs: Vec<Input> = Vec::new();
        for group in dep_groups {
            let addrs = dep_strings.get(group).expect("group key from same map");
            // The hermetic SDK (group `gosdk`) is read-only and identical across
            // every golist target — stage it once and hardlink it into each
            // sandbox instead of byte-copying the whole tree (incl. ~150 MB of
            // std `src/`) per package. Source deps keep the source-map
            // annotation so golist can map codegen output back to its target.
            let is_sdk = group.as_str() == crate::plugingo::addr_util::GO_SDK_DEP_GROUP;
            let annotations = if is_sdk {
                std::collections::BTreeMap::from([(
                    hdriver_support::stage::READ_ONLY_ANNOTATION.to_string(),
                    "true".to_string(),
                )])
            } else {
                std::collections::BTreeMap::from([(
                    hdriver_support::driver_managed::SOURCE_MAP_ANNOTATION.to_string(),
                    "true".to_string(),
                )])
            };
            for (i, addr_str) in addrs.iter().enumerate() {
                dep_inputs.push(Input {
                    r#ref: TargetAddr::parse(addr_str, &pkg)
                        .with_context(|| format!("parse dep addr {addr_str}"))?,
                    mode: InputMode::Standard,
                    origin_id: format!("dep|{group}|{i}"),
                    annotations: annotations.clone(),
                    hashed: true,
                    runtime: true,
                });
            }
        }

        let (runner, runner_input) = super::runner::parse_runner(&spec.runner, &pkg)?;
        dep_inputs.extend(runner_input);

        let def = GoGolistDef {
            runner,
            import_path: spec.import_path,
            goos: spec.goos,
            goarch: spec.goarch,
            go_version: spec.go_version,
            build_tags: spec.build_tags,
            goexperiment: spec.goexperiment,
            race: spec.race,
            with_test: spec.with_test,
            dep_inputs: dep_inputs.clone(),
            thirdparty_download_addr: spec.thirdparty_download_addr,
            firstparty: spec.firstparty,
        };

        let hash = {
            let mut h = DebugHasher::new(Xxh3Default::new(), || {
                format!("go_golist_{}", req.target_spec.addr.format())
            });
            def.hash(&mut h);
            format!("{:x}", h.finish()).into_bytes()
        };

        // Parse outputs from spec, prepend package path
        let outputs = spec
            .out
            .iter()
            .map(|(group, paths)| Output {
                group: group.clone(),
                paths: paths
                    .iter()
                    .map(|p| {
                        let full_path = if pkg_str.is_empty() {
                            p.clone()
                        } else {
                            format!("{pkg_str}/{p}")
                        };
                        Path {
                            content: Content::FilePath(full_path),
                            codegen_tree: CodegenMode::None,
                            collect: true,
                        }
                    })
                    .collect(),
            })
            .collect();

        Ok(ParseResponse {
            target_def: TargetDef {
                addr: req.target_spec.addr.clone(),
                labels: req.target_spec.labels.clone(),
                raw_def: Arc::new(def),
                inputs: dep_inputs,
                outputs,
                support_files: vec![],
                cache: CacheConfig::on(true),
                pty: false,
                hash,
                transparent: false,
            },
        })
    }

    async fn apply_transitive(
        &self,
        req: ApplyTransitiveRequest,
        _ctoken: &(dyn Cancellable + Send + Sync),
    ) -> anyhow::Result<ApplyTransitiveResponse> {
        Ok(ApplyTransitiveResponse {
            target_def: req.target_def,
        })
    }

    async fn run<'a, 'io>(
        &self,
        req: ManagedRunRequest<'a, 'io>,
        ctoken: &(dyn Cancellable + Send + Sync),
    ) -> anyhow::Result<ManagedRunResponse> {
        let def = req.request.target.def_de::<GoGolistDef>();

        // GOROOT and the `go` binary depend on the selected toolchain (host,
        // target-ref, or hermetic) — see [`toolchain::resolve_toolchain_go`].
        use crate::plugingo::toolchain::Toolchain;
        let (goroot, go_bin) = crate::plugingo::toolchain::resolve_toolchain_go(
            &def.go_version,
            &req.inputs,
            &req.sandbox_ws_dir,
            "go_golist",
        )?;
        // The build cache `go list` runs against. Shared across sandboxes per
        // toolchain when the engine gave us a home dir, so the standard
        // library's test metadata is derived once per repo instead of once per
        // package — and, more to the point, so no cache is materialized and torn
        // down inside each sandbox. The host GOCACHE is still never touched.
        // See `golist_gocache` for why this is sound.
        let gocache = self.gocache.resolve(
            &crate::plugingo::golist_gocache::GocacheKey {
                goroot: goroot.clone(),
                goos: def.goos.clone(),
                goarch: def.goarch.clone(),
                build_tags: def.build_tags.clone(),
                goexperiment: def.goexperiment.clone(),
                race: def.race,
            },
            &req.sandbox_pkg_dir.join(".heph-gocache"),
        )?;

        let mut env: HashMap<String, String> = HashMap::new();
        env.insert("GOOS".to_string(), def.goos.clone());
        env.insert("GOARCH".to_string(), def.goarch.clone());
        env.insert("GOROOT".to_string(), goroot.to_string_lossy().into_owned());
        env.insert(
            "GOCACHE".to_string(),
            gocache.to_string_lossy().into_owned(),
        );
        // Pin the toolchain to the staged SDK and ignore any workspace go.work so
        // resolution is reproducible regardless of host config.
        env.insert("GOTOOLCHAIN".to_string(), "local".to_string());
        env.insert("GOWORK".to_string(), "off".to_string());
        // Pin CGO_ENABLED rather than letting Go autodetect it: autodetection is
        // PATH-dependent and drifts across hosts — e.g. an Ubuntu host with gcc on
        // PATH pulls runtime/cgo in here but later link steps run without it,
        // breaking importcfg. The value must match what the compile/link sandboxes
        // use, which is `0` for every ordinary build and `1` only for a race build
        // off darwin (see `factors::cgo_required`).
        env.insert(
            "CGO_ENABLED".to_string(),
            crate::plugingo::factors::cgo_enabled_value(&def.goos, def.race).to_string(),
        );
        if !def.goexperiment.is_empty() {
            env.insert("GOEXPERIMENT".to_string(), def.goexperiment.join(","));
        }
        // Thirdparty module *metadata* listing still consults the host module
        // cache / proxy (modules are content-addressed and verified by go.sum),
        // matching the v1 plugin; first-party and stdlib reads stay fully
        // hermetic via the staged SDK above.
        for name in &[
            "GOPATH",
            "GOMODCACHE",
            "HOME",
            "GONOSUMDB",
            "GOFLAGS",
            "GOPRIVATE",
            "GOPROXY",
        ] {
            if let Ok(v) = std::env::var(name) {
                env.insert(name.to_string(), v);
            }
        }
        // Non-hermetic toolchains: the `go` subprocess (or a hostbin/nix wrapper)
        // may need PATH — to locate ancillary tools, or for the wrapper itself.
        // Hermetic mode deliberately omits it to stay PATH-independent.
        if !matches!(
            crate::plugingo::toolchain::classify(&def.go_version),
            Toolchain::Hermetic(_)
        ) && let Ok(v) = std::env::var("PATH")
        {
            env.insert("PATH".to_string(), v);
        }

        // A first-party directory with no `.go` file staged into it cannot be a
        // Go package — a Go package needs at least one `.go` file, and every
        // source that could make it one (checked-in *and* codegen output, via
        // the `srcfiles` deps) is already materialized here. So `go list` can
        // only come back with the "no Go files" error the provider maps to
        // NotFound, and spawning it to learn that is pure cost.
        //
        // This is not a small tail: heph emits go targets per *directory*, not
        // per Go package, so on a 500-package corpus 1171 of the 1945 golist
        // targets are directories that only hold subdirectories or assets.
        //
        // Deliberately decided from the *staged inputs* rather than the
        // workspace: reading the real tree would be an undeclared input, and
        // would miss generated sources that only exist in the sandbox. Gated on
        // `firstparty` because stdlib/thirdparty packages stage no sources at
        // all — their emptiness means nothing.
        if def.firstparty && !has_go_file(&req.sandbox_pkg_dir)? {
            let pkg = GoPackage {
                import_path: def.import_path.clone(),
                error: Some(crate::plugingo::pkg_analysis::GoPackageError {
                    err: format!("no Go files in {}", def.import_path),
                }),
                ..Default::default()
            };
            let package_bin = encode_go_package(&pkg).context("encode package.bin")?;
            std::fs::write(req.sandbox_pkg_dir.join("package.bin"), &package_bin)
                .context("write package.bin")?;
            let addrs_bin =
                encode_package_addrs(&crate::plugingo::pkg_analysis::PackageAddrs::default())
                    .context("encode package_addrs.bin")?;
            std::fs::write(req.sandbox_pkg_dir.join("package_addrs.bin"), &addrs_bin)
                .context("write package_addrs.bin")?;
            return Ok(ManagedRunResponse { artifacts: vec![] });
        }

        let args: Vec<OsString> = golist_args(def).iter().map(OsString::from).collect();
        let env_pairs: Vec<(OsString, OsString)> = env
            .iter()
            .map(|(k, v)| (OsString::from(k), OsString::from(v)))
            .collect();

        // setsid=false: `go list` is single-process; the supervisor's
        // direct-pid kill is sufficient on hard-shutdown.
        let spec = proc_exec::Spec {
            program: go_bin.clone(),
            args,
            env: env_pairs,
            cwd: req.sandbox_pkg_dir.clone(),
            stdin: proc_exec::StdioSpec::Null,
            stdout: proc_exec::StdioSpec::Piped,
            stderr: proc_exec::StdioSpec::Piped,
            setsid: false,
            ctty: false,
        };

        let output = hexecrunner::output(
            super::runner::runner_ref(req.request.request_id, def.runner.as_ref()),
            spec,
            ctoken,
        )
        .await
        .with_context(|| format!("wait for go list for {}", def.import_path))?;

        if !output.status.success() {
            let stderr = String::from_utf8_lossy(&output.stderr);
            return Err(crate::plugingo::errors::GoListError {
                import_path: def.import_path.clone(),
                stderr_tail: hplugin::error::last_n_lines(&stderr, 10),
            }
            .into());
        }

        // Parse once, normalize Dir on the struct, then serialize package.bin and
        // reuse the same value for addr resolution below.
        //
        // `-test` makes go list emit synthetic variants (`pkg.test`, `pkg [pkg.test]`,
        // `pkg_test [pkg.test]`); we keep only the canonical entry whose ImportPath
        // matches the request — that one has the resolved TestEmbedFiles /
        // XTestEmbedFiles we actually need downstream.
        let ws_prefix = req.sandbox_ws_dir.to_string_lossy();
        let mut pkgs: Vec<GoPackage> = serde_json::Deserializer::from_slice(&output.stdout)
            .into_iter::<GoPackage>()
            .collect::<Result<_, _>>()
            .context("parse go list output")?;
        pkgs.retain(|p| p.import_path == def.import_path);
        for p in &mut pkgs {
            normalize_pkg_paths(p, &ws_prefix);
        }

        let pkg = pkgs.into_iter().next().ok_or_else(|| {
            anyhow::anyhow!("go list returned no entry matching {}", def.import_path)
        })?;

        let package_bin = encode_go_package(&pkg).context("encode package.bin")?;
        std::fs::write(req.sandbox_pkg_dir.join("package.bin"), &package_bin)
            .context("write package.bin")?;

        let source_map_path = req.sandbox_pkg_dir.join("source_map.json");
        let source_map: HashMap<String, String> = if source_map_path.exists() {
            let raw = std::fs::read_to_string(&source_map_path)
                .with_context(|| format!("read {source_map_path:?}"))?;
            serde_json::from_str(&raw).with_context(|| "parse source_map.json")?
        } else {
            HashMap::new()
        };

        let pkg_str = req.request.target.addr.package.as_str();
        let download_addr = match &def.thirdparty_download_addr {
            Some(s) => Some(
                hplugin::driver::TargetAddr::parse(s, &hmodel::htpkg::PkgBuf::from(""))
                    .with_context(|| format!("parse thirdparty_download_addr {s:?}"))?
                    .r#ref,
            ),
            None => None,
        };
        let mut addrs = resolve_package_addrs(&pkg, pkg_str, &source_map, download_addr.as_ref());

        // circl-style asm `#include`s reach into sibling packages of the same
        // module (`dh/x448` → `../../math/fp448/fp_amd64.h`). Those headers
        // aren't in this package's HFiles, so scan the asm sources and stage the
        // siblings via the module-root download target at their module-relative
        // path — the path the `-I .` asm step resolves them against.
        if let (Some(dl), false) = (download_addr.as_ref(), pkg.s_files.is_empty())
            && let Some(pkg_dir) = pkg.dir.as_deref()
        {
            let module_ws_root = dl.package.as_str();
            let subpath = pkg_str
                .strip_prefix(module_ws_root)
                .map(|s| s.trim_start_matches('/'))
                .unwrap_or("");
            addrs.extra_h_files = crate::plugingo::pkg_analysis::collect_cross_pkg_asm_headers(
                pkg_dir,
                subpath,
                &pkg.s_files,
            )
            .into_iter()
            .map(|rel| {
                TargetAddr {
                    r#ref: dl.clone(),
                    output: None,
                    filters: vec![format!("{module_ws_root}/{rel}")],
                }
                .to_string()
            })
            .collect();
        }

        let addrs_bin = encode_package_addrs(&addrs).context("encode package_addrs.bin")?;
        std::fs::write(req.sandbox_pkg_dir.join("package_addrs.bin"), &addrs_bin)
            .context("write package_addrs.bin")?;

        Ok(ManagedRunResponse { artifacts: vec![] })
    }
}

/// Whether `dir` directly contains a file ending in `.go`.
///
/// Non-recursive on purpose: a Go package is exactly one directory, and the
/// `srcfiles` glob that stages sources is `<pkg>/*.go` for the same reason. A
/// subdirectory's sources belong to a different package with its own `_golist`.
/// `*_test.go` counts — a directory holding only tests is still a package.
///
/// A missing directory reads as "no Go files": the sandbox only materializes
/// directories that some input actually lands in.
fn has_go_file(dir: &std::path::Path) -> anyhow::Result<bool> {
    let entries = match std::fs::read_dir(dir) {
        Ok(e) => e,
        Err(e) if e.kind() == std::io::ErrorKind::NotFound => return Ok(false),
        Err(e) => return Err(e).with_context(|| format!("read staged package dir {dir:?}")),
    };
    for entry in entries {
        let entry = entry.with_context(|| format!("read staged package dir {dir:?}"))?;
        if std::path::Path::new(&entry.file_name())
            .extension()
            .is_some_and(|e| e == "go")
            && !entry.file_type().map(|t| t.is_dir()).unwrap_or(false)
        {
            return Ok(true);
        }
    }
    Ok(false)
}

/// The `go list` command line for one package.
///
/// `-test` populates TestEmbedFiles / XTestEmbedFiles and resolves test imports.
/// Without it `go list` reports test embed *patterns* but never resolves them,
/// so the test embedcfg path would glob against an empty staged-file set. The
/// flag also adds synthetic `pkg.test` / `pkg [pkg.test]` / `pkg_test [pkg.test]`
/// entries, which `run` discards in favour of the plain `pkg` entry.
///
/// It is not free: it makes `go list` load the package a second time in its test
/// configuration, pulling the test imports' own closure. Measured over 60 std
/// packages listed one at a time against a *fresh shared* `GOCACHE` — i.e. what
/// [`crate::plugingo::golist_gocache`] gives a cold run today — dropping `-test`
/// took CPU from 3.72s to 2.58s (-31%) and wall from 1.89s to 1.69s (-11%).
///
/// The gap used to be far wider: before the shared `GOCACHE`, every sandbox
/// re-warmed its own, and `-test` was ~3x the call. Sharing the cache absorbed
/// most of that, so this is now a modest trim on the cold path and nothing at
/// all on a full cache hit — do not quote it as a headline.
///
/// So the provider asks for it only where a test field can actually be read
/// back — a first-party package with `_test.go` files on disk. std and
/// thirdparty build no tests under heph and never pay it.
fn golist_args(def: &GoGolistDef) -> Vec<String> {
    let mut args = vec![
        "list".to_string(),
        GOLIST_JSON_FIELDS.to_string(),
        "-e".to_string(),
    ];
    if def.with_test {
        args.push("-test".to_string());
    }
    if !def.build_tags.is_empty() {
        args.push(format!("-tags={}", def.build_tags.join(",")));
    }
    // `-race` rather than `-tags=race`: besides the build tag it also adds
    // `runtime/race` to the listed deps, which is how the linker gets told about
    // the TSan runtime (nothing in the source graph imports it).
    if def.race {
        args.push("-race".to_string());
    }
    args.push(def.import_path.clone());
    args
}

/// Strip every absolute path out of a `go list` package so the cached
/// `package.bin` is byte-identical across machines (and sandboxes). go reports
/// absolute paths in two places:
/// - `Dir`: rewritten repo-root-relative (it lives under the sandbox ws).
/// - `Module.Dir`: an absolute sandbox-ws path (first-party) or host
///   GOMODCACHE path (thirdparty). Nothing downstream reads it — only
///   `Module.Path` matters — so it's dropped. Left in, its per-machine
///   absolute value would make this output (and every consumer's hashin)
///   differ across machines, defeating the cache.
fn normalize_pkg_paths(p: &mut GoPackage, ws_prefix: &str) {
    if let Some(dir) = &p.dir {
        p.dir = Some(normalize_dir(dir, ws_prefix));
    }
    if let Some(m) = &mut p.module {
        m.dir = None;
    }
}

/// Strip `ws_prefix/` from a go list `Dir` path so it becomes repo-root-relative.
fn normalize_dir(dir: &str, ws_prefix: &str) -> String {
    let prefix_slash = format!("{ws_prefix}/");
    if let Some(rel) = dir.strip_prefix(&prefix_slash) {
        rel.to_string()
    } else if dir == ws_prefix {
        String::new()
    } else {
        dir.to_string()
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::plugingo::pkg_analysis::GoModule;
    use hmodel::htpkg::PkgBuf;

    fn driver() -> GoGolistDriver {
        GoGolistDriver::new()
    }

    mod has_go_file {
        use super::super::has_go_file;

        fn dir_with(names: &[&str]) -> tempfile::TempDir {
            let d = tempfile::tempdir().expect("tempdir");
            for n in names {
                std::fs::write(d.path().join(n), b"").expect("write");
            }
            d
        }

        #[test]
        fn plain_source_counts() {
            let d = dir_with(&["lib.go"]);
            assert!(has_go_file(d.path()).expect("scan"));
        }

        #[test]
        fn tests_alone_still_make_it_a_package() {
            // `go list -test` reports a synthetic entry for a directory holding
            // only `_test.go` files, so skipping it would lose real targets.
            for only in [&["pkg_test.go"][..], &["x_test.go"][..]] {
                let d = dir_with(only);
                assert!(
                    has_go_file(d.path()).expect("scan"),
                    "a test-only directory is still a Go package: {only:?}"
                );
            }
        }

        #[test]
        fn non_go_files_do_not_count() {
            // The directories this exists to skip: assets, and the parent dirs
            // that only hold subpackages.
            let d = dir_with(&[
                "README.md",
                "logo.png",
                "data.json",
                "go.mod",
                "gopher.gopher",
            ]);
            assert!(!has_go_file(d.path()).expect("scan"));
        }

        #[test]
        fn empty_and_missing_directories_have_no_go_files() {
            let d = dir_with(&[]);
            assert!(!has_go_file(d.path()).expect("scan"));
            assert!(
                !has_go_file(&d.path().join("never-materialized")).expect("scan"),
                "a directory no input landed in must read as empty, not error"
            );
        }

        #[test]
        fn a_directory_named_like_a_source_does_not_count() {
            let d = tempfile::tempdir().expect("tempdir");
            std::fs::create_dir(d.path().join("weird.go")).expect("mkdir");
            assert!(
                !has_go_file(d.path()).expect("scan"),
                "`go list` compiles files, not directories that happen to end in .go"
            );
        }

        #[test]
        fn a_subdirectorys_sources_do_not_count() {
            let d = tempfile::tempdir().expect("tempdir");
            std::fs::create_dir(d.path().join("sub")).expect("mkdir");
            std::fs::write(d.path().join("sub").join("lib.go"), b"").expect("write");
            assert!(
                !has_go_file(d.path()).expect("scan"),
                "a Go package is one directory; the subpackage has its own _golist"
            );
        }
    }

    fn make_parse_request(
        pkg: &str,
        import_path: &str,
        extra_deps: Vec<(&str, Vec<&str>)>,
    ) -> ParseRequest {
        use hcore::htvalue::Value;
        use hmodel::htaddr::Addr;
        use hplugin::provider::TargetSpec;
        use std::collections::HashMap;

        let mut config: HashMap<String, Value> = HashMap::new();
        config.insert(
            "import_path".to_string(),
            Value::String(import_path.to_string()),
        );
        config.insert("goos".to_string(), Value::String("linux".to_string()));
        config.insert("goarch".to_string(), Value::String("amd64".to_string()));
        config.insert(
            "go_version".to_string(),
            Value::String(crate::plugingo::toolchain::DEFAULT_GO_VERSION.to_string()),
        );
        config.insert(
            "out".to_string(),
            Value::Map(HashMap::from([
                (
                    "pkg".to_string(),
                    Value::List(vec![Value::String("package.bin".to_string())]),
                ),
                (
                    "addrs".to_string(),
                    Value::List(vec![Value::String("package_addrs.bin".to_string())]),
                ),
            ])),
        );

        if !extra_deps.is_empty() {
            let deps_map: HashMap<String, Value> = extra_deps
                .into_iter()
                .map(|(k, vs)| {
                    (
                        k.to_string(),
                        Value::List(
                            vs.into_iter()
                                .map(|v| Value::String(v.to_string()))
                                .collect(),
                        ),
                    )
                })
                .collect();
            config.insert("deps".to_string(), Value::Map(deps_map));
        }

        ParseRequest {
            request_id: "test".to_string(),
            target_spec: std::sync::Arc::new(TargetSpec {
                addr: Addr::new(PkgBuf::from(pkg), "_golist".to_string(), Default::default()),
                driver: "go_golist".to_string(),
                config,
                ..Default::default()
            }),
        }
    }

    fn noop_ctoken() -> hcore::hasync::StdCancellationToken {
        hcore::hasync::StdCancellationToken::new()
    }

    #[tokio::test]
    async fn test_driver_name_is_go_golist() {
        let resp = driver().config(ConfigRequest {}).unwrap();
        assert_eq!(resp.name, "go_golist");
    }

    #[tokio::test]
    async fn test_parse_missing_import_path_errors() {
        use hmodel::htaddr::Addr;
        use hplugin::provider::TargetSpec;
        use std::collections::HashMap;

        let ct = noop_ctoken();
        let req = ParseRequest {
            request_id: "test".to_string(),
            target_spec: std::sync::Arc::new(TargetSpec {
                addr: Addr::new(
                    PkgBuf::from("mylib"),
                    "_golist".to_string(),
                    Default::default(),
                ),
                driver: "go_golist".to_string(),
                ..Default::default()
            }),
        };
        assert!(driver().parse(req, &ct).await.is_err());
    }

    #[tokio::test]
    async fn test_parse_has_no_host_go_tool_input() {
        // The hermetic SDK arrives as a normal dep (group `gosdk`), staged by the
        // engine; the driver must not pull a host `go` binary as a Tool input.
        let ct = noop_ctoken();
        let req = make_parse_request(
            "mylib",
            "example.com/mylib",
            vec![("gosdk", vec!["//@heph/go/toolchain:go"])],
        );
        let resp = driver().parse(req, &ct).await.unwrap();
        assert!(
            !resp
                .target_def
                .inputs
                .iter()
                .any(|i| i.mode == InputMode::Tool),
            "golist must declare no Tool inputs (SDK is a dep)"
        );
        assert!(
            resp.target_def
                .inputs
                .iter()
                .any(|i| i.origin_id == "dep|gosdk|0"),
            "the hermetic SDK dep must flow through as a Standard input"
        );
    }

    #[tokio::test]
    async fn test_parse_gosdk_dep_is_read_only_but_sources_are_not() {
        // The SDK dep is identical across every golist target — mark it
        // read-only so the OS runner stages it once and hardlinks it in rather
        // than byte-copying the whole tree per package. Source deps stay on the
        // copy path (they carry the source-map annotation instead).
        let ct = noop_ctoken();
        let req = make_parse_request(
            "mylib",
            "example.com/mylib",
            vec![
                ("gosdk", vec!["//@heph/go/toolchain:go"]),
                ("srcfiles", vec!["//mylib:_go_src"]),
            ],
        );
        let resp = driver().parse(req, &ct).await.unwrap();
        let inputs = &resp.target_def.inputs;

        let sdk = inputs
            .iter()
            .find(|i| i.origin_id == "dep|gosdk|0")
            .expect("gosdk input present");
        assert_eq!(
            sdk.annotations
                .get(hdriver_support::stage::READ_ONLY_ANNOTATION)
                .map(String::as_str),
            Some("true"),
            "gosdk dep must be staged read-only"
        );

        let src = inputs
            .iter()
            .find(|i| i.origin_id == "dep|srcfiles|0")
            .expect("srcfiles input present");
        assert!(
            !src.annotations
                .contains_key(hdriver_support::stage::READ_ONLY_ANNOTATION),
            "source deps must not be read-only staged"
        );
    }

    #[tokio::test]
    async fn test_parse_dep_inputs_present() {
        let ct = noop_ctoken();
        let req = make_parse_request(
            "mylib",
            "example.com/mylib",
            vec![
                ("modfiles", vec!["//go.mod:_go_mod"]),
                ("srcfiles", vec!["//mylib:_go_src"]),
            ],
        );
        let resp = driver().parse(req, &ct).await.unwrap();
        let inputs = &resp.target_def.inputs;
        assert!(inputs.iter().any(|i| i.origin_id == "dep|modfiles|0"));
        assert!(inputs.iter().any(|i| i.origin_id == "dep|srcfiles|0"));
    }

    // Regression: dep groups came from a HashMap, so dep_inputs Vec order varied
    // across runs, making def.hash unstable and breaking the local cache for
    // go_golist targets. Order must now be sorted by group name.
    #[tokio::test]
    async fn test_parse_dep_inputs_order_is_deterministic() {
        let ct = noop_ctoken();
        let mk = || {
            make_parse_request(
                "mylib",
                "example.com/mylib",
                vec![
                    ("zsrc", vec!["//mylib:_go_src"]),
                    ("modfiles", vec!["//go.mod:_go_mod"]),
                    ("asrc", vec!["//mylib:_extra"]),
                ],
            )
        };
        let resp_a = driver().parse(mk(), &ct).await.unwrap();
        let resp_b = driver().parse(mk(), &ct).await.unwrap();

        let ids_a: Vec<&str> = resp_a
            .target_def
            .inputs
            .iter()
            .filter(|i| i.origin_id.starts_with("dep|"))
            .map(|i| i.origin_id.as_str())
            .collect();
        let ids_b: Vec<&str> = resp_b
            .target_def
            .inputs
            .iter()
            .filter(|i| i.origin_id.starts_with("dep|"))
            .map(|i| i.origin_id.as_str())
            .collect();

        assert_eq!(ids_a, ids_b, "dep input order must be stable across parses");
        // Verify it's sorted by group name (asrc < modfiles < zsrc).
        assert_eq!(ids_a, vec!["dep|asrc|0", "dep|modfiles|0", "dep|zsrc|0"]);
        assert_eq!(resp_a.target_def.hash, resp_b.target_def.hash);
    }

    #[tokio::test]
    async fn test_parse_outputs_prepend_package() {
        let ct = noop_ctoken();
        let req = make_parse_request("mylib", "example.com/mylib", vec![]);
        let resp = driver().parse(req, &ct).await.unwrap();
        let pkg_out = resp
            .target_def
            .outputs
            .iter()
            .find(|o| o.group == "pkg")
            .unwrap();
        assert!(pkg_out.paths.iter().any(|p| matches!(
            &p.content,
            Content::FilePath(s) if s == "mylib/package.bin"
        )));
    }

    #[tokio::test]
    async fn test_parse_outputs_no_prefix_for_empty_package() {
        let ct = noop_ctoken();
        let req = make_parse_request("", "example.com/mylib", vec![]);
        let resp = driver().parse(req, &ct).await.unwrap();
        let pkg_out = resp
            .target_def
            .outputs
            .iter()
            .find(|o| o.group == "pkg")
            .unwrap();
        assert!(pkg_out.paths.iter().any(|p| matches!(
            &p.content,
            Content::FilePath(s) if s == "package.bin"
        )));
    }

    fn def_with(with_test: bool, build_tags: Vec<String>) -> GoGolistDef {
        GoGolistDef {
            runner: None,
            import_path: "example.com/mylib".to_string(),
            goos: "linux".to_string(),
            goarch: "amd64".to_string(),
            go_version: crate::plugingo::toolchain::DEFAULT_GO_VERSION.to_string(),
            build_tags,
            goexperiment: vec![],
            race: false,
            with_test,
            dep_inputs: vec![],
            thirdparty_download_addr: None,
            firstparty: true,
        }
    }

    #[test]
    fn test_golist_args_omit_test_when_the_package_has_no_tests() {
        let args = golist_args(&def_with(false, vec![]));
        assert!(
            !args.iter().any(|a| a == "-test"),
            "a package with no test files must not pay for the test-config load: {args:?}"
        );
        // The rest of the command is unchanged — same field set, still -e, and
        // the import path stays last.
        assert!(args.iter().any(|a| a == "-e"));
        assert_eq!(args.last().map(String::as_str), Some("example.com/mylib"));
    }

    /// `-race` (not `-tags=race`): besides the build tag it adds `runtime/race`
    /// to the listed deps, which is the only reason the listing knows about the
    /// TSan runtime at all.
    #[test]
    fn golist_args_pass_race_when_set() {
        let mut def = def_with(false, vec![]);
        assert!(!golist_args(&def).iter().any(|a| a == "-race"));
        def.race = true;
        assert!(golist_args(&def).iter().any(|a| a == "-race"));
    }

    /// Race must key the listing: the file set and the import graph both differ.
    #[test]
    fn golist_def_hash_differs_for_race() {
        let plain = def_with(false, vec![]);
        let racy = GoGolistDef {
            race: true,
            ..plain.clone()
        };
        assert_ne!(def_hash(&plain), def_hash(&racy));
    }

    /// …but adding the field must not have moved the hash for everyone else, or
    /// every cached `_golist` artifact in existence would be invalidated. The
    /// constant is the hash this def produced before `race` was introduced.
    #[test]
    fn golist_def_hash_unchanged_for_non_race() {
        assert_eq!(def_hash(&def_with(false, vec![])), NON_RACE_GOLIST_HASH);
    }

    /// Pinned pre-`race` value of `def_hash(def_with(false, vec![]))`. Update it
    /// only alongside a deliberate `GO_GOLIST_FORMAT_VERSION` bump — a change
    /// here means every cached listing is being thrown away.
    const NON_RACE_GOLIST_HASH: u64 = 642058481220411298;

    fn def_hash(def: &GoGolistDef) -> u64 {
        use std::hash::{Hash, Hasher};
        let mut h = xxhash_rust::xxh3::Xxh3Default::new();
        def.hash(&mut h);
        h.finish()
    }

    #[test]
    fn test_golist_args_keep_test_and_tags_together() {
        let args = golist_args(&def_with(true, vec!["integration".to_string()]));
        assert!(args.iter().any(|a| a == "-test"), "{args:?}");
        assert!(args.iter().any(|a| a == "-tags=integration"), "{args:?}");
        assert_eq!(args.last().map(String::as_str), Some("example.com/mylib"));
    }

    /// `with_test` changes which fields come back populated, so two otherwise
    /// identical defs must not share a cache entry.
    #[test]
    fn test_with_test_keys_the_def_hash() {
        let h = |d: &GoGolistDef| {
            let mut hasher = Xxh3Default::new();
            d.hash(&mut hasher);
            hasher.finish()
        };
        assert_ne!(
            h(&def_with(true, vec![])),
            h(&def_with(false, vec![])),
            "-test must key the golist cache"
        );
    }

    #[test]
    fn test_normalize_dir_strips_ws_prefix() {
        assert_eq!(normalize_dir("/sandbox/ws/mylib", "/sandbox/ws"), "mylib");
    }

    #[test]
    fn test_normalize_dir_equals_ws_prefix_yields_empty() {
        assert_eq!(normalize_dir("/sandbox/ws", "/sandbox/ws"), "");
    }

    #[test]
    fn test_normalize_dir_leaves_third_party_unchanged() {
        let dir = "/home/user/go/pkg/mod/github.com/foo/bar@v1.0.0";
        assert_eq!(normalize_dir(dir, "/sandbox/ws"), dir);
    }

    #[test]
    fn test_normalize_pkg_paths_drops_absolute_module_dir() {
        // Module.Dir is an absolute per-machine path; dropping it keeps
        // package.bin byte-identical across sandboxes/machines.
        let mut pkg = GoPackage {
            import_path: "example.com/m/lib".to_string(),
            dir: Some("/sandbox/ws/lib".to_string()),
            module: Some(GoModule {
                path: "example.com/m".to_string(),
                version: None,
                dir: Some("/sandbox/ws".to_string()),
            }),
            ..Default::default()
        };
        normalize_pkg_paths(&mut pkg, "/sandbox/ws");
        assert_eq!(pkg.dir.as_deref(), Some("lib"));
        let m = pkg.module.expect("module retained");
        assert_eq!(m.path, "example.com/m", "Module.Path must survive");
        assert_eq!(m.dir, None, "absolute Module.Dir must be dropped");
    }
}
