use crate::plugingo::pkg_analysis::{
    GoPackage, encode_go_package, encode_package_addrs, resolve_package_addrs,
};
use anyhow::Context;
use async_trait::async_trait;
use hcore::debug_hash::DebugHasher;
use hcore::hasync::Cancellable;
use hcore::htvalue::signature::ParamType;
use hdriver_support::driver_managed::{ManagedDriver, ManagedRunRequest, ManagedRunResponse};
use hplugin::driver::targetdef::path::{CodegenMode, Content, Path};
use hplugin::driver::targetdef::{CacheConfig, Input, InputMode, Output, TargetDef};
use hplugin::driver::{
    ApplyTransitiveRequest, ApplyTransitiveResponse, ConfigRequest, ConfigResponse, ParseRequest,
    ParseResponse, TargetAddr,
};
use hplugin::htspec::Spec;
use hproc::proc_exec;
use std::collections::HashMap;
use std::ffi::OsString;
use std::hash::{Hash, Hasher};
use std::sync::Arc;
use xxhash_rust::xxh3::Xxh3Default;

pub struct GoGolistDriver;

/// Config for a `go_golist` target (engine-generated by the Go provider).
/// `#[derive(Spec)]` provides the parser and the LSP schema. The hermetic Go SDK
/// arrives as a normal dep (group `gosdk`); the driver derives GOROOT and the
/// `go` binary from its staged path — nothing is read from the host.
#[derive(Spec)]
struct GoGolistSpec {
    /// Go import path of the package to analyze.
    #[spec(required)]
    import_path: String,
    /// Target GOOS.
    #[spec(required)]
    goos: String,
    /// Target GOARCH.
    #[spec(required)]
    goarch: String,
    /// Go release whose staged hermetic SDK provides GOROOT + the `go` binary.
    #[spec(required)]
    go_version: String,
    /// Go build tags.
    build_tags: Vec<String>,
    /// For thirdparty packages: the `download` target whose filtered outputs are
    /// staged into consumers' sandboxes.
    #[spec(ty = ParamType::String)]
    thirdparty_download_addr: Option<String>,
    /// Source/mod dependencies, grouped by name → list of target addresses.
    deps: HashMap<String, Vec<String>>,
    /// Declared outputs, grouped by name → list of output paths.
    out: HashMap<String, Vec<String>>,
}

impl GoGolistDriver {
    pub fn new() -> Self {
        Self
    }
}

impl Default for GoGolistDriver {
    fn default() -> Self {
        Self::new()
    }
}

#[derive(Clone, serde::Serialize, serde::Deserialize)]
struct GoGolistDef {
    import_path: String,
    goos: String,
    goarch: String,
    go_version: String,
    build_tags: Vec<String>,
    dep_inputs: Vec<Input>,
    /// For thirdparty packages: the `download` target whose filtered outputs
    /// will be staged into consumers' sandboxes. Threaded through so
    /// `resolve_package_addrs` emits download-filter refs instead of pluginfs
    /// file refs for per-file addresses.
    thirdparty_download_addr: Option<String>,
}

/// Bump to invalidate every cached `_golist` artifact whenever the driver's
/// output format (package.bin layout, package_addrs.bin schema, …) changes.
const GO_GOLIST_FORMAT_VERSION: u32 = 13;

impl Hash for GoGolistDef {
    fn hash<H: Hasher>(&self, state: &mut H) {
        GO_GOLIST_FORMAT_VERSION.hash(state);
        self.import_path.hash(state);
        self.goos.hash(state);
        self.goarch.hash(state);
        self.go_version.hash(state);
        self.build_tags.hash(state);
        self.dep_inputs.hash(state);
        self.thirdparty_download_addr.hash(state);
        // The hermetic SDK arrives via dep_inputs (group `gosdk`); the engine
        // hashes its content, so no separate goroot/go_bin field is hashed here.
    }
}

#[async_trait]
impl ManagedDriver for GoGolistDriver {
    fn config(&self, _req: ConfigRequest) -> anyhow::Result<ConfigResponse> {
        Ok(ConfigResponse {
            name: "go_golist".to_string(),
        })
    }

    fn schema(&self) -> hplugin::driver::DriverSchema {
        GoGolistSpec::schema()
    }

    async fn parse(
        &self,
        req: ParseRequest,
        _ctoken: &(dyn Cancellable + Send + Sync),
    ) -> anyhow::Result<ParseResponse> {
        let pkg = req.target_spec.addr.package.clone();
        let pkg_str = pkg.as_str();

        let spec =
            GoGolistSpec::from(req.target_spec.config.clone()).context("parse go_golist config")?;

        // Parse deps (srcfiles, modfiles) — no go_bin here
        let dep_strings = spec.deps;

        let mut dep_groups: Vec<&String> = dep_strings.keys().collect();
        dep_groups.sort();
        let mut dep_inputs: Vec<Input> = Vec::new();
        for group in dep_groups {
            let addrs = dep_strings.get(group).expect("group key from same map");
            // The hermetic SDK (group `gosdk`) is read-only and identical across
            // every golist target — stage it once and hardlink it into each
            // sandbox instead of byte-copying the whole tree (incl. ~150 MB of
            // std `src/`) per package. Source deps keep the source-map
            // annotation so golist can map codegen output back to its target.
            let is_sdk = group.as_str() == crate::plugingo::addr_util::GO_SDK_DEP_GROUP;
            let annotations = if is_sdk {
                std::collections::BTreeMap::from([(
                    hdriver_support::stage::READ_ONLY_ANNOTATION.to_string(),
                    "true".to_string(),
                )])
            } else {
                std::collections::BTreeMap::from([(
                    hdriver_support::driver_managed::SOURCE_MAP_ANNOTATION.to_string(),
                    "true".to_string(),
                )])
            };
            for (i, addr_str) in addrs.iter().enumerate() {
                dep_inputs.push(Input {
                    r#ref: TargetAddr::parse(addr_str, &pkg)
                        .with_context(|| format!("parse dep addr {addr_str}"))?,
                    mode: InputMode::Standard,
                    origin_id: format!("dep|{group}|{i}"),
                    annotations: annotations.clone(),
                    hashed: true,
                    runtime: true,
                });
            }
        }

        let def = GoGolistDef {
            import_path: spec.import_path,
            goos: spec.goos,
            goarch: spec.goarch,
            go_version: spec.go_version,
            build_tags: spec.build_tags,
            dep_inputs: dep_inputs.clone(),
            thirdparty_download_addr: spec.thirdparty_download_addr,
        };

        let hash = {
            let mut h = DebugHasher::new(Xxh3Default::new(), || {
                format!("go_golist_{}", req.target_spec.addr.format())
            });
            def.hash(&mut h);
            format!("{:x}", h.finish()).into_bytes()
        };

        // Parse outputs from spec, prepend package path
        let outputs = spec
            .out
            .iter()
            .map(|(group, paths)| Output {
                group: group.clone(),
                paths: paths
                    .iter()
                    .map(|p| {
                        let full_path = if pkg_str.is_empty() {
                            p.clone()
                        } else {
                            format!("{pkg_str}/{p}")
                        };
                        Path {
                            content: Content::FilePath(full_path),
                            codegen_tree: CodegenMode::None,
                            collect: true,
                        }
                    })
                    .collect(),
            })
            .collect();

        Ok(ParseResponse {
            target_def: TargetDef {
                addr: req.target_spec.addr.clone(),
                labels: req.target_spec.labels.clone(),
                raw_def: Arc::new(def),
                inputs: dep_inputs,
                outputs,
                support_files: vec![],
                cache: CacheConfig::on(true),
                pty: false,
                hash,
                transparent: false,
            },
        })
    }

    async fn apply_transitive(
        &self,
        req: ApplyTransitiveRequest,
        _ctoken: &(dyn Cancellable + Send + Sync),
    ) -> anyhow::Result<ApplyTransitiveResponse> {
        Ok(ApplyTransitiveResponse {
            target_def: req.target_def,
        })
    }

    async fn run<'a, 'io>(
        &self,
        req: ManagedRunRequest<'a, 'io>,
        ctoken: &(dyn Cancellable + Send + Sync),
    ) -> anyhow::Result<ManagedRunResponse> {
        let def = req.request.target.def_de::<GoGolistDef>();

        // GOROOT and the `go` binary come from either the hermetic SDK staged
        // into this sandbox by the `gosdk` dep, or — when the provider selects
        // `gotool = "host"` — the host `go` resolved from this process's PATH.
        let host = crate::plugingo::toolchain::is_host(&def.go_version);
        let (goroot, go_bin) = if host {
            let go_bin = resolve_host_go()?;
            let goroot = host_goroot(&go_bin)?;
            (goroot, go_bin)
        } else {
            let goroot = req
                .sandbox_ws_dir
                .join(crate::plugingo::toolchain::staged_goroot(&def.go_version));
            let go_bin = goroot.join("bin").join("go");
            if !go_bin.exists() {
                anyhow::bail!(
                    "go_golist: hermetic go binary missing at {go_bin:?} (gosdk dep not staged?)"
                );
            }
            (goroot, go_bin)
        };
        // Sandbox-local build cache so `go list` neither reads nor writes the
        // host GOCACHE.
        let gocache = req.sandbox_pkg_dir.join(".heph-gocache");
        std::fs::create_dir_all(&gocache)
            .with_context(|| format!("create gocache dir {gocache:?}"))?;

        let mut env: HashMap<String, String> = HashMap::new();
        env.insert("GOOS".to_string(), def.goos.clone());
        env.insert("GOARCH".to_string(), def.goarch.clone());
        env.insert("GOROOT".to_string(), goroot.to_string_lossy().into_owned());
        env.insert(
            "GOCACHE".to_string(),
            gocache.to_string_lossy().into_owned(),
        );
        // Pin the toolchain to the staged SDK and ignore any workspace go.work so
        // resolution is reproducible regardless of host config.
        env.insert("GOTOOLCHAIN".to_string(), "local".to_string());
        env.insert("GOWORK".to_string(), "off".to_string());
        // Pin CGO_ENABLED=0 to keep this list call's view of transitive deps
        // consistent with the bash-driven compile/link sandboxes. Letting Go
        // autodetect produces drift across hosts (PATH-dependent) — e.g. an
        // Ubuntu host with gcc on PATH pulls runtime/cgo here but later link
        // steps run without it, breaking importcfg.
        env.insert("CGO_ENABLED".to_string(), "0".to_string());
        // Thirdparty module *metadata* listing still consults the host module
        // cache / proxy (modules are content-addressed and verified by go.sum),
        // matching the v1 plugin; first-party and stdlib reads stay fully
        // hermetic via the staged SDK above.
        for name in &[
            "GOPATH",
            "GOMODCACHE",
            "HOME",
            "GONOSUMDB",
            "GOFLAGS",
            "GOPRIVATE",
            "GOPROXY",
        ] {
            if let Ok(v) = std::env::var(name) {
                env.insert(name.to_string(), v);
            }
        }
        // Host toolchain: the `go` subprocess may need PATH (e.g. to locate
        // ancillary tools). Hermetic mode deliberately omits it to stay
        // PATH-independent.
        if host && let Ok(v) = std::env::var("PATH") {
            env.insert("PATH".to_string(), v);
        }

        let mut cmd_args = vec![
            "list".to_string(),
            "-json=Dir,ImportPath,Name,GoFiles,SFiles,HFiles,TestGoFiles,XTestGoFiles,EmbedPatterns,EmbedFiles,TestEmbedPatterns,TestEmbedFiles,XTestEmbedPatterns,XTestEmbedFiles,Imports,TestImports,XTestImports,Standard,Module,Match,Incomplete,Error".to_string(),
            "-e".to_string(),
            // -test populates TestEmbedFiles / XTestEmbedFiles (and resolves test
            // imports). Without it go list reports test embed patterns but never
            // resolves them, so the test embedcfg path globs against an empty
            // staged-file set. The flag also adds synthetic `pkg.test` / `pkg
            // [pkg.test]` / `pkg_test [pkg.test]` entries — we discard them
            // below and keep only the plain `pkg` entry.
            "-test".to_string(),
        ];

        if !def.build_tags.is_empty() {
            cmd_args.push(format!("-tags={}", def.build_tags.join(",")));
        }

        cmd_args.push(def.import_path.clone());

        let args: Vec<OsString> = cmd_args.iter().map(OsString::from).collect();
        let env_pairs: Vec<(OsString, OsString)> = env
            .iter()
            .map(|(k, v)| (OsString::from(k), OsString::from(v)))
            .collect();

        // setsid=false: `go list` is single-process; the supervisor's
        // direct-pid kill is sufficient on hard-shutdown.
        let spec = proc_exec::Spec {
            program: go_bin.clone(),
            args,
            env: env_pairs,
            cwd: req.sandbox_pkg_dir.clone(),
            stdin: proc_exec::StdioSpec::Null,
            stdout: proc_exec::StdioSpec::Piped,
            stderr: proc_exec::StdioSpec::Piped,
            setsid: false,
            ctty: false,
        };

        let output = proc_exec::output(spec, ctoken)
            .await
            .with_context(|| format!("wait for go list for {}", def.import_path))?;

        if !output.status.success() {
            let stderr = String::from_utf8_lossy(&output.stderr);
            return Err(crate::plugingo::errors::GoListError {
                import_path: def.import_path.clone(),
                stderr_tail: hplugin::error::last_n_lines(&stderr, 10),
            }
            .into());
        }

        // Parse once, normalize Dir on the struct, then serialize package.bin and
        // reuse the same value for addr resolution below.
        //
        // `-test` makes go list emit synthetic variants (`pkg.test`, `pkg [pkg.test]`,
        // `pkg_test [pkg.test]`); we keep only the canonical entry whose ImportPath
        // matches the request — that one has the resolved TestEmbedFiles /
        // XTestEmbedFiles we actually need downstream.
        let ws_prefix = req.sandbox_ws_dir.to_string_lossy();
        let mut pkgs: Vec<GoPackage> = serde_json::Deserializer::from_slice(&output.stdout)
            .into_iter::<GoPackage>()
            .collect::<Result<_, _>>()
            .context("parse go list output")?;
        pkgs.retain(|p| p.import_path == def.import_path);
        for p in &mut pkgs {
            normalize_pkg_paths(p, &ws_prefix);
        }

        let pkg = pkgs.into_iter().next().ok_or_else(|| {
            anyhow::anyhow!("go list returned no entry matching {}", def.import_path)
        })?;

        let package_bin = encode_go_package(&pkg).context("encode package.bin")?;
        std::fs::write(req.sandbox_pkg_dir.join("package.bin"), &package_bin)
            .context("write package.bin")?;

        let source_map_path = req.sandbox_pkg_dir.join("source_map.json");
        let source_map: HashMap<String, String> = if source_map_path.exists() {
            let raw = std::fs::read_to_string(&source_map_path)
                .with_context(|| format!("read {source_map_path:?}"))?;
            serde_json::from_str(&raw).with_context(|| "parse source_map.json")?
        } else {
            HashMap::new()
        };

        let pkg_str = req.request.target.addr.package.as_str();
        let download_addr = match &def.thirdparty_download_addr {
            Some(s) => Some(
                hplugin::driver::TargetAddr::parse(s, &hmodel::htpkg::PkgBuf::from(""))
                    .with_context(|| format!("parse thirdparty_download_addr {s:?}"))?
                    .r#ref,
            ),
            None => None,
        };
        let mut addrs = resolve_package_addrs(&pkg, pkg_str, &source_map, download_addr.as_ref());

        // circl-style asm `#include`s reach into sibling packages of the same
        // module (`dh/x448` → `../../math/fp448/fp_amd64.h`). Those headers
        // aren't in this package's HFiles, so scan the asm sources and stage the
        // siblings via the module-root download target at their module-relative
        // path — the path the `-I .` asm step resolves them against.
        if let (Some(dl), false) = (download_addr.as_ref(), pkg.s_files.is_empty())
            && let Some(pkg_dir) = pkg.dir.as_deref()
        {
            let module_ws_root = dl.package.as_str();
            let subpath = pkg_str
                .strip_prefix(module_ws_root)
                .map(|s| s.trim_start_matches('/'))
                .unwrap_or("");
            addrs.extra_h_files = crate::plugingo::pkg_analysis::collect_cross_pkg_asm_headers(
                pkg_dir,
                subpath,
                &pkg.s_files,
            )
            .into_iter()
            .map(|rel| {
                TargetAddr {
                    r#ref: dl.clone(),
                    output: None,
                    filters: vec![format!("{module_ws_root}/{rel}")],
                }
                .to_string()
            })
            .collect();
        }

        let addrs_bin = encode_package_addrs(&addrs).context("encode package_addrs.bin")?;
        std::fs::write(req.sandbox_pkg_dir.join("package_addrs.bin"), &addrs_bin)
            .context("write package_addrs.bin")?;

        Ok(ManagedRunResponse { artifacts: vec![] })
    }
}

/// Strip every absolute path out of a `go list` package so the cached
/// `package.bin` is byte-identical across machines (and sandboxes). go reports
/// absolute paths in two places:
/// - `Dir`: rewritten repo-root-relative (it lives under the sandbox ws).
/// - `Module.Dir`: an absolute sandbox-ws path (first-party) or host
///   GOMODCACHE path (thirdparty). Nothing downstream reads it — only
///   `Module.Path` matters — so it's dropped. Left in, its per-machine
///   absolute value would make this output (and every consumer's hashin)
///   differ across machines, defeating the cache.
fn normalize_pkg_paths(p: &mut GoPackage, ws_prefix: &str) {
    if let Some(dir) = &p.dir {
        p.dir = Some(normalize_dir(dir, ws_prefix));
    }
    if let Some(m) = &mut p.module {
        m.dir = None;
    }
}

/// Strip `ws_prefix/` from a go list `Dir` path so it becomes repo-root-relative.
fn normalize_dir(dir: &str, ws_prefix: &str) -> String {
    let prefix_slash = format!("{ws_prefix}/");
    if let Some(rel) = dir.strip_prefix(&prefix_slash) {
        rel.to_string()
    } else if dir == ws_prefix {
        String::new()
    } else {
        dir.to_string()
    }
}

/// Resolve the host `go` binary from this process's `PATH` — used for
/// `go list` when the provider selects `gotool = "host"`.
fn resolve_host_go() -> anyhow::Result<std::path::PathBuf> {
    let path = std::env::var_os("PATH")
        .ok_or_else(|| anyhow::anyhow!("go_golist host toolchain: PATH not set"))?;
    for dir in std::env::split_paths(&path) {
        let cand = dir.join("go");
        if std::fs::metadata(&cand)
            .map(|m| m.is_file())
            .unwrap_or(false)
        {
            return Ok(cand);
        }
    }
    anyhow::bail!("go_golist host toolchain: `go` not found on PATH")
}

/// Query `GOROOT` from the host `go` binary.
fn host_goroot(go_bin: &std::path::Path) -> anyhow::Result<std::path::PathBuf> {
    let out = std::process::Command::new(go_bin)
        .args(["env", "GOROOT"])
        .output()
        .with_context(|| format!("run {go_bin:?} env GOROOT"))?;
    if !out.status.success() {
        anyhow::bail!(
            "`{go_bin:?} env GOROOT` failed: {}",
            String::from_utf8_lossy(&out.stderr)
        );
    }
    let goroot = String::from_utf8(out.stdout)
        .context("go env GOROOT output is not utf8")?
        .trim()
        .to_string();
    if goroot.is_empty() {
        anyhow::bail!("`{go_bin:?} env GOROOT` returned empty");
    }
    Ok(std::path::PathBuf::from(goroot))
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::plugingo::pkg_analysis::GoModule;
    use hmodel::htpkg::PkgBuf;

    fn driver() -> GoGolistDriver {
        GoGolistDriver::new()
    }

    fn make_parse_request(
        pkg: &str,
        import_path: &str,
        extra_deps: Vec<(&str, Vec<&str>)>,
    ) -> ParseRequest {
        use hcore::htvalue::Value;
        use hmodel::htaddr::Addr;
        use hplugin::provider::TargetSpec;
        use std::collections::HashMap;

        let mut config: HashMap<String, Value> = HashMap::new();
        config.insert(
            "import_path".to_string(),
            Value::String(import_path.to_string()),
        );
        config.insert("goos".to_string(), Value::String("linux".to_string()));
        config.insert("goarch".to_string(), Value::String("amd64".to_string()));
        config.insert(
            "go_version".to_string(),
            Value::String(crate::plugingo::toolchain::DEFAULT_GO_VERSION.to_string()),
        );
        config.insert(
            "out".to_string(),
            Value::Map(HashMap::from([
                (
                    "pkg".to_string(),
                    Value::List(vec![Value::String("package.bin".to_string())]),
                ),
                (
                    "addrs".to_string(),
                    Value::List(vec![Value::String("package_addrs.bin".to_string())]),
                ),
            ])),
        );

        if !extra_deps.is_empty() {
            let deps_map: HashMap<String, Value> = extra_deps
                .into_iter()
                .map(|(k, vs)| {
                    (
                        k.to_string(),
                        Value::List(
                            vs.into_iter()
                                .map(|v| Value::String(v.to_string()))
                                .collect(),
                        ),
                    )
                })
                .collect();
            config.insert("deps".to_string(), Value::Map(deps_map));
        }

        ParseRequest {
            request_id: "test".to_string(),
            target_spec: std::sync::Arc::new(TargetSpec {
                addr: Addr::new(PkgBuf::from(pkg), "_golist".to_string(), Default::default()),
                driver: "go_golist".to_string(),
                config,
                labels: vec![],
                transitive: Default::default(),
            }),
        }
    }

    fn noop_ctoken() -> hcore::hasync::StdCancellationToken {
        hcore::hasync::StdCancellationToken::new()
    }

    #[tokio::test]
    async fn test_driver_name_is_go_golist() {
        let resp = driver().config(ConfigRequest {}).unwrap();
        assert_eq!(resp.name, "go_golist");
    }

    #[tokio::test]
    async fn test_parse_missing_import_path_errors() {
        use hmodel::htaddr::Addr;
        use hplugin::provider::TargetSpec;
        use std::collections::HashMap;

        let ct = noop_ctoken();
        let req = ParseRequest {
            request_id: "test".to_string(),
            target_spec: std::sync::Arc::new(TargetSpec {
                addr: Addr::new(
                    PkgBuf::from("mylib"),
                    "_golist".to_string(),
                    Default::default(),
                ),
                driver: "go_golist".to_string(),
                config: HashMap::new(),
                labels: vec![],
                transitive: Default::default(),
            }),
        };
        assert!(driver().parse(req, &ct).await.is_err());
    }

    #[tokio::test]
    async fn test_parse_has_no_host_go_tool_input() {
        // The hermetic SDK arrives as a normal dep (group `gosdk`), staged by the
        // engine; the driver must not pull a host `go` binary as a Tool input.
        let ct = noop_ctoken();
        let req = make_parse_request(
            "mylib",
            "example.com/mylib",
            vec![("gosdk", vec!["//@heph/go/toolchain:go"])],
        );
        let resp = driver().parse(req, &ct).await.unwrap();
        assert!(
            !resp
                .target_def
                .inputs
                .iter()
                .any(|i| i.mode == InputMode::Tool),
            "golist must declare no Tool inputs (SDK is a dep)"
        );
        assert!(
            resp.target_def
                .inputs
                .iter()
                .any(|i| i.origin_id == "dep|gosdk|0"),
            "the hermetic SDK dep must flow through as a Standard input"
        );
    }

    #[tokio::test]
    async fn test_parse_gosdk_dep_is_read_only_but_sources_are_not() {
        // The SDK dep is identical across every golist target — mark it
        // read-only so the OS runner stages it once and hardlinks it in rather
        // than byte-copying the whole tree per package. Source deps stay on the
        // copy path (they carry the source-map annotation instead).
        let ct = noop_ctoken();
        let req = make_parse_request(
            "mylib",
            "example.com/mylib",
            vec![
                ("gosdk", vec!["//@heph/go/toolchain:go"]),
                ("srcfiles", vec!["//mylib:_go_src"]),
            ],
        );
        let resp = driver().parse(req, &ct).await.unwrap();
        let inputs = &resp.target_def.inputs;

        let sdk = inputs
            .iter()
            .find(|i| i.origin_id == "dep|gosdk|0")
            .expect("gosdk input present");
        assert_eq!(
            sdk.annotations
                .get(hdriver_support::stage::READ_ONLY_ANNOTATION)
                .map(String::as_str),
            Some("true"),
            "gosdk dep must be staged read-only"
        );

        let src = inputs
            .iter()
            .find(|i| i.origin_id == "dep|srcfiles|0")
            .expect("srcfiles input present");
        assert!(
            !src.annotations
                .contains_key(hdriver_support::stage::READ_ONLY_ANNOTATION),
            "source deps must not be read-only staged"
        );
    }

    #[tokio::test]
    async fn test_parse_dep_inputs_present() {
        let ct = noop_ctoken();
        let req = make_parse_request(
            "mylib",
            "example.com/mylib",
            vec![
                ("modfiles", vec!["//go.mod:_go_mod"]),
                ("srcfiles", vec!["//mylib:_go_src"]),
            ],
        );
        let resp = driver().parse(req, &ct).await.unwrap();
        let inputs = &resp.target_def.inputs;
        assert!(inputs.iter().any(|i| i.origin_id == "dep|modfiles|0"));
        assert!(inputs.iter().any(|i| i.origin_id == "dep|srcfiles|0"));
    }

    // Regression: dep groups came from a HashMap, so dep_inputs Vec order varied
    // across runs, making def.hash unstable and breaking the local cache for
    // go_golist targets. Order must now be sorted by group name.
    #[tokio::test]
    async fn test_parse_dep_inputs_order_is_deterministic() {
        let ct = noop_ctoken();
        let mk = || {
            make_parse_request(
                "mylib",
                "example.com/mylib",
                vec![
                    ("zsrc", vec!["//mylib:_go_src"]),
                    ("modfiles", vec!["//go.mod:_go_mod"]),
                    ("asrc", vec!["//mylib:_extra"]),
                ],
            )
        };
        let resp_a = driver().parse(mk(), &ct).await.unwrap();
        let resp_b = driver().parse(mk(), &ct).await.unwrap();

        let ids_a: Vec<&str> = resp_a
            .target_def
            .inputs
            .iter()
            .filter(|i| i.origin_id.starts_with("dep|"))
            .map(|i| i.origin_id.as_str())
            .collect();
        let ids_b: Vec<&str> = resp_b
            .target_def
            .inputs
            .iter()
            .filter(|i| i.origin_id.starts_with("dep|"))
            .map(|i| i.origin_id.as_str())
            .collect();

        assert_eq!(ids_a, ids_b, "dep input order must be stable across parses");
        // Verify it's sorted by group name (asrc < modfiles < zsrc).
        assert_eq!(ids_a, vec!["dep|asrc|0", "dep|modfiles|0", "dep|zsrc|0"]);
        assert_eq!(resp_a.target_def.hash, resp_b.target_def.hash);
    }

    #[tokio::test]
    async fn test_parse_outputs_prepend_package() {
        let ct = noop_ctoken();
        let req = make_parse_request("mylib", "example.com/mylib", vec![]);
        let resp = driver().parse(req, &ct).await.unwrap();
        let pkg_out = resp
            .target_def
            .outputs
            .iter()
            .find(|o| o.group == "pkg")
            .unwrap();
        assert!(pkg_out.paths.iter().any(|p| matches!(
            &p.content,
            Content::FilePath(s) if s == "mylib/package.bin"
        )));
    }

    #[tokio::test]
    async fn test_parse_outputs_no_prefix_for_empty_package() {
        let ct = noop_ctoken();
        let req = make_parse_request("", "example.com/mylib", vec![]);
        let resp = driver().parse(req, &ct).await.unwrap();
        let pkg_out = resp
            .target_def
            .outputs
            .iter()
            .find(|o| o.group == "pkg")
            .unwrap();
        assert!(pkg_out.paths.iter().any(|p| matches!(
            &p.content,
            Content::FilePath(s) if s == "package.bin"
        )));
    }

    #[test]
    fn test_normalize_dir_strips_ws_prefix() {
        assert_eq!(normalize_dir("/sandbox/ws/mylib", "/sandbox/ws"), "mylib");
    }

    #[test]
    fn test_normalize_dir_equals_ws_prefix_yields_empty() {
        assert_eq!(normalize_dir("/sandbox/ws", "/sandbox/ws"), "");
    }

    #[test]
    fn test_normalize_dir_leaves_third_party_unchanged() {
        let dir = "/home/user/go/pkg/mod/github.com/foo/bar@v1.0.0";
        assert_eq!(normalize_dir(dir, "/sandbox/ws"), dir);
    }

    #[test]
    fn test_normalize_pkg_paths_drops_absolute_module_dir() {
        // Module.Dir is an absolute per-machine path; dropping it keeps
        // package.bin byte-identical across sandboxes/machines.
        let mut pkg = GoPackage {
            import_path: "example.com/m/lib".to_string(),
            dir: Some("/sandbox/ws/lib".to_string()),
            module: Some(GoModule {
                path: "example.com/m".to_string(),
                version: None,
                dir: Some("/sandbox/ws".to_string()),
            }),
            ..Default::default()
        };
        normalize_pkg_paths(&mut pkg, "/sandbox/ws");
        assert_eq!(pkg.dir.as_deref(), Some("lib"));
        let m = pkg.module.expect("module retained");
        assert_eq!(m.path, "example.com/m", "Module.Path must survive");
        assert_eq!(m.dir, None, "absolute Module.Dir must be dropped");
    }
}
