use crate::plugingo::embed;
use crate::plugingo::pkg_analysis::decode_go_package;
use anyhow::Context;
use async_trait::async_trait;
use hcore::debug_hash::DebugHasher;
use hcore::hasync::Cancellable;
use hdriver_support::driver_managed::{ManagedDriver, ManagedRunRequest, ManagedRunResponse};
use hplugin::driver::targetdef::path::{CodegenMode, Content, Path};
use hplugin::driver::targetdef::{CacheConfig, Input, InputMode, Output, TargetDef};
use hplugin::driver::{
    ApplyTransitiveRequest, ApplyTransitiveResponse, ConfigRequest, ConfigResponse, ParseRequest,
    ParseResponse, TargetAddr,
};
use hplugin::htspec::{Spec, SpecEnum};
use std::collections::HashMap;
use std::hash::{Hash, Hasher};
use std::io::BufRead;
use std::sync::Arc;
use xxhash_rust::xxh3::Xxh3Default;

pub struct GoEmbedDriver;

/// Config for a `go_embed` target (engine-generated by the Go provider).
/// `#[derive(Spec)]` provides the parser and the LSP schema.
#[derive(Spec)]
struct GoEmbedSpec {
    /// Which embed set to extract: `embed`, `test_embed`, or `xtest_embed`.
    #[spec(required)]
    variant: EmbedVariant,
    /// Dependencies; must include a non-empty `golist` group.
    deps: HashMap<String, Vec<String>>,
    /// Declared outputs, grouped by name → list of output paths.
    out: HashMap<String, Vec<String>>,
}

#[derive(Clone, PartialEq, Debug, serde::Serialize, serde::Deserialize, SpecEnum)]
enum EmbedVariant {
    Embed,
    /// embed_patterns ∪ test_embed_patterns / embed_files ∪ test_embed_files —
    /// used by `build_test_lib`, which compiles GoFiles+TestGoFiles together and
    /// so must see embeds from both sides.
    TestEmbed,
    XtestEmbed,
}

impl Hash for EmbedVariant {
    fn hash<H: Hasher>(&self, state: &mut H) {
        match self {
            EmbedVariant::Embed => 0u8.hash(state),
            EmbedVariant::XtestEmbed => 1u8.hash(state),
            EmbedVariant::TestEmbed => 2u8.hash(state),
        }
    }
}

/// Bump to invalidate every cached embed cfg whenever the embed cfg layout
/// (paths, file resolution semantics) changes. v6: `go_embed_src` lane —
/// patterns now resolved against staged files, not just `go list EmbedFiles`.
const GO_EMBED_FORMAT_VERSION: u32 = 6;

#[derive(Clone, serde::Serialize, serde::Deserialize)]
struct GoEmbedDef {
    variant: EmbedVariant,
    golist_origin_id: String,
    /// Origin ids of the `go_embed_src` inputs (assets `go list` never saw).
    embed_src_origin_ids: Vec<String>,
}

impl Hash for GoEmbedDef {
    fn hash<H: Hasher>(&self, state: &mut H) {
        GO_EMBED_FORMAT_VERSION.hash(state);
        self.variant.hash(state);
        self.golist_origin_id.hash(state);
        self.embed_src_origin_ids.hash(state);
    }
}

#[async_trait]
impl ManagedDriver for GoEmbedDriver {
    fn config(&self, _req: ConfigRequest) -> anyhow::Result<ConfigResponse> {
        Ok(ConfigResponse {
            name: "go_embed".to_string(),
        })
    }

    fn schema(&self) -> hplugin::driver::DriverSchema {
        GoEmbedSpec::schema()
    }

    async fn parse(
        &self,
        req: ParseRequest,
        _ctoken: &(dyn Cancellable + Send + Sync),
    ) -> anyhow::Result<ParseResponse> {
        let pkg = req.target_spec.addr.package.clone();
        let pkg_str = pkg.as_str();

        let spec =
            GoEmbedSpec::from(req.target_spec.config.clone()).context("parse go_embed config")?;

        let golist_addrs = spec
            .deps
            .get("golist")
            .ok_or_else(|| anyhow::anyhow!("go_embed: missing deps.golist"))?;

        if golist_addrs.is_empty() {
            anyhow::bail!("go_embed: deps.golist must have at least one entry");
        }

        let golist_origin_id = "dep|golist|0".to_string();

        let mut inputs: Vec<Input> = Vec::new();
        for (i, addr_str) in golist_addrs.iter().enumerate() {
            inputs.push(Input {
                r#ref: TargetAddr::parse(addr_str, &pkg)
                    .with_context(|| format!("parse golist dep addr {addr_str}"))?,
                mode: InputMode::Standard,
                origin_id: format!("dep|golist|{i}"),
                annotations: std::collections::BTreeMap::new(),
                hashed: true,
                runtime: true,
            });
        }

        // The `go_embed_src` lane: assets `go list` never resolved (they are
        // intentionally kept out of `_golist`). Staged here so the driver can
        // re-glob them against the package's `EmbedPatterns` and reproduce Go's
        // `EmbedFiles`. Read-only + per-file: materialized once into the shared
        // stage and hardlinked file-by-file (the run step reads the list to
        // enumerate them), shared with the consumer's compile sandbox.
        let embed_src_origin_ids: Vec<String> = spec
            .deps
            .get("embed_src")
            .map(|addrs| {
                addrs
                    .iter()
                    .enumerate()
                    .map(|(i, addr_str)| {
                        let origin_id = format!("dep|embed_src|{i}");
                        inputs.push(Input {
                            r#ref: TargetAddr::parse(addr_str, &pkg)
                                .with_context(|| format!("parse embed_src dep addr {addr_str}"))?,
                            mode: InputMode::Standard,
                            origin_id: origin_id.clone(),
                            annotations: std::collections::BTreeMap::from([
                                (
                                    hdriver_support::stage::READ_ONLY_ANNOTATION.to_string(),
                                    "true".to_string(),
                                ),
                                (
                                    hdriver_support::stage::STAGE_PER_FILE_ANNOTATION.to_string(),
                                    "true".to_string(),
                                ),
                            ]),
                            hashed: true,
                            runtime: true,
                        });
                        Ok(origin_id)
                    })
                    .collect::<anyhow::Result<Vec<_>>>()
            })
            .transpose()?
            .unwrap_or_default();

        let def = GoEmbedDef {
            variant: spec.variant,
            golist_origin_id,
            embed_src_origin_ids,
        };

        // Parse outputs
        let outputs = spec
            .out
            .iter()
            .map(|(group, paths)| Output {
                group: group.clone(),
                paths: paths
                    .iter()
                    .map(|p| {
                        let full_path = if pkg_str.is_empty() {
                            p.clone()
                        } else {
                            format!("{pkg_str}/{p}")
                        };
                        Path {
                            content: Content::FilePath(full_path),
                            codegen_tree: CodegenMode::None,
                            collect: true,
                        }
                    })
                    .collect(),
            })
            .collect();

        let hash = {
            let mut h = DebugHasher::new(Xxh3Default::new(), || {
                format!("go_embed_{}", req.target_spec.addr.format())
            });
            def.hash(&mut h);
            format!("{:x}", h.finish()).into_bytes()
        };

        Ok(ParseResponse {
            target_def: TargetDef {
                addr: req.target_spec.addr.clone(),
                labels: req.target_spec.labels.clone(),
                raw_def: Arc::new(def),
                inputs,
                outputs,
                support_files: vec![],
                cache: CacheConfig::on(true),
                pty: false,
                hash,
                transparent: false,
            },
        })
    }

    async fn apply_transitive(
        &self,
        req: ApplyTransitiveRequest,
        _ctoken: &(dyn Cancellable + Send + Sync),
    ) -> anyhow::Result<ApplyTransitiveResponse> {
        Ok(ApplyTransitiveResponse {
            target_def: req.target_def,
        })
    }

    async fn run<'a, 'io>(
        &self,
        req: ManagedRunRequest<'a, 'io>,
        _ctoken: &(dyn Cancellable + Send + Sync),
    ) -> anyhow::Result<ManagedRunResponse> {
        let def = req.request.target.def_de::<GoEmbedDef>();

        // Find package.bin from the golist input
        let managed = req
            .inputs
            .iter()
            .find(|m| m.input.origin_id == def.golist_origin_id)
            .ok_or_else(|| {
                anyhow::anyhow!("go_embed: golist input {} not found", def.golist_origin_id)
            })?;

        let list_path = managed.require_list_path()?;
        let list_f = std::fs::File::open(list_path)
            .with_context(|| format!("open golist list {:?}", list_path))?;
        let pkg_bin_path = std::io::BufReader::new(list_f)
            .lines()
            .find(|l| {
                l.as_ref()
                    .is_ok_and(|s| !s.is_empty() && s.ends_with("package.bin"))
            })
            .ok_or_else(|| anyhow::anyhow!("go_embed: package.bin not found in golist input"))??;

        let pkg_bin_file =
            std::fs::File::open(&pkg_bin_path).with_context(|| "open package.bin")?;
        let pkg = decode_go_package(pkg_bin_file).context("decode package.bin")?;

        let (patterns_owned, files_owned): (Vec<String>, Vec<String>) = match &def.variant {
            EmbedVariant::Embed => (pkg.embed_patterns.clone(), pkg.embed_files.clone()),
            EmbedVariant::TestEmbed => (
                pkg.embed_patterns
                    .iter()
                    .chain(pkg.test_embed_patterns.iter())
                    .cloned()
                    .collect(),
                pkg.embed_files
                    .iter()
                    .chain(pkg.test_embed_files.iter())
                    .cloned()
                    .collect(),
            ),
            EmbedVariant::XtestEmbed => (
                pkg.xtest_embed_patterns.clone(),
                pkg.xtest_embed_files.clone(),
            ),
        };
        let patterns = &patterns_owned;

        // Enumerate the staged `go_embed_src` files (package-relative). These are
        // assets `go list` never resolved; we re-glob them against `patterns` to
        // reproduce the `EmbedFiles` Go would have produced, then union with the
        // `go_src` files `go list` did resolve.
        let embed_src_rel = if def.embed_src_origin_ids.is_empty() {
            Vec::new()
        } else {
            collect_embed_src_rel(&req, &def.embed_src_origin_ids)
                .context("enumerate staged go_embed_src files")?
        };
        let files = merge_embed_files(files_owned, patterns, &embed_src_rel);
        let files = &files;

        if patterns.is_empty() && files.is_empty() {
            // Write empty embedcfg
            std::fs::write(
                req.sandbox_pkg_dir.join("embedcfg"),
                r#"{"Patterns":{},"Files":{}}"#,
            )
            .context("write empty embedcfg")?;
            return Ok(ManagedRunResponse { artifacts: vec![] });
        }

        // Group the resolved files under each pattern. `go_src` files came from
        // Go's authoritative `EmbedFiles`; `go_embed_src` files were resolved by
        // our Go-faithful selector above. Both align with what the consumer's
        // compile sandbox stages.
        let cfg_json =
            embed::compute_embed_cfg_json(patterns, files).context("compute embedcfg")?;

        std::fs::write(req.sandbox_pkg_dir.join("embedcfg"), cfg_json).context("write embedcfg")?;

        Ok(ManagedRunResponse { artifacts: vec![] })
    }
}

/// Union Go's authoritative `EmbedFiles` (`go_src`, already resolved by
/// `go list`) with the selector's resolution of the `go_embed_src` files for
/// each pattern. Returns a sorted, deduped package-relative file list.
fn merge_embed_files(
    go_src_files: Vec<String>,
    patterns: &[String],
    embed_src_rel: &[String],
) -> Vec<String> {
    let mut files = go_src_files;
    if !embed_src_rel.is_empty() {
        for pattern in patterns {
            files.extend(embed::select_pattern_files(pattern, embed_src_rel));
        }
    }
    files.sort();
    files.dedup();
    files
}

/// Read the staged `go_embed_src` inputs' list files and return their files as
/// package-relative, `/`-separated paths — the space `//go:embed` patterns match
/// against. Read-only per-file staging records every individual file in the list.
fn collect_embed_src_rel(
    req: &ManagedRunRequest<'_, '_>,
    origin_ids: &[String],
) -> anyhow::Result<Vec<String>> {
    let mut rel: Vec<String> = Vec::new();
    for id in origin_ids {
        let managed = req
            .inputs
            .iter()
            .find(|m| m.input.origin_id == *id)
            .ok_or_else(|| anyhow::anyhow!("go_embed: embed_src input {id} not found"))?;
        let list_path = managed.require_list_path()?;
        let f = std::fs::File::open(list_path)
            .with_context(|| format!("open embed_src list {list_path:?}"))?;
        for line in std::io::BufReader::new(f).lines() {
            let line = line.context("read embed_src list line")?;
            if line.is_empty() {
                continue;
            }
            let abs = std::path::Path::new(&line);
            let r = abs.strip_prefix(&req.sandbox_pkg_dir).unwrap_or(abs);
            rel.push(r.to_string_lossy().replace('\\', "/"));
        }
    }
    Ok(rel)
}

#[cfg(test)]
mod tests {
    use super::*;
    use hcore::htvalue::Value;
    use hmodel::htaddr::Addr;
    use hmodel::htpkg::PkgBuf;
    use hplugin::provider::TargetSpec;
    use std::collections::HashMap;

    fn driver() -> GoEmbedDriver {
        GoEmbedDriver
    }

    fn noop_ctoken() -> hcore::hasync::StdCancellationToken {
        hcore::hasync::StdCancellationToken::new()
    }

    fn make_parse_request(pkg: &str, variant: &str, golist_addr: &str) -> ParseRequest {
        let mut config: HashMap<String, Value> = HashMap::new();
        config.insert("variant".to_string(), Value::String(variant.to_string()));
        config.insert(
            "deps".to_string(),
            Value::Map(HashMap::from([(
                "golist".to_string(),
                Value::List(vec![Value::String(golist_addr.to_string())]),
            )])),
        );
        config.insert(
            "out".to_string(),
            Value::Map(HashMap::from([(
                "cfg".to_string(),
                Value::List(vec![Value::String("embedcfg".to_string())]),
            )])),
        );

        ParseRequest {
            request_id: "test".to_string(),
            target_spec: std::sync::Arc::new(TargetSpec {
                addr: Addr::new(PkgBuf::from(pkg), "embed".to_string(), Default::default()),
                driver: "go_embed".to_string(),
                config,
                labels: vec![],
                transitive: Default::default(),
            }),
        }
    }

    #[test]
    fn test_merge_embed_files_unions_go_src_and_embed_src() {
        // go_src files (from go list) ∪ selector resolution of go_embed_src
        // assets against the patterns, sorted + deduped.
        let go_src = vec!["static/x.html".to_string()];
        // Plain-dir pattern `dist`: recursion skips leading-dot entries (no all:).
        let patterns = vec!["dist".to_string(), "static/x.html".to_string()];
        let embed_src = vec![
            "dist/app.js".to_string(),
            "dist/index.html".to_string(),
            "dist/.hidden".to_string(), // excluded by Go's dir-recursion rule
        ];
        let merged = merge_embed_files(go_src, &patterns, &embed_src);
        assert_eq!(
            merged,
            vec![
                "dist/app.js".to_string(),
                "dist/index.html".to_string(),
                "static/x.html".to_string(),
            ]
        );
    }

    #[test]
    fn test_merge_embed_files_no_embed_src_is_passthrough() {
        // The common case (no go_embed_src) must be byte-identical to go list's
        // EmbedFiles — pure addition, zero change for existing packages.
        let go_src = vec!["b.txt".to_string(), "a.txt".to_string()];
        let merged = merge_embed_files(go_src, &["*.txt".to_string()], &[]);
        assert_eq!(merged, vec!["a.txt".to_string(), "b.txt".to_string()]);
    }

    #[test]
    fn test_driver_name_is_go_embed() {
        let resp = driver().config(ConfigRequest {}).unwrap();
        assert_eq!(resp.name, "go_embed");
    }

    #[tokio::test]
    async fn test_parse_embed_variant() {
        let ct = noop_ctoken();
        let req = make_parse_request("mypkg", "embed", "//mypkg:_golist|pkg");
        let resp = driver().parse(req, &ct).await.unwrap();
        assert_eq!(
            resp.target_def.def::<GoEmbedDef>().variant,
            EmbedVariant::Embed
        );
    }

    #[tokio::test]
    async fn test_parse_xtest_embed_variant() {
        let ct = noop_ctoken();
        let req = make_parse_request("mypkg", "xtest_embed", "//mypkg:_golist|pkg");
        let resp = driver().parse(req, &ct).await.unwrap();
        assert_eq!(
            resp.target_def.def::<GoEmbedDef>().variant,
            EmbedVariant::XtestEmbed
        );
    }

    #[tokio::test]
    async fn test_parse_invalid_variant_errors() {
        let ct = noop_ctoken();
        let req = make_parse_request("mypkg", "invalid", "//mypkg:_golist|pkg");
        assert!(driver().parse(req, &ct).await.is_err());
    }

    #[tokio::test]
    async fn test_parse_missing_variant_errors() {
        let ct = noop_ctoken();
        let mut config: HashMap<String, Value> = HashMap::new();
        config.insert(
            "deps".to_string(),
            Value::Map(HashMap::from([(
                "golist".to_string(),
                Value::List(vec![Value::String("//mypkg:_golist|pkg".to_string())]),
            )])),
        );
        let req = ParseRequest {
            request_id: "test".to_string(),
            target_spec: std::sync::Arc::new(TargetSpec {
                addr: Addr::new(
                    PkgBuf::from("mypkg"),
                    "embed".to_string(),
                    Default::default(),
                ),
                driver: "go_embed".to_string(),
                config,
                labels: vec![],
                transitive: Default::default(),
            }),
        };
        assert!(driver().parse(req, &ct).await.is_err());
    }

    #[tokio::test]
    async fn test_parse_includes_golist_input() {
        let ct = noop_ctoken();
        let req = make_parse_request("mypkg", "embed", "//mypkg:_golist|pkg");
        let resp = driver().parse(req, &ct).await.unwrap();
        assert!(
            resp.target_def
                .inputs
                .iter()
                .any(|i| i.origin_id == "dep|golist|0"),
            "golist input must be present"
        );
    }

    #[tokio::test]
    async fn test_parse_only_stages_golist_input() {
        // The embed driver only reads package.bin from the golist input; the
        // actual embed source files belong in the consumer's deps, not here.
        let ct = noop_ctoken();
        let req = make_parse_request("mypkg", "embed", "//mypkg:_golist|pkg");
        let resp = driver().parse(req, &ct).await.unwrap();
        let non_golist: Vec<&str> = resp
            .target_def
            .inputs
            .iter()
            .map(|i| i.origin_id.as_str())
            .filter(|id| !id.starts_with("dep|golist|"))
            .collect();
        assert!(
            non_golist.is_empty(),
            "embed driver must only declare the golist input, got: {non_golist:?}"
        );
    }

    #[tokio::test]
    async fn test_parse_embed_src_inputs_are_read_only_per_file() {
        // go_embed_src assets must be staged read-only + per-file: hardlinked
        // once into the shared stage (shared with the compile sandbox) and
        // enumerable from the input list so run() can re-glob them.
        let ct = noop_ctoken();
        let mut config: HashMap<String, Value> = HashMap::new();
        config.insert("variant".to_string(), Value::String("embed".to_string()));
        config.insert(
            "deps".to_string(),
            Value::Map(HashMap::from([
                (
                    "golist".to_string(),
                    Value::List(vec![Value::String("//mypkg:_golist|pkg".to_string())]),
                ),
                (
                    "embed_src".to_string(),
                    Value::List(vec![Value::String("//mypkg:frontend".to_string())]),
                ),
            ])),
        );
        config.insert(
            "out".to_string(),
            Value::Map(HashMap::from([(
                "cfg".to_string(),
                Value::List(vec![Value::String("embedcfg".to_string())]),
            )])),
        );
        let req = ParseRequest {
            request_id: "test".to_string(),
            target_spec: std::sync::Arc::new(TargetSpec {
                addr: Addr::new(
                    PkgBuf::from("mypkg"),
                    "embed".to_string(),
                    Default::default(),
                ),
                driver: "go_embed".to_string(),
                config,
                labels: vec![],
                transitive: Default::default(),
            }),
        };
        let resp = driver().parse(req, &ct).await.unwrap();
        let es = resp
            .target_def
            .inputs
            .iter()
            .find(|i| i.origin_id == "dep|embed_src|0")
            .expect("embed_src input present");
        assert_eq!(
            es.annotations
                .get(hdriver_support::stage::READ_ONLY_ANNOTATION)
                .map(String::as_str),
            Some("true"),
            "embed_src must be read-only"
        );
        assert_eq!(
            es.annotations
                .get(hdriver_support::stage::STAGE_PER_FILE_ANNOTATION)
                .map(String::as_str),
            Some("true"),
            "embed_src must be staged per-file"
        );
        assert_eq!(
            resp.target_def.def::<GoEmbedDef>().embed_src_origin_ids,
            vec!["dep|embed_src|0".to_string()]
        );
    }

    #[tokio::test]
    async fn test_parse_out_prepends_package() {
        let ct = noop_ctoken();
        let req = make_parse_request("mypkg", "embed", "//mypkg:_golist|pkg");
        let resp = driver().parse(req, &ct).await.unwrap();
        let cfg_out = resp
            .target_def
            .outputs
            .iter()
            .find(|o| o.group == "cfg")
            .unwrap();
        assert!(cfg_out.paths.iter().any(|p| matches!(
            &p.content,
            Content::FilePath(s) if s == "mypkg/embedcfg"
        )));
    }

    #[tokio::test]
    async fn test_parse_no_host_src_dir_in_def() {
        let ct = noop_ctoken();
        let req = make_parse_request("mypkg", "embed", "//mypkg:_golist|pkg");
        let resp = driver().parse(req, &ct).await.unwrap();
        // Verify GoEmbedDef has no host path — only variant + origin_id
        let def = resp.target_def.def::<GoEmbedDef>();
        assert_eq!(def.golist_origin_id, "dep|golist|0");
    }
}
