//! `go_compile` — the single driver that compiles a Go package archive.
//!
//! Replaces the former `sh`-scripted compile *and* the separate `go_embed`
//! target: importcfg generation, `//go:embed` resolution, the asm/symabis/pack
//! pipeline, and `go tool compile` all happen in one target. Folding embed into
//! the compile means embed assets are staged once (here), not also into a
//! separate `go_embed` sandbox — and the `go_embed_src` lane (assets kept out of
//! `_golist`) is resolved in-process against the staged files with the
//! Go-faithful selector in [`crate::plugingo::embed`].
//!
//! Mirrors the exact flag set the old scripts used (`-p`, `-trimpath`, `-pack`,
//! `-shared`, `-symabis`, `-asmhdr`, `-embedcfg`) so archives stay
//! byte-compatible.

use crate::plugingo::embed;
use crate::plugingo::pkg_analysis::decode_go_package;
use anyhow::Context;
use async_trait::async_trait;
use hcore::debug_hash::DebugHasher;
use hcore::hasync::Cancellable;
use hdriver_support::driver_managed::{ManagedDriver, ManagedRunRequest, ManagedRunResponse};
use hplugin::driver::targetdef::path::{CodegenMode, Content, Path};
use hplugin::driver::targetdef::{CacheConfig, Input, InputMode, Output, TargetDef};
use hplugin::driver::{
    ApplyTransitiveRequest, ApplyTransitiveResponse, ConfigRequest, ConfigResponse, ParseRequest,
    ParseResponse, TargetAddr,
};
use hplugin::htspec::Spec;
use hproc::proc_exec;
use std::collections::BTreeMap;
use std::collections::HashMap;
use std::ffi::OsString;
use std::hash::{Hash, Hasher};
use std::io::BufRead;
use std::sync::Arc;
use xxhash_rust::xxh3::Xxh3Default;

pub struct GoCompileDriver;

impl GoCompileDriver {
    pub fn new() -> Self {
        Self
    }
}

impl Default for GoCompileDriver {
    fn default() -> Self {
        Self::new()
    }
}

/// Which embed set to resolve, matching the variants the old `go_embed` target
/// exposed. `None`-equivalent (no embedcfg) is encoded by leaving
/// `embed_variant` empty in the spec.
#[derive(Clone, Copy, PartialEq, Debug, serde::Serialize, serde::Deserialize)]
pub enum EmbedVariant {
    Embed,
    /// embed ∪ test — `build_test_lib` compiles GoFiles+TestGoFiles together.
    TestEmbed,
    XtestEmbed,
}

impl EmbedVariant {
    fn parse(s: &str) -> Option<Self> {
        match s {
            "embed" => Some(Self::Embed),
            "test_embed" => Some(Self::TestEmbed),
            "xtest_embed" => Some(Self::XtestEmbed),
            _ => None,
        }
    }
    fn hash_tag(self) -> u8 {
        match self {
            Self::Embed => 0,
            Self::TestEmbed => 1,
            Self::XtestEmbed => 2,
        }
    }
}

/// Config for a `go_compile` target (engine-generated by the Go provider).
#[derive(Spec)]
struct GoCompileSpec {
    /// `-p` flag: `main` for main packages, else the import path.
    #[spec(required)]
    p_flag: String,
    /// Output archive filename (package-relative).
    #[spec(required)]
    out_file: String,
    /// Target GOOS.
    #[spec(required)]
    goos: String,
    /// Target GOARCH.
    #[spec(required)]
    goarch: String,
    /// Go release whose staged hermetic SDK provides GOROOT + the `go` binary.
    #[spec(required)]
    go_version: String,
    /// Import paths of the transitive libs, in deterministic order — each maps to
    /// a `lib_<sanitized>` dep group carrying that archive, used to build
    /// importcfg.
    import_paths: Vec<String>,
    /// `.s` assembly source names (package-relative). Empty → no asm pipeline.
    s_files: Vec<String>,
    /// Which embed set to resolve (`embed`/`test_embed`/`xtest_embed`), or empty
    /// for no embedcfg.
    embed_variant: Vec<String>,
    /// Dependencies, grouped by name → list of target addresses.
    deps: HashMap<String, Vec<String>>,
    /// Declared outputs, grouped by name → list of output paths.
    out: HashMap<String, Vec<String>>,
}

#[derive(Clone, serde::Serialize, serde::Deserialize)]
struct GoCompileDef {
    p_flag: String,
    out_file: String,
    goos: String,
    goarch: String,
    go_version: String,
    import_paths: Vec<String>,
    s_files: Vec<String>,
    embed_variant: Option<EmbedVariant>,
    /// origin_id of the `golist|pkg` input (present iff embed_variant is set).
    golist_origin_id: Option<String>,
    /// origin_ids of the `go_embed_src` inputs (assets `go list` never saw).
    embed_src_origin_ids: Vec<String>,
}

/// Bump to invalidate every cached `go_compile` archive whenever the compile
/// command shape or embed resolution semantics change.
const GO_COMPILE_FORMAT_VERSION: u32 = 1;

impl Hash for GoCompileDef {
    fn hash<H: Hasher>(&self, state: &mut H) {
        GO_COMPILE_FORMAT_VERSION.hash(state);
        self.p_flag.hash(state);
        self.out_file.hash(state);
        self.goos.hash(state);
        self.goarch.hash(state);
        self.go_version.hash(state);
        self.import_paths.hash(state);
        self.s_files.hash(state);
        self.embed_variant.map(|v| v.hash_tag()).hash(state);
        self.golist_origin_id.hash(state);
        self.embed_src_origin_ids.hash(state);
        // Archives, sources, SDK arrive via inputs; the engine hashes their
        // content, so no per-file hashing here.
    }
}

#[async_trait]
impl ManagedDriver for GoCompileDriver {
    fn config(&self, _req: ConfigRequest) -> anyhow::Result<ConfigResponse> {
        Ok(ConfigResponse {
            name: "go_compile".to_string(),
        })
    }

    fn schema(&self) -> hplugin::driver::DriverSchema {
        GoCompileSpec::schema()
    }

    async fn parse(
        &self,
        req: ParseRequest,
        _ctoken: &(dyn Cancellable + Send + Sync),
    ) -> anyhow::Result<ParseResponse> {
        let pkg = req.target_spec.addr.package.clone();
        let pkg_str = pkg.as_str();
        let spec = GoCompileSpec::from(req.target_spec.config.clone())
            .context("parse go_compile config")?;

        let mut inputs: Vec<Input> = Vec::new();
        let mut golist_origin_id: Option<String> = None;
        let mut embed_src_origin_ids: Vec<String> = Vec::new();

        let mut groups: Vec<&String> = spec.deps.keys().collect();
        groups.sort();
        for group in groups {
            let addrs = spec.deps.get(group).expect("group key from same map");
            let is_sdk = group.as_str() == crate::plugingo::addr_util::GO_SDK_DEP_GROUP;
            let is_embed_src = group.as_str() == "embed_src";
            // SDK and embed assets are read-only: staged once into the shared
            // stage and hardlinked in. embed_src also goes per-file so the run
            // step can enumerate it from the list.
            let annotations = if is_sdk {
                BTreeMap::from([(
                    hdriver_support::stage::READ_ONLY_ANNOTATION.to_string(),
                    "true".to_string(),
                )])
            } else if is_embed_src {
                BTreeMap::from([
                    (
                        hdriver_support::stage::READ_ONLY_ANNOTATION.to_string(),
                        "true".to_string(),
                    ),
                    (
                        hdriver_support::stage::STAGE_PER_FILE_ANNOTATION.to_string(),
                        "true".to_string(),
                    ),
                ])
            } else {
                BTreeMap::new()
            };
            for (i, addr_str) in addrs.iter().enumerate() {
                let origin_id = format!("dep|{group}|{i}");
                if group == "golist" && golist_origin_id.is_none() {
                    golist_origin_id = Some(origin_id.clone());
                }
                if is_embed_src {
                    embed_src_origin_ids.push(origin_id.clone());
                }
                inputs.push(Input {
                    r#ref: TargetAddr::parse(addr_str, &pkg)
                        .with_context(|| format!("parse dep addr {addr_str}"))?,
                    mode: InputMode::Standard,
                    origin_id,
                    annotations: annotations.clone(),
                    hashed: true,
                    runtime: true,
                });
            }
        }

        let embed_variant = spec
            .embed_variant
            .first()
            .and_then(|s| EmbedVariant::parse(s));

        let def = GoCompileDef {
            p_flag: spec.p_flag,
            out_file: spec.out_file,
            goos: spec.goos,
            goarch: spec.goarch,
            go_version: spec.go_version,
            import_paths: spec.import_paths,
            s_files: spec.s_files,
            embed_variant,
            golist_origin_id: if embed_variant.is_some() {
                golist_origin_id
            } else {
                None
            },
            embed_src_origin_ids,
        };

        let outputs: Vec<Output> = spec
            .out
            .iter()
            .map(|(group, paths)| Output {
                group: group.clone(),
                paths: paths
                    .iter()
                    .map(|p| {
                        let full_path = if pkg_str.is_empty() {
                            p.clone()
                        } else {
                            format!("{pkg_str}/{p}")
                        };
                        Path {
                            content: Content::FilePath(full_path),
                            codegen_tree: CodegenMode::None,
                            collect: true,
                        }
                    })
                    .collect(),
            })
            .collect();

        let hash = {
            let mut h = DebugHasher::new(Xxh3Default::new(), || {
                format!("go_compile_{}", req.target_spec.addr.format())
            });
            def.hash(&mut h);
            format!("{:x}", h.finish()).into_bytes()
        };

        Ok(ParseResponse {
            target_def: TargetDef {
                addr: req.target_spec.addr.clone(),
                labels: req.target_spec.labels.clone(),
                raw_def: Arc::new(def),
                inputs,
                outputs,
                support_files: vec![],
                cache: CacheConfig::on(true),
                pty: false,
                hash,
                transparent: false,
            },
        })
    }

    async fn apply_transitive(
        &self,
        req: ApplyTransitiveRequest,
        _ctoken: &(dyn Cancellable + Send + Sync),
    ) -> anyhow::Result<ApplyTransitiveResponse> {
        Ok(ApplyTransitiveResponse {
            target_def: req.target_def,
        })
    }

    async fn run<'a, 'io>(
        &self,
        req: ManagedRunRequest<'a, 'io>,
        ctoken: &(dyn Cancellable + Send + Sync),
    ) -> anyhow::Result<ManagedRunResponse> {
        let def = req.request.target.def_de::<GoCompileDef>();
        let pkg_dir = &req.sandbox_pkg_dir;
        let ws_root = req.sandbox_ws_dir.to_string_lossy().into_owned();

        // GOROOT / go binary: hermetic staged SDK or host (mirrors go_golist).
        let host = crate::plugingo::toolchain::is_host(&def.go_version);
        let (goroot, go_bin) = if host {
            let go_bin = crate::plugingo::toolchain::resolve_host_go()?;
            let goroot = crate::plugingo::toolchain::host_goroot(&go_bin)?;
            (goroot, go_bin)
        } else {
            let goroot = req
                .sandbox_ws_dir
                .join(crate::plugingo::toolchain::staged_goroot(&def.go_version));
            let go_bin = goroot.join("bin").join("go");
            if !go_bin.exists() {
                anyhow::bail!(
                    "go_compile: hermetic go binary missing at {go_bin:?} (gosdk dep not staged?)"
                );
            }
            (goroot, go_bin)
        };

        let gocache = pkg_dir.join(".heph-gocache");
        std::fs::create_dir_all(&gocache)
            .with_context(|| format!("create gocache dir {gocache:?}"))?;

        let mut env: HashMap<String, String> = HashMap::new();
        env.insert("GOOS".to_string(), def.goos.clone());
        env.insert("GOARCH".to_string(), def.goarch.clone());
        env.insert("GOROOT".to_string(), goroot.to_string_lossy().into_owned());
        env.insert(
            "GOCACHE".to_string(),
            gocache.to_string_lossy().into_owned(),
        );
        env.insert("GOTOOLCHAIN".to_string(), "local".to_string());
        env.insert("GOWORK".to_string(), "off".to_string());
        env.insert("CGO_ENABLED".to_string(), "0".to_string());
        if host && let Ok(v) = std::env::var("PATH") {
            env.insert("PATH".to_string(), v);
        }

        // 1. importcfg: one `packagefile <import>=<archive>` per transitive lib,
        //    sorted by import path (matches the old write_importcfg_script).
        let mut import_paths = def.import_paths.clone();
        import_paths.sort();
        let mut importcfg = String::new();
        for ip in &import_paths {
            let group = crate::plugingo::addr_util::import_path_to_dep_group(ip);
            let archive = self
                .single_staged_path(&req, &group)
                .with_context(|| format!("locate staged archive for lib {ip}"))?;
            importcfg.push_str(&format!("packagefile {ip}={archive}\n"));
        }
        let importcfg_path = pkg_dir.join("importcfg");
        std::fs::write(&importcfg_path, &importcfg).context("write importcfg")?;

        // 2. sources response file: every staged `.go` source in the default group.
        let src_paths = self.group_staged_paths(&req, "");
        let rsp_path = pkg_dir.join("gofiles.rsp");
        std::fs::write(&rsp_path, src_paths.join("\n")).context("write sources response file")?;

        // 3. embedcfg (optional): patterns from go list ∪ go_embed_src resolution.
        let has_embed = if let Some(variant) = def.embed_variant {
            let embedcfg = self
                .compute_embedcfg(&req, &def, variant)
                .context("compute embedcfg")?;
            std::fs::write(pkg_dir.join("embedcfg"), embedcfg).context("write embedcfg")?;
            true
        } else {
            false
        };

        let has_asm = !def.s_files.is_empty();
        let shared = "-shared";
        let trimpath = format!("-trimpath={ws_root}");
        let goinc = format!("{}/pkg/include", goroot.to_string_lossy());

        let run_go =
            |args: Vec<String>| -> Vec<OsString> { args.into_iter().map(OsString::from).collect() };

        // 4. asm step 0+1: seed go_asm.h, then -gensymabis → symabis.
        if has_asm {
            std::fs::write(pkg_dir.join("go_asm.h"), b"").context("seed go_asm.h")?;
            let mut args = vec![
                "tool".to_string(),
                "asm".to_string(),
                "-p".to_string(),
                def.p_flag.clone(),
                trimpath.clone(),
                "-I".to_string(),
                ".".to_string(),
                "-I".to_string(),
                goinc.clone(),
                "-D".to_string(),
                format!("GOOS_{}", def.goos),
                "-D".to_string(),
                format!("GOARCH_{}", def.goarch),
                shared.to_string(),
                "-gensymabis".to_string(),
                "-o".to_string(),
                "symabis".to_string(),
            ];
            for s in &def.s_files {
                args.push(format!("./{s}"));
            }
            self.exec_go(
                &go_bin,
                run_go(args),
                &env,
                pkg_dir,
                ctoken,
                "asm -gensymabis",
            )
            .await?;
        }

        // 5. compile.
        let mut cargs = vec![
            "tool".to_string(),
            "compile".to_string(),
            "-p".to_string(),
            def.p_flag.clone(),
            trimpath.clone(),
            "-pack".to_string(),
            "-importcfg".to_string(),
            importcfg_path.to_string_lossy().into_owned(),
        ];
        if has_asm {
            cargs.push("-symabis".to_string());
            cargs.push("symabis".to_string());
            cargs.push("-asmhdr".to_string());
            cargs.push("go_asm.h".to_string());
        }
        if has_embed {
            cargs.push("-embedcfg".to_string());
            cargs.push("embedcfg".to_string());
        }
        cargs.push(shared.to_string());
        cargs.push("-o".to_string());
        cargs.push(def.out_file.clone());
        cargs.push(format!("@{}", rsp_path.to_string_lossy()));
        self.exec_go(&go_bin, run_go(cargs), &env, pkg_dir, ctoken, "compile")
            .await?;

        // 6. asm step 3+4: assemble each .s, then pack into the archive.
        if has_asm {
            for s in &def.s_files {
                let obj = format!("{}.o", s.trim_end_matches(".s"));
                let args = vec![
                    "tool".to_string(),
                    "asm".to_string(),
                    "-p".to_string(),
                    def.p_flag.clone(),
                    trimpath.clone(),
                    "-I".to_string(),
                    ".".to_string(),
                    "-I".to_string(),
                    goinc.clone(),
                    "-D".to_string(),
                    format!("GOOS_{}", def.goos),
                    "-D".to_string(),
                    format!("GOARCH_{}", def.goarch),
                    shared.to_string(),
                    "-o".to_string(),
                    obj,
                    format!("./{s}"),
                ];
                self.exec_go(&go_bin, run_go(args), &env, pkg_dir, ctoken, "asm")
                    .await?;
            }
            let mut pargs = vec![
                "tool".to_string(),
                "pack".to_string(),
                "r".to_string(),
                def.out_file.clone(),
            ];
            for s in &def.s_files {
                pargs.push(format!("{}.o", s.trim_end_matches(".s")));
            }
            self.exec_go(&go_bin, run_go(pargs), &env, pkg_dir, ctoken, "pack")
                .await?;
        }

        Ok(ManagedRunResponse { artifacts: vec![] })
    }
}

impl GoCompileDriver {
    /// All staged file paths for the inputs in dep `group` (origin `dep|group|*`).
    fn group_staged_paths(&self, req: &ManagedRunRequest<'_, '_>, group: &str) -> Vec<String> {
        let prefix = format!("dep|{group}|");
        let mut out: Vec<String> = Vec::new();
        for m in &req.inputs {
            if !m.input.origin_id.starts_with(&prefix) {
                continue;
            }
            let Ok(list_path) = m.require_list_path() else {
                continue;
            };
            if let Ok(f) = std::fs::File::open(list_path) {
                for line in std::io::BufReader::new(f).lines().map_while(Result::ok) {
                    if !line.is_empty() {
                        out.push(line);
                    }
                }
            }
        }
        out
    }

    /// The single staged path for a one-output group (e.g. a lib archive).
    fn single_staged_path(
        &self,
        req: &ManagedRunRequest<'_, '_>,
        group: &str,
    ) -> anyhow::Result<String> {
        self.group_staged_paths(req, group)
            .into_iter()
            .next()
            .ok_or_else(|| anyhow::anyhow!("no staged file for dep group {group}"))
    }

    /// Resolve the embedcfg JSON for `variant`: union Go's authoritative
    /// EmbedFiles (from the `golist` package.bin) with the selector's resolution
    /// of the staged `go_embed_src` assets, then group under each pattern.
    fn compute_embedcfg(
        &self,
        req: &ManagedRunRequest<'_, '_>,
        def: &GoCompileDef,
        variant: EmbedVariant,
    ) -> anyhow::Result<String> {
        let golist_origin = def
            .golist_origin_id
            .as_deref()
            .ok_or_else(|| anyhow::anyhow!("go_compile: embed requested but no golist input"))?;
        let managed = req
            .inputs
            .iter()
            .find(|m| m.input.origin_id == golist_origin)
            .ok_or_else(|| anyhow::anyhow!("go_compile: golist input not found"))?;
        let list_path = managed.require_list_path()?;
        let list_f = std::fs::File::open(list_path)
            .with_context(|| format!("open golist list {list_path:?}"))?;
        let pkg_bin_path = std::io::BufReader::new(list_f)
            .lines()
            .map_while(Result::ok)
            .find(|s| !s.is_empty() && s.ends_with("package.bin"))
            .ok_or_else(|| anyhow::anyhow!("go_compile: package.bin not found in golist input"))?;
        let pkg =
            decode_go_package(std::fs::File::open(&pkg_bin_path).context("open package.bin")?)
                .context("decode package.bin")?;

        let (patterns, go_src_files) = match variant {
            EmbedVariant::Embed => (pkg.embed_patterns.clone(), pkg.embed_files.clone()),
            EmbedVariant::TestEmbed => (
                pkg.embed_patterns
                    .iter()
                    .chain(pkg.test_embed_patterns.iter())
                    .cloned()
                    .collect(),
                pkg.embed_files
                    .iter()
                    .chain(pkg.test_embed_files.iter())
                    .cloned()
                    .collect(),
            ),
            EmbedVariant::XtestEmbed => (
                pkg.xtest_embed_patterns.clone(),
                pkg.xtest_embed_files.clone(),
            ),
        };

        let embed_src_rel = self.collect_embed_src_rel(req, &def.embed_src_origin_ids)?;
        let files = embed::merge_embed_files(go_src_files, &patterns, &embed_src_rel);
        embed::compute_embed_cfg_json(&patterns, &files)
    }

    /// Staged `go_embed_src` files as package-relative, `/`-separated paths.
    fn collect_embed_src_rel(
        &self,
        req: &ManagedRunRequest<'_, '_>,
        origin_ids: &[String],
    ) -> anyhow::Result<Vec<String>> {
        let mut rel: Vec<String> = Vec::new();
        for id in origin_ids {
            // A `go_embed_src` dep can be a query that matched no targets (e.g. a
            // package with only checked-in `go_src` embeds). The engine elides
            // such inputs, so a missing origin here means "no files", not an
            // error — an actually-unresolved embed pattern surfaces downstream
            // in `compute_embed_cfg_json`'s zero-match check.
            let Some(managed) = req.inputs.iter().find(|m| m.input.origin_id == *id) else {
                continue;
            };
            let Ok(list_path) = managed.require_list_path() else {
                continue;
            };
            let f = std::fs::File::open(list_path)
                .with_context(|| format!("open embed_src list {list_path:?}"))?;
            for line in std::io::BufReader::new(f).lines() {
                let line = line.context("read embed_src list line")?;
                if line.is_empty() {
                    continue;
                }
                let abs = std::path::Path::new(&line);
                let r = abs.strip_prefix(&req.sandbox_pkg_dir).unwrap_or(abs);
                rel.push(r.to_string_lossy().replace('\\', "/"));
            }
        }
        Ok(rel)
    }

    async fn exec_go(
        &self,
        go_bin: &std::path::Path,
        args: Vec<OsString>,
        env: &HashMap<String, String>,
        cwd: &std::path::Path,
        ctoken: &(dyn Cancellable + Send + Sync),
        step: &str,
    ) -> anyhow::Result<()> {
        let env_pairs: Vec<(OsString, OsString)> = env
            .iter()
            .map(|(k, v)| (OsString::from(k), OsString::from(v)))
            .collect();
        let spec = proc_exec::Spec {
            program: go_bin.to_path_buf(),
            args,
            env: env_pairs,
            cwd: cwd.to_path_buf(),
            stdin: proc_exec::StdioSpec::Null,
            stdout: proc_exec::StdioSpec::Piped,
            stderr: proc_exec::StdioSpec::Piped,
            setsid: false,
            ctty: false,
        };
        let output = proc_exec::output(spec, ctoken)
            .await
            .with_context(|| format!("wait for go {step}"))?;
        if !output.status.success() {
            let stderr = String::from_utf8_lossy(&output.stderr);
            anyhow::bail!(
                "go {step} failed:\n{}",
                hplugin::error::last_n_lines(&stderr, 20)
            );
        }
        Ok(())
    }
}

// ---------------------------------------------------------------------------
// Provider-facing spec builder
// ---------------------------------------------------------------------------

use crate::plugingo::addr_util::{go_sdk_dep, import_path_to_dep_group};
use crate::plugingo::factors::Factors;
use hcore::htvalue::Value;
use hmodel::htaddr::Addr;
use hplugin::provider::TargetSpec;

/// Parameters for [`build_compile_spec`]. Groups the (necessarily many) compile
/// inputs so each builder (`target_lib`, `target_test`, `thirdparty`) just fills
/// this in.
pub struct CompileParams<'a> {
    pub addr: Addr,
    /// `-p` flag: `main` for main packages, else the import path.
    pub p_flag: String,
    /// Output archive filename (package-relative).
    pub out_file: String,
    pub factors: &'a Factors,
    pub go_version: &'a str,
    /// `(import_path, lib archive addr)` — importcfg entries + `lib_*` dep groups.
    pub transitive_libs: &'a [(String, Addr)],
    /// Compile sources (`.go`) → the default (`""`) dep group.
    pub src_addrs: &'a [String],
    /// `.s` assembly source names (package-relative) driving the asm steps.
    pub s_files: &'a [String],
    /// Addrs that stage the `.s` sources into the sandbox.
    pub s_file_addrs: &'a [String],
    /// `.h` header addrs (next to / `#include`d by the `.s` sources).
    pub hdr_addrs: &'a [String],
    /// `golist|pkg` addr — read for `EmbedPatterns`/`EmbedFiles`. `Some` iff the
    /// package embeds.
    pub golist_addr: Option<&'a Addr>,
    /// `""` for no embed, else `embed` / `test_embed` / `xtest_embed`.
    pub embed_variant: &'a str,
    /// `go_src` embed file addrs (Go resolved) staged for the compile.
    pub embed_file_addrs: &'a [String],
    /// `go_embed_src` lane addrs (assets `go list` never saw), resolved in-driver.
    pub embed_src_addrs: &'a [String],
}

/// Build a `go_compile` target spec. Replaces the former `sh`-script compile and
/// the separate `go_embed` target.
pub fn build_compile_spec(p: CompileParams) -> TargetSpec {
    let mut deps: BTreeMap<String, Value> = p
        .transitive_libs
        .iter()
        .map(|(import_path, dep_addr)| {
            (
                import_path_to_dep_group(import_path),
                Value::List(vec![Value::String(dep_addr.format())]),
            )
        })
        .collect();

    let str_list = |v: &[String]| Value::List(v.iter().cloned().map(Value::String).collect());

    deps.insert(String::new(), str_list(p.src_addrs));
    if !p.s_file_addrs.is_empty() {
        deps.insert("asm".to_string(), str_list(p.s_file_addrs));
    }
    if !p.hdr_addrs.is_empty() {
        deps.insert("hdr".to_string(), str_list(p.hdr_addrs));
    }
    let embedding = !p.embed_variant.is_empty();
    if embedding && let Some(golist) = p.golist_addr {
        deps.insert(
            "golist".to_string(),
            Value::List(vec![Value::String(format!("{}|pkg", golist.format()))]),
        );
    }
    if !p.embed_file_addrs.is_empty() {
        deps.insert("embed_files".to_string(), str_list(p.embed_file_addrs));
    }
    if !p.embed_src_addrs.is_empty() {
        deps.insert("embed_src".to_string(), str_list(p.embed_src_addrs));
    }
    if let Some((sdk_group, sdk_val)) = go_sdk_dep(p.go_version) {
        deps.insert(sdk_group, sdk_val);
    }

    let import_paths: Vec<Value> = p
        .transitive_libs
        .iter()
        .map(|(ip, _)| Value::String(ip.clone()))
        .collect();

    let mut config: HashMap<String, Value> = HashMap::new();
    config.insert("p_flag".to_string(), Value::String(p.p_flag));
    config.insert("out_file".to_string(), Value::String(p.out_file.clone()));
    config.insert("goos".to_string(), Value::String(p.factors.goos.clone()));
    config.insert(
        "goarch".to_string(),
        Value::String(p.factors.goarch.clone()),
    );
    config.insert(
        "go_version".to_string(),
        Value::String(p.go_version.to_string()),
    );
    config.insert("import_paths".to_string(), Value::List(import_paths));
    config.insert("s_files".to_string(), str_list(p.s_files));
    config.insert(
        "embed_variant".to_string(),
        if embedding {
            Value::List(vec![Value::String(p.embed_variant.to_string())])
        } else {
            Value::List(vec![])
        },
    );
    config.insert("deps".to_string(), Value::Map(deps.into_iter().collect()));
    config.insert(
        "out".to_string(),
        Value::Map(HashMap::from([(
            "a".to_string(),
            Value::List(vec![Value::String(p.out_file)]),
        )])),
    );
    // NOTE: unlike the old `sh` compile, GOOS/GOARCH/CGO/GOTOOLCHAIN/GOWORK and
    // read-only/host-env handling are NOT config keys — the managed driver sets
    // env directly in run() and marks read-only via input annotations. Cache
    // correctness rides on GoCompileDef (go_version, goos, goarch, format ver).

    TargetSpec {
        addr: p.addr,
        driver: "go_compile".to_string(),
        config,
        labels: vec!["go-build".to_string()],
        transitive: Default::default(),
    }
}

#[cfg(test)]
mod driver_tests {
    use super::*;
    use crate::plugingo::factors::Factors;
    use hmodel::htpkg::PkgBuf;

    const V: &str = crate::plugingo::toolchain::DEFAULT_GO_VERSION;

    fn factors() -> Factors {
        Factors {
            goos: "linux".into(),
            goarch: "amd64".into(),
            build_tags: vec![],
        }
    }

    async fn parse_def(spec: TargetSpec) -> TargetDef {
        let ct = hcore::hasync::StdCancellationToken::new();
        GoCompileDriver::new()
            .parse(
                ParseRequest {
                    request_id: "t".to_string(),
                    target_spec: std::sync::Arc::new(spec),
                },
                &ct,
            )
            .await
            .unwrap()
            .target_def
    }

    #[tokio::test]
    async fn parse_embed_src_inputs_are_read_only_per_file_and_capture_golist() {
        let golist = Addr::new(
            PkgBuf::from("mylib"),
            "_golist".to_string(),
            Default::default(),
        );
        let spec = build_compile_spec(CompileParams {
            addr: Addr::new(
                PkgBuf::from("mylib"),
                "build_lib".to_string(),
                Default::default(),
            ),
            p_flag: "example.com/mylib".to_string(),
            out_file: "x.a".to_string(),
            factors: &factors(),
            go_version: V,
            transitive_libs: &[],
            src_addrs: &["//mylib:a.go".to_string()],
            s_files: &[],
            s_file_addrs: &[],
            hdr_addrs: &[],
            golist_addr: Some(&golist),
            embed_variant: "embed",
            embed_file_addrs: &[],
            embed_src_addrs: &["//mylib:frontend".to_string()],
        });
        let def = parse_def(spec).await;
        let es = def
            .inputs
            .iter()
            .find(|i| i.origin_id.starts_with("dep|embed_src|"))
            .expect("embed_src input present");
        assert_eq!(
            es.annotations
                .get(hdriver_support::stage::READ_ONLY_ANNOTATION)
                .map(String::as_str),
            Some("true")
        );
        assert_eq!(
            es.annotations
                .get(hdriver_support::stage::STAGE_PER_FILE_ANNOTATION)
                .map(String::as_str),
            Some("true")
        );
        let d = def.def::<GoCompileDef>();
        assert_eq!(d.embed_variant, Some(EmbedVariant::Embed));
        assert!(d.golist_origin_id.is_some(), "golist origin captured");
        assert_eq!(d.embed_src_origin_ids.len(), 1);
    }

    #[tokio::test]
    async fn parse_no_embed_leaves_variant_and_golist_unset() {
        let spec = build_compile_spec(CompileParams {
            addr: Addr::new(
                PkgBuf::from("mylib"),
                "build_lib".to_string(),
                Default::default(),
            ),
            p_flag: "example.com/mylib".to_string(),
            out_file: "x.a".to_string(),
            factors: &factors(),
            go_version: V,
            transitive_libs: &[],
            src_addrs: &["//mylib:a.go".to_string()],
            s_files: &[],
            s_file_addrs: &[],
            hdr_addrs: &[],
            golist_addr: None,
            embed_variant: "",
            embed_file_addrs: &[],
            embed_src_addrs: &[],
        });
        let def = parse_def(spec).await;
        let d = def.def::<GoCompileDef>();
        assert_eq!(d.embed_variant, None);
        assert!(d.golist_origin_id.is_none());
    }

    #[tokio::test]
    async fn parse_sdk_input_is_read_only() {
        let spec = build_compile_spec(CompileParams {
            addr: Addr::new(
                PkgBuf::from("mylib"),
                "build_lib".to_string(),
                Default::default(),
            ),
            p_flag: "example.com/mylib".to_string(),
            out_file: "x.a".to_string(),
            factors: &factors(),
            go_version: V,
            transitive_libs: &[],
            src_addrs: &["//mylib:a.go".to_string()],
            s_files: &[],
            s_file_addrs: &[],
            hdr_addrs: &[],
            golist_addr: None,
            embed_variant: "",
            embed_file_addrs: &[],
            embed_src_addrs: &[],
        });
        let def = parse_def(spec).await;
        let prefix = format!("dep|{}|", crate::plugingo::addr_util::GO_SDK_DEP_GROUP);
        let sdk = def
            .inputs
            .iter()
            .find(|i| i.origin_id.starts_with(&prefix))
            .expect("sdk input present");
        assert_eq!(
            sdk.annotations
                .get(hdriver_support::stage::READ_ONLY_ANNOTATION)
                .map(String::as_str),
            Some("true")
        );
    }
}

/// Shared helpers for asserting on `go_compile` specs from the builders' tests.
#[cfg(test)]
pub(crate) mod test_support {
    use hcore::htvalue::Value;
    use hplugin::provider::TargetSpec;
    use std::collections::HashMap;

    pub(crate) fn cfg_str(spec: &TargetSpec, k: &str) -> String {
        match spec
            .config
            .get(k)
            .unwrap_or_else(|| panic!("missing config {k}"))
        {
            Value::String(s) => s.clone(),
            v => panic!("{k} not a string: {v:?}"),
        }
    }

    pub(crate) fn cfg_list(spec: &TargetSpec, k: &str) -> Vec<String> {
        match spec
            .config
            .get(k)
            .unwrap_or_else(|| panic!("missing config {k}"))
        {
            Value::List(l) => l
                .iter()
                .map(|x| match x {
                    Value::String(s) => s.clone(),
                    _ => panic!("{k} entry not a string"),
                })
                .collect(),
            v => panic!("{k} not a list: {v:?}"),
        }
    }

    pub(crate) fn deps_map(spec: &TargetSpec) -> HashMap<String, Vec<String>> {
        match spec.config.get("deps").unwrap() {
            Value::Map(m) => m
                .iter()
                .map(|(k, v)| {
                    let list = match v {
                        Value::List(l) => l
                            .iter()
                            .map(|x| match x {
                                Value::String(s) => s.clone(),
                                _ => panic!("dep entry not a string"),
                            })
                            .collect(),
                        _ => panic!("dep group not a list"),
                    };
                    (k.clone(), list)
                })
                .collect(),
            _ => panic!("deps not a map"),
        }
    }
}
