mod addr_util;
mod driver_compile;
mod driver_golist;
mod driver_testmain;
mod embed;
pub(crate) mod errors;
mod factors;
mod gen_testmain;
mod pkg_analysis;
mod provider;
mod target_bin;
mod target_golist;
mod target_lib;
mod target_modfiles;
mod target_std;
mod target_test;
mod thirdparty;
mod toolchain;

pub use driver_compile::GoCompileDriver;
pub use driver_golist::GoGolistDriver;
pub use driver_testmain::GoTestmainDriver;
pub use provider::{Config, Provider};
pub use toolchain::GoToolchainDriver;
