load("//backend/go", "go_mod")
load("//backend/go", "go_bin")

go_mod(
    cfg={
        "...": {
            "test": {
                "run": {
                    "labels": "mytest"
                }
            }
        }
    }
)
