//! Guards on the lint gate itself.
//!
//! `lint` used to run `cargo clippy --all-targets` with no `--workspace`. The
//! repo root is itself a package, so cargo selected *only* that package: every
//! member's lib was compiled as a plain dependency with lints switched off, and
//! no member's test targets were built at all. 323 clippy errors accumulated
//! behind it, and on 2026-07-29 the `Lint` job reported pass on a master commit
//! whose `engine (lib test)` did not compile.
//!
//! Both tests below assert a *selection* invariant — which code the gate is
//! pointed at — because that is the class of failure that is silent. A lint the
//! gate can see fails loudly; a crate the gate cannot see fails never.
//!
//! Cheap on purpose: two file reads and some string work, no build.

use std::path::{Path, PathBuf};

/// The repo root — this test belongs to the root package, so its manifest dir
/// *is* the root.
fn repo_root() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).to_path_buf()
}

/// `gen/proto` is generated by `buf`/`protoc-gen-prost` and carries
/// `[lints.clippy] all = "allow"` deliberately — hand-written lint policy does
/// not apply to code nobody hand-edits.
const LINTS_EXEMPT: &[&str] = &["gen/proto"];

/// The paths in the root manifest's `workspace.members` array.
///
/// Read from the manifest rather than hardcoded: a copy of the list would stop
/// covering exactly the crates this test exists to catch — the new ones.
fn workspace_members(manifest: &str) -> Vec<String> {
    let after = manifest
        .split_once("members = [")
        .map(|(_, rest)| rest)
        .expect("root Cargo.toml has a workspace.members array");
    let list = after
        .split_once(']')
        .map(|(list, _)| list)
        .expect("workspace.members array is closed");
    list.split(',')
        .map(|entry| entry.trim().trim_matches('"').to_string())
        .filter(|entry| !entry.is_empty())
        .collect()
}

/// Whether `manifest` has a `[lints]` table containing `workspace = true`.
///
/// Deliberately section-aware: `[lints.clippy]` is a *different* table and must
/// not satisfy this, since a crate that defines its own lints does not inherit
/// the workspace set (cargo rejects having both).
fn inherits_workspace_lints(manifest: &str) -> bool {
    let mut in_lints = false;
    for line in manifest.lines() {
        let line = line.trim();
        if let Some(section) = line.strip_prefix('[').and_then(|s| s.strip_suffix(']')) {
            in_lints = section == "lints";
            continue;
        }
        if in_lints && line.replace(' ', "") == "workspace=true" {
            return true;
        }
    }
    false
}

/// Every member must inherit `[workspace.lints]`.
///
/// This is the other half of the gate's coverage, and it fails the same silent
/// way: `--workspace --all-targets` will happily lint a member that never
/// opted in, using stock clippy only — no `unwrap_used`, no `indexing_slicing`,
/// no `map_err_ignore`, no `undocumented_unsafe_blocks` — and report green.
#[test]
fn every_workspace_member_inherits_the_workspace_lints() {
    let root = repo_root();
    let manifest =
        std::fs::read_to_string(root.join("Cargo.toml")).expect("read the root Cargo.toml");
    let members = workspace_members(&manifest);
    assert!(
        members.len() > 10,
        "parsed only {} workspace members — the manifest layout changed and this \
         test is no longer reading it",
        members.len()
    );

    let missing: Vec<&String> = members
        .iter()
        .filter(|member| !LINTS_EXEMPT.contains(&member.as_str()))
        .filter(|member| {
            let path = root.join(member).join("Cargo.toml");
            let member_manifest = std::fs::read_to_string(&path)
                .unwrap_or_else(|e| panic!("read {}: {e}", path.display()));
            !inherits_workspace_lints(&member_manifest)
        })
        .collect();

    assert!(
        missing.is_empty(),
        "these workspace members do not inherit `[workspace.lints]`, so the \
         repo's restriction lints do not apply to them and `lint` will report \
         green on code that violates every one of them: {missing:?}\n\
         Add `[lints]\\nworkspace = true` to each, or add it to LINTS_EXEMPT \
         here with a reason."
    );
}

/// The `lint` script must point clippy at the whole workspace, every target.
///
/// This restates the implementation on purpose: the literal regression was
/// someone writing the shorter invocation, and the comment above it in
/// `devenv.nix` is documentation, not a gate.
#[test]
fn the_lint_script_selects_the_whole_workspace() {
    let devenv = std::fs::read_to_string(repo_root().join("devenv.nix")).expect("read devenv.nix");
    let clippy_lines: Vec<&str> = devenv
        .lines()
        .map(str::trim)
        .filter(|line| line.starts_with("cargo clippy"))
        .collect();

    assert_eq!(
        clippy_lines.len(),
        2,
        "expected exactly two clippy invocations in devenv.nix (default features \
         and --all-features); found {clippy_lines:?}"
    );
    for line in clippy_lines {
        assert!(
            line.contains("--workspace"),
            "`{line}` omits --workspace. The repo root is itself a package, so \
             cargo would select only the root package: members' libs get linted \
             with no lints applied and their test targets are never built."
        );
        assert!(
            line.contains("--all-targets"),
            "`{line}` omits --all-targets, so `#[cfg(test)] mod tests` and \
             `tests/` are skipped — where most of this repo's test code lives."
        );
    }
}
