//! Guards on the lint gate itself.
//!
//! `lint` used to run `cargo clippy --all-targets` with no `--workspace`. The
//! repo root is itself a package, so cargo selected *only* that package: every
//! member's lib was compiled as a plain dependency with lints switched off, and
//! no member's test targets were built at all. 323 clippy errors accumulated
//! behind it, and on 2026-07-29 the `Lint` job reported pass on a master commit
//! whose `engine (lib test)` did not compile.
//!
//! Every test below asserts a *selection* invariant — which code the gate is
//! pointed at — because that is the class of failure that is silent. A lint the
//! gate can see fails loudly; a crate the gate cannot see fails never. The
//! selection has four axes and each one has already gone wrong or been left
//! open: which packages (`--workspace`), which targets (`--all-targets`), which
//! feature set (`--no-default-features`, whose obvious spelling is a no-op
//! here), and which platform (macOS was linted nowhere).
//!
//! Cheap on purpose: a few file reads and some string work, no build.

use std::path::{Path, PathBuf};

/// The repo root — this test belongs to the root package, so its manifest dir
/// *is* the root.
fn repo_root() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).to_path_buf()
}

/// `gen/proto` is generated by `buf`/`protoc-gen-prost` and carries
/// `[lints.clippy] all = "allow"` deliberately — hand-written lint policy does
/// not apply to code nobody hand-edits.
const LINTS_EXEMPT: &[&str] = &["gen/proto"];

/// The paths in the root manifest's `workspace.members` array.
///
/// Read from the manifest rather than hardcoded: a copy of the list would stop
/// covering exactly the crates this test exists to catch — the new ones.
fn workspace_members(manifest: &str) -> Vec<String> {
    let after = manifest
        .split_once("members = [")
        .map(|(_, rest)| rest)
        .expect("root Cargo.toml has a workspace.members array");
    let list = after
        .split_once(']')
        .map(|(list, _)| list)
        .expect("workspace.members array is closed");
    list.split(',')
        .map(|entry| entry.trim().trim_matches('"').to_string())
        .filter(|entry| !entry.is_empty())
        .collect()
}

/// Whether `manifest` has a `[lints]` table containing `workspace = true`.
///
/// Deliberately section-aware: `[lints.clippy]` is a *different* table and must
/// not satisfy this, since a crate that defines its own lints does not inherit
/// the workspace set (cargo rejects having both).
fn inherits_workspace_lints(manifest: &str) -> bool {
    let mut in_lints = false;
    for line in manifest.lines() {
        let line = line.trim();
        if let Some(section) = line.strip_prefix('[').and_then(|s| s.strip_suffix(']')) {
            in_lints = section == "lints";
            continue;
        }
        if in_lints && line.replace(' ', "") == "workspace=true" {
            return true;
        }
    }
    false
}

/// Every member must inherit `[workspace.lints]`.
///
/// This is the other half of the gate's coverage, and it fails the same silent
/// way: `--workspace --all-targets` will happily lint a member that never
/// opted in, using stock clippy only — no `unwrap_used`, no `indexing_slicing`,
/// no `map_err_ignore`, no `undocumented_unsafe_blocks` — and report green.
#[test]
fn every_workspace_member_inherits_the_workspace_lints() {
    let root = repo_root();
    let manifest =
        std::fs::read_to_string(root.join("Cargo.toml")).expect("read the root Cargo.toml");
    let members = workspace_members(&manifest);
    assert!(
        members.len() > 10,
        "parsed only {} workspace members — the manifest layout changed and this \
         test is no longer reading it",
        members.len()
    );

    let missing: Vec<&String> = members
        .iter()
        .filter(|member| !LINTS_EXEMPT.contains(&member.as_str()))
        .filter(|member| {
            let path = root.join(member).join("Cargo.toml");
            let member_manifest = std::fs::read_to_string(&path)
                .unwrap_or_else(|e| panic!("read {}: {e}", path.display()));
            !inherits_workspace_lints(&member_manifest)
        })
        .collect();

    assert!(
        missing.is_empty(),
        "these workspace members do not inherit `[workspace.lints]`, so the \
         repo's restriction lints do not apply to them and `lint` will report \
         green on code that violates every one of them: {missing:?}\n\
         Add `[lints]\\nworkspace = true` to each, or add it to LINTS_EXEMPT \
         here with a reason."
    );
}

/// The body of a `scripts.<name>.exec = ''…'';` block in `devenv.nix`.
///
/// Split per script rather than scanning the whole file: `lint` and `fix` both
/// contain `cargo clippy` lines, and the invariant below is that they *agree* —
/// which cannot be checked if the two are read as one pile.
///
/// `expect`, not `panic!`: `clippy.toml`'s `allow-panic-in-tests` only covers
/// `#[test]` bodies, and this is a free function.
#[track_caller]
fn devenv_script(devenv: &str, name: &str) -> String {
    let marker = format!("scripts.{name}.exec = ''");
    // Built up front rather than inside `expect`, which would be
    // `expect_fun_call`.
    let opened = format!("devenv.nix defines `scripts.{name}.exec` as a '' block");
    let closed = format!("`scripts.{name}.exec` block is closed");
    let (_, rest) = devenv.split_once(&marker).expect(&opened);
    let (body, _) = rest.split_once("'';").expect(&closed);
    body.to_string()
}

/// The `cargo clippy` invocations inside one script body, trimmed.
fn clippy_lines(script: &str) -> Vec<&str> {
    script
        .lines()
        .map(str::trim)
        .filter(|line| line.starts_with("cargo clippy"))
        .collect()
}

/// The `--exclude <name>` arguments on a single invocation.
///
/// Both spellings cargo accepts, `--exclude name` and `--exclude=name`: reading
/// only the first would turn a legal rewrite of the script into a spurious
/// failure.
fn excludes(line: &str) -> Vec<&str> {
    let mut out = Vec::new();
    let mut words = line.split_whitespace();
    while let Some(word) = words.next() {
        if let Some(name) = word.strip_prefix("--exclude=") {
            out.push(name);
        } else if word == "--exclude"
            && let Some(name) = words.next()
        {
            out.push(name);
        }
    }
    out
}

/// The `lint` script must point clippy at the whole workspace, every target.
///
/// This restates the implementation on purpose: the literal regression was
/// someone writing the shorter invocation, and the comment above it in
/// `devenv.nix` is documentation, not a gate.
#[test]
fn the_lint_script_selects_the_whole_workspace() {
    let devenv = std::fs::read_to_string(repo_root().join("devenv.nix")).expect("read devenv.nix");
    let lint = devenv_script(&devenv, "lint");
    let lines = clippy_lines(&lint);

    assert!(
        lines.len() >= 3,
        "expected at least three clippy invocations in `lint` (default features, \
         --all-features, --no-default-features); found {lines:?}"
    );
    for line in &lines {
        assert!(
            line.contains("--workspace"),
            "`{line}` omits --workspace. The repo root is itself a package, so \
             cargo would select only the root package: members' libs get linted \
             with no lints applied and their test targets are never built."
        );
        assert!(
            line.contains("--all-targets"),
            "`{line}` omits --all-targets, so `#[cfg(test)] mod tests` and \
             `tests/` are skipped — where most of this repo's test code lives."
        );
    }

    let feature_off: Vec<&&str> = lines
        .iter()
        .filter(|line| line.contains("--no-default-features"))
        .collect();
    assert_eq!(
        feature_off.len(),
        1,
        "`lint` must carry exactly one --no-default-features pass. With \
         `fuse-sandbox` on — the default — `crates/sandboxfuse/src/stub.rs` is \
         compiled by nothing at all, on any platform, and must still satisfy \
         its callers in `crates/engine` and `crates/driver-bridge`. Found \
         {feature_off:?}"
    );

    // The guard that proves the pass above is pointed at the feature-*off* arm
    // must itself exist, and must select the same packages. Without this, the
    // guard can be deleted the first time it is inconvenient and the third pass
    // silently reverts to re-linting the arm pass 1 already covered — with the
    // script still printing `> clippy --no-default-features`.
    let probe = lint
        .lines()
        .map(str::trim)
        // `!starts_with('#')`: the block is commented, and a comment mentioning
        // the probe is not the probe.
        .find(|line| {
            !line.starts_with('#') && line.contains("cargo tree") && line.contains("-i fuser")
        })
        .expect(
            "`lint` must assert `fuse-sandbox` is actually off before linting it, \
             with a `cargo tree … -i fuser` probe. `--no-default-features` alone \
             does not disable it: e2e/plugingo-e2e/testkit pull the root `heph` \
             package with default features and cargo unifies across the selection.",
        );
    assert_eq!(
        excludes(probe),
        excludes(feature_off[0]),
        "the `cargo tree -i fuser` probe and the --no-default-features clippy \
         pass select different packages, so the probe is not checking the \
         selection that gets linted.\nprobe: {probe}\npass:  {}",
        feature_off[0]
    );
}

/// The `--no-default-features` pass must exclude every member that switches
/// `fuse-sandbox` back on, or it silently lints the wrong arm.
///
/// Cargo unifies features across the whole selected set. `crates/e2e`,
/// `crates/plugingo-e2e` and `crates/testkit` depend on the root `heph` package
/// with default features on, so a plain `--workspace --no-default-features`
/// re-enables `fuse-sandbox` through that edge and the pass becomes a no-op
/// that still reports green — the same silent-selection failure the rest of
/// this file exists to catch, one axis over.
///
/// Derived from the manifests, never copied: a *new* member with a default-
/// featured `heph` edge is exactly the case a hardcoded list would miss.
///
/// **Scope, stated so it is not over-trusted.** This reads one line per
/// manifest, so it sees a *direct*, single-line `heph = { … }` edge and nothing
/// else — not a `[dependencies.heph]` table, not a multi-line inline table, and
/// not a transitive re-enable (a new member dev-depending on `htestkit`, which
/// itself pulls `heph` with default features, gets the feature back without
/// appearing here). The authority is the `cargo tree -i fuser` assertion inside
/// `lint`, which sees the fully resolved graph; this test is the cheap early
/// warning that costs no build, not a replacement for it.
#[test]
fn the_feature_off_pass_excludes_every_member_that_re_enables_fuse_sandbox() {
    let root = repo_root();
    let manifest = std::fs::read_to_string(root.join("Cargo.toml")).expect("read root Cargo.toml");
    let members = workspace_members(&manifest);

    let mut re_enablers: Vec<String> = members
        .iter()
        .filter(|member| {
            let path = root.join(member).join("Cargo.toml");
            let member_manifest = std::fs::read_to_string(&path)
                .unwrap_or_else(|e| panic!("read {}: {e}", path.display()));
            member_manifest.lines().any(|line| {
                let line = line.trim();
                line.starts_with("heph = ") && !line.contains("default-features = false")
            })
        })
        // The package name is the last path component for every member here.
        .map(|member| {
            member
                .rsplit('/')
                .next()
                .unwrap_or(member.as_str())
                .to_string()
        })
        .collect();
    re_enablers.sort();
    assert!(
        !re_enablers.is_empty(),
        "no member was found depending on the root `heph` package — this test \
         is no longer reading the manifests it thinks it is"
    );

    let devenv = std::fs::read_to_string(root.join("devenv.nix")).expect("read devenv.nix");
    for script in ["lint", "fix"] {
        let body = devenv_script(&devenv, script);
        let line = clippy_lines(&body)
            .into_iter()
            .find(|line| line.contains("--no-default-features"))
            .unwrap_or_else(|| panic!("`{script}` has a --no-default-features clippy invocation"));
        let mut excluded = excludes(line);
        excluded.sort_unstable();

        let missing: Vec<&String> = re_enablers
            .iter()
            .filter(|name| !excluded.contains(&name.as_str()))
            .collect();
        assert!(
            missing.is_empty(),
            "`{script}`'s --no-default-features pass does not exclude {missing:?}. \
             Those members depend on the root `heph` package with default \
             features on, and cargo unifies features across the selection, so \
             `fuse-sandbox` is switched back on and the pass lints the feature-\
             *on* arm while reporting that it covered the off one.\n\
             Add `--exclude <name>` for each, or give the member's `heph` \
             dependency `default-features = false`."
        );

        // Equality, not just containment. An *extra* exclusion is the more
        // dangerous direction and a subset check waves it through: `--exclude
        // engine` or `--exclude driver-bridge` drops the two callers `stub.rs`
        // has to satisfy, and `--exclude sandboxfuse` drops the only package
        // the feature changes at all. Each turns the pass into a no-op that
        // still reports green, and none of them puts `fuser` back in the graph,
        // so the `cargo tree` guard in `lint` cannot see it either.
        let extra: Vec<&&str> = excluded
            .iter()
            .filter(|name| !re_enablers.iter().any(|r| r == *name))
            .collect();
        assert!(
            extra.is_empty(),
            "`{script}`'s --no-default-features pass excludes {extra:?}, which \
             do not re-enable `fuse-sandbox`. Excluding a package that is not a \
             re-enabler only shrinks what the pass lints — `engine` and \
             `driver-bridge` are the callers `crates/sandboxfuse/src/stub.rs` \
             must satisfy, and `sandboxfuse` is the only package the feature \
             changes — and neither the `cargo tree` guard nor the check above \
             can see the loss. Expected exactly {re_enablers:?}."
        );
    }
}

/// `fix` must select the same code as `lint`.
///
/// A `fix` that reaches less than `lint` leaves CI reporting lints with no
/// automated fix — and the person who hits it has to work out which of three
/// invocations produced the error before they can reproduce it.
#[test]
fn fix_selects_the_same_code_as_lint() {
    let devenv = std::fs::read_to_string(repo_root().join("devenv.nix")).expect("read devenv.nix");
    let fix = devenv_script(&devenv, "fix");
    let fix_lines = clippy_lines(&fix);

    for line in &fix_lines {
        assert!(
            line.contains("--fix"),
            "`{line}` is a bare clippy invocation inside `fix`; it must be \
             `cargo clippy --fix`"
        );
        assert!(
            line.contains("--workspace") && line.contains("--all-targets"),
            "`{line}` does not select the whole workspace and every target, so \
             `fix` cannot reach the code `lint` fails on"
        );
    }

    // Every feature selection `lint` checks must have a `fix` counterpart, or
    // CI reports a lint in code `fix` cannot reach. `--all-features` is the one
    // exemption: it selects no code that the default pass does not already
    // select in this workspace (every member feature is unified on by
    // `--workspace`), so a fourth rewriting pass would buy nothing.
    //
    // Both halves are asserted, not just the feature-off one. Checking only the
    // `--no-default-features` axis let `fix` lose its *default* pass entirely
    // and still pass every assertion above — the remaining feature-off line
    // carries `--fix`, `--workspace` and `--all-targets`, so nothing went red
    // while `fix` could no longer touch anything the first `lint` pass reports.
    let lint = devenv_script(&devenv, "lint");
    let lint_lines = clippy_lines(&lint);

    assert!(
        fix_lines
            .iter()
            .any(|line| !line.contains("--all-features")
                && !line.contains("--no-default-features")),
        "`fix` has no default-feature pass, so it cannot fix anything `lint`'s \
         first and largest pass reports. Found {fix_lines:?}"
    );

    if lint_lines
        .iter()
        .any(|line| line.contains("--no-default-features"))
    {
        assert!(
            fix_lines
                .iter()
                .any(|line| line.contains("--no-default-features")),
            "`lint` has a --no-default-features pass but `fix` does not, so CI \
             reports lints in that arm with no automated fix at all. Found \
             {fix_lines:?}"
        );
    }

    // One `fix` pass per `lint` pass, less the `--all-features` exemption.
    assert!(
        fix_lines.len() >= lint_lines.len().saturating_sub(1),
        "`lint` runs {} clippy passes and `fix` only {}. At most one (\
         --all-features) may be skipped; anything more leaves a selection \
         `lint` fails on that `fix` cannot reach.\nlint: {lint_lines:?}\nfix: \
         {fix_lines:?}",
        lint_lines.len(),
        fix_lines.len(),
    );
}

/// `cargo fmt --check` must cover every member too.
///
/// The fourth selection axis, and the last one still hand-maintained: the fmt
/// pass takes an explicit 34-entry `-p` list (`qualityCrates` in `devenv.nix`)
/// rather than `--all`. Add a member and forget the `-p`, and `lint` reports
/// green on an unformatted crate forever — the same silent hole as a member
/// that never gets clippy'd, one tool over.
#[test]
fn the_fmt_pass_covers_every_workspace_member() {
    let root = repo_root();
    let manifest = std::fs::read_to_string(root.join("Cargo.toml")).expect("read root Cargo.toml");
    let members = workspace_members(&manifest);
    let devenv = std::fs::read_to_string(root.join("devenv.nix")).expect("read devenv.nix");

    // Scoped to the `qualityCrates = "…"` value, not searched across the whole
    // file: `scripts.tst.exec` also carries `-p plugin-stabby` and `-p
    // plugin-sdk`, so a whole-file search stays green when either is deleted
    // from `qualityCrates` — satisfied by the `tst` line while `cargo fmt
    // --check` quietly stops looking at the crate.
    let (_, after) = devenv
        .split_once("qualityCrates = \"")
        .expect("devenv.nix defines qualityCrates");
    let (quality_crates, _) = after
        .split_once('"')
        .expect("the qualityCrates string is closed");
    let selected: Vec<&str> = quality_crates.split_whitespace().collect();

    // The package name is the last path component for every member here; the
    // root package (`heph`) is not in `members` and is listed separately.
    let missing: Vec<&str> = members
        .iter()
        .filter(|member| !LINTS_EXEMPT.contains(&member.as_str()))
        .map(|member| member.rsplit('/').next().unwrap_or(member.as_str()))
        .filter(|name| !selected.contains(name))
        .collect();

    assert!(
        missing.is_empty(),
        "these workspace members are not in `qualityCrates`, so `cargo fmt \
         --check` never looks at them and `lint` reports green on unformatted \
         code: {missing:?}"
    );
}

/// The gate must run on macOS as well as Linux.
///
/// macOS-only code — the Mach `sweep_threads` block in `src/diag.rs`,
/// `crates/proc/src/proc_exec/imp_macos.rs`, `kqueue_macos.rs` — is compiled by
/// `Test darwin/arm64`, but nothing there passes `-D warnings`, so before the
/// `Lint darwin/arm64` job it was clippy-linted nowhere.
///
/// It is also the half that cannot fail loudly on its own: `#[expect]` is
/// fulfilled-or-error, so the crate-root test exemptions are pinned to whatever
/// lint set the gate actually runs. Delete the darwin job and nothing goes red —
/// the macOS half of every `#[expect]` simply stops being checked. Hence a test.
#[test]
fn the_lint_gate_runs_on_macos_as_well_as_linux() {
    let workflow = std::fs::read_to_string(repo_root().join(".github/workflows/heph.yml"))
        .expect("read .github/workflows/heph.yml");

    // A job id is a two-space-indented `<name>:` at the end of its line; a job's
    // body runs until the next one. Walk the file once and collect, for every
    // job whose id starts with `lint`, its `runs-on:` and its `run:` steps.
    //
    // The `run:` half matters as much as the runner: asserting only the label
    // lets someone point the darwin job at `cargo fmt --check`, or drop its
    // Lint step, and stay green while macOS clippy coverage disappears — which
    // is the whole reason the job exists.
    let mut runners: Vec<&str> = Vec::new();
    let mut commands: Vec<&str> = Vec::new();
    let mut in_lint_job = false;
    for line in workflow.lines() {
        if let Some(rest) = line.strip_prefix("  ")
            && !rest.starts_with([' ', '#', '-'])
            && let Some(id) = rest.strip_suffix(':')
        {
            in_lint_job = id.starts_with("lint");
            continue;
        }
        if !in_lint_job {
            continue;
        }
        if let Some(runner) = line.trim().strip_prefix("runs-on:") {
            runners.push(runner.trim());
        }
        if let Some(cmd) = line.trim().strip_prefix("run:") {
            commands.push(cmd.trim());
        }
    }

    assert!(
        runners.iter().any(|r| r.contains("ubuntu")),
        "no lint job runs on a Linux runner; found {runners:?}"
    );
    assert!(
        runners.iter().any(|r| r.contains("macos")),
        "no lint job runs on a macOS runner, so macOS-only code — including the \
         Mach `sweep_threads` block in `src/diag.rs`, the largest unsafe region \
         in the tree — is clippy-linted nowhere, and the crate-root `#[expect]` \
         headers are only ever checked against the lints that fire on Linux. \
         Found {runners:?}"
    );
    assert_eq!(
        commands.iter().filter(|c| **c == "lint").count(),
        runners.len(),
        "every lint job must actually run the `lint` script — one per runner. A \
         job that runs something narrower keeps the check name and the runner \
         while quietly covering less. runners: {runners:?}, run steps: \
         {commands:?}"
    );

    // Every lint job must gate something. `Lint darwin/arm64` is not in the
    // branch ruleset, so its entries in `release.needs` / `cleanup.needs` are
    // its only teeth: drop them and it can go red on every run forever with
    // nothing blocked and nothing red downstream.
    let mut lint_job_ids: Vec<&str> = Vec::new();
    for line in workflow.lines() {
        if let Some(rest) = line.strip_prefix("  ")
            && !rest.starts_with([' ', '#', '-'])
            && let Some(id) = rest.strip_suffix(':')
            && id.starts_with("lint")
        {
            lint_job_ids.push(id);
        }
    }
    assert!(
        lint_job_ids.len() >= 2,
        "expected at least two lint jobs (one per OS); found {lint_job_ids:?}"
    );

    for gate in ["release", "cleanup"] {
        let marker = format!("\n  {gate}:\n");
        let (_, body) = workflow
            .split_once(&marker)
            .unwrap_or_else(|| panic!("the workflow defines a `{gate}` job"));
        let needs = body
            .lines()
            .map(str::trim)
            .find(|line| line.starts_with("needs:"))
            .unwrap_or_else(|| panic!("`{gate}` declares `needs:`"));
        // Tokenised, not substring-matched: `lint` is a prefix of `lint_darwin`,
        // so a `contains` check would report `lint` present when only
        // `lint_darwin` is.
        let listed: Vec<&str> = needs
            .trim_start_matches("needs:")
            .trim()
            .trim_matches(['[', ']'])
            .split(',')
            .map(str::trim)
            .collect();
        for id in &lint_job_ids {
            assert!(
                listed.contains(id),
                "`{gate}` does not depend on the `{id}` job, so a red `{id}` \
                 blocks nothing at all. Found `{needs}`."
            );
        }
    }
}
