//! Guards on the lint gate itself.
//!
//! `lint` used to run `cargo clippy --all-targets` with no `--workspace`. The
//! repo root is itself a package, so cargo selected *only* that package: every
//! member's lib was compiled as a plain dependency with lints switched off, and
//! no member's test targets were built at all. 323 clippy errors accumulated
//! behind it, and on 2026-07-29 the `Lint` job reported pass on a master commit
//! whose `engine (lib test)` did not compile.
//!
//! Every test below asserts a *selection* invariant — which code the gate is
//! pointed at, and whether what it finds can actually turn a check red —
//! because that is the class of failure that is silent. A lint the gate can see
//! fails loudly; a crate the gate cannot see fails never. Five axes, each of
//! which has already gone wrong or been left open:
//!
//!   - which packages — `--workspace`;
//!   - which targets — `--all-targets`;
//!   - which feature set — `--no-default-features`, whose obvious spelling is a
//!     silent no-op in this workspace;
//!   - which platform — macOS was linted nowhere;
//!   - whether a red leg has any consequence at all — a leg can be made to
//!     conclude `success` without clippy ever running, and the `needs:` wiring
//!     that makes a red lint stop a release can simply be deleted.
//!
//! What these tests **cannot** cover: the lint job is a matrix, so its status
//! contexts are the rendered per-leg names (`Lint linux/amd64`,
//! `Lint darwin/arm64`). Whether those are *required* lives in the repo's
//! branch protection, outside this tree — so nothing here can assert that a red
//! lint blocks a merge. `lint_gates_release_and_cleanup` guards the only part
//! the workflow owns.
//!
//! Cheap on purpose: a few file reads and some string work, no build.

use std::path::{Path, PathBuf};

/// The repo root — this test belongs to the root package, so its manifest dir
/// *is* the root.
fn repo_root() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).to_path_buf()
}

/// `gen/proto` is generated by `buf`/`protoc-gen-prost` and carries
/// `[lints.clippy] all = "allow"` deliberately — hand-written lint policy does
/// not apply to code nobody hand-edits.
const LINTS_EXEMPT: &[&str] = &["gen/proto"];

/// The paths in the root manifest's `workspace.members` array.
///
/// Read from the manifest rather than hardcoded: a copy of the list would stop
/// covering exactly the crates this test exists to catch — the new ones.
fn workspace_members(manifest: &str) -> Vec<String> {
    let after = manifest
        .split_once("members = [")
        .map(|(_, rest)| rest)
        .expect("root Cargo.toml has a workspace.members array");
    let list = after
        .split_once(']')
        .map(|(list, _)| list)
        .expect("workspace.members array is closed");
    list.split(',')
        .map(|entry| entry.trim().trim_matches('"').to_string())
        .filter(|entry| !entry.is_empty())
        .collect()
}

/// Whether `manifest` has a `[lints]` table containing `workspace = true`.
///
/// Deliberately section-aware: `[lints.clippy]` is a *different* table and must
/// not satisfy this, since a crate that defines its own lints does not inherit
/// the workspace set (cargo rejects having both).
fn inherits_workspace_lints(manifest: &str) -> bool {
    let mut in_lints = false;
    for line in manifest.lines() {
        let line = line.trim();
        if let Some(section) = line.strip_prefix('[').and_then(|s| s.strip_suffix(']')) {
            in_lints = section == "lints";
            continue;
        }
        if in_lints && line.replace(' ', "") == "workspace=true" {
            return true;
        }
    }
    false
}

/// Every member must inherit `[workspace.lints]`.
///
/// This is the other half of the gate's coverage, and it fails the same silent
/// way: `--workspace --all-targets` will happily lint a member that never
/// opted in, using stock clippy only — no `unwrap_used`, no `indexing_slicing`,
/// no `map_err_ignore`, no `undocumented_unsafe_blocks` — and report green.
#[test]
fn every_workspace_member_inherits_the_workspace_lints() {
    let root = repo_root();
    let manifest =
        std::fs::read_to_string(root.join("Cargo.toml")).expect("read the root Cargo.toml");
    let members = workspace_members(&manifest);
    assert!(
        members.len() > 10,
        "parsed only {} workspace members — the manifest layout changed and this \
         test is no longer reading it",
        members.len()
    );

    let missing: Vec<&String> = members
        .iter()
        .filter(|member| !LINTS_EXEMPT.contains(&member.as_str()))
        .filter(|member| {
            let path = root.join(member).join("Cargo.toml");
            let member_manifest = std::fs::read_to_string(&path)
                .unwrap_or_else(|e| panic!("read {}: {e}", path.display()));
            !inherits_workspace_lints(&member_manifest)
        })
        .collect();

    assert!(
        missing.is_empty(),
        "these workspace members do not inherit `[workspace.lints]`, so the \
         repo's restriction lints do not apply to them and `lint` will report \
         green on code that violates every one of them: {missing:?}\n\
         Add `[lints]\\nworkspace = true` to each, or add it to LINTS_EXEMPT \
         here with a reason."
    );
}

/// The body of a `scripts.<name>.exec = ''…'';` block in `devenv.nix`.
///
/// Split per script rather than scanning the whole file: `lint` and `fix` both
/// contain `cargo clippy` lines, and the invariant below is that they *agree* —
/// which cannot be checked if the two are read as one pile.
///
/// `expect`, not `panic!`: `clippy.toml`'s `allow-panic-in-tests` only covers
/// `#[test]` bodies, and this is a free function.
#[track_caller]
fn devenv_script(devenv: &str, name: &str) -> String {
    let marker = format!("scripts.{name}.exec = ''");
    // Built up front rather than inside `expect`, which would be
    // `expect_fun_call`.
    let opened = format!("devenv.nix defines `scripts.{name}.exec` as a '' block");
    let closed = format!("`scripts.{name}.exec` block is closed");
    let (_, rest) = devenv.split_once(&marker).expect(&opened);
    let (body, _) = rest.split_once("'';").expect(&closed);
    body.to_string()
}

/// The `cargo clippy` invocations inside one script body, trimmed.
fn clippy_lines(script: &str) -> Vec<&str> {
    script
        .lines()
        .map(str::trim)
        .filter(|line| line.starts_with("cargo clippy"))
        .collect()
}

/// The `--exclude <name>` arguments on a single invocation.
///
/// Both spellings cargo accepts, `--exclude name` and `--exclude=name`: reading
/// only the first would turn a legal rewrite of the script into a spurious
/// failure.
fn excludes(line: &str) -> Vec<&str> {
    let mut out = Vec::new();
    let mut words = line.split_whitespace();
    while let Some(word) = words.next() {
        if let Some(name) = word.strip_prefix("--exclude=") {
            out.push(name);
        } else if word == "--exclude"
            && let Some(name) = words.next()
        {
            out.push(name);
        }
    }
    out
}

/// The `lint` script must point clippy at the whole workspace, every target.
///
/// This restates the implementation on purpose: the literal regression was
/// someone writing the shorter invocation, and the comment above it in
/// `devenv.nix` is documentation, not a gate.
#[test]
fn the_lint_script_selects_the_whole_workspace() {
    let devenv = std::fs::read_to_string(repo_root().join("devenv.nix")).expect("read devenv.nix");
    let lint = devenv_script(&devenv, "lint");
    let lines = clippy_lines(&lint);

    assert!(
        lines.len() >= 3,
        "expected at least three clippy invocations in `lint` (default features, \
         --all-features, --no-default-features); found {lines:?}"
    );
    for line in &lines {
        assert!(
            line.contains("--workspace"),
            "`{line}` omits --workspace. The repo root is itself a package, so \
             cargo would select only the root package: members' libs get linted \
             with no lints applied and their test targets are never built."
        );
        assert!(
            line.contains("--all-targets"),
            "`{line}` omits --all-targets, so `#[cfg(test)] mod tests` and \
             `tests/` are skipped — where most of this repo's test code lives."
        );
    }

    let feature_off: Vec<&&str> = lines
        .iter()
        .filter(|line| line.contains("--no-default-features"))
        .collect();
    assert_eq!(
        feature_off.len(),
        1,
        "`lint` must carry exactly one --no-default-features pass. With \
         `fuse-sandbox` on — the default — `crates/sandboxfuse/src/stub.rs` is \
         compiled by nothing at all, on any platform, and must still satisfy \
         its callers in `crates/engine` and `crates/driver-bridge`. Found \
         {feature_off:?}"
    );

    // The guard that proves the pass above is pointed at the feature-*off* arm
    // must itself exist, and must select the same packages. Without this, the
    // guard can be deleted the first time it is inconvenient and the third pass
    // silently reverts to re-linting the arm pass 1 already covered — with the
    // script still printing `> clippy --no-default-features`.
    let probe = lint
        .lines()
        .map(str::trim)
        // `!starts_with('#')`: the block is commented, and a comment mentioning
        // the probe is not the probe.
        .find(|line| {
            !line.starts_with('#') && line.contains("cargo tree") && line.contains("-i fuser")
        })
        .expect(
            "`lint` must assert `fuse-sandbox` is actually off before linting it, \
             with a `cargo tree … -i fuser` probe. `--no-default-features` alone \
             does not disable it: e2e/plugingo-e2e/testkit pull the root `heph` \
             package with default features and cargo unifies across the selection.",
        );
    assert_eq!(
        excludes(probe),
        excludes(feature_off[0]),
        "the `cargo tree -i fuser` probe and the --no-default-features clippy \
         pass select different packages, so the probe is not checking the \
         selection that gets linted.\nprobe: {probe}\npass:  {}",
        feature_off[0]
    );
}

/// The `--no-default-features` pass must exclude every member that switches
/// `fuse-sandbox` back on, or it silently lints the wrong arm.
///
/// Cargo unifies features across the whole selected set. `crates/e2e`,
/// `crates/plugingo-e2e` and `crates/testkit` depend on the root `heph` package
/// with default features on, so a plain `--workspace --no-default-features`
/// re-enables `fuse-sandbox` through that edge and the pass becomes a no-op
/// that still reports green — the same silent-selection failure the rest of
/// this file exists to catch, one axis over.
///
/// Derived from the manifests, never copied: a *new* member with a default-
/// featured `heph` edge is exactly the case a hardcoded list would miss.
///
/// **Scope, stated so it is not over-trusted.** This reads one line per
/// manifest, so it sees a *direct*, single-line `heph = { … }` edge and nothing
/// else — not a `[dependencies.heph]` table, not a multi-line inline table, and
/// not a transitive re-enable (a new member dev-depending on `htestkit`, which
/// itself pulls `heph` with default features, gets the feature back without
/// appearing here). The authority is the `cargo tree -i fuser` assertion inside
/// `lint`, which sees the fully resolved graph; this test is the cheap early
/// warning that costs no build, not a replacement for it.
#[test]
fn the_feature_off_pass_excludes_every_member_that_re_enables_fuse_sandbox() {
    let root = repo_root();
    let manifest = std::fs::read_to_string(root.join("Cargo.toml")).expect("read root Cargo.toml");
    let members = workspace_members(&manifest);

    let mut re_enablers: Vec<String> = members
        .iter()
        .filter(|member| {
            let path = root.join(member).join("Cargo.toml");
            let member_manifest = std::fs::read_to_string(&path)
                .unwrap_or_else(|e| panic!("read {}: {e}", path.display()));
            member_manifest.lines().any(|line| {
                let line = line.trim();
                line.starts_with("heph = ") && !line.contains("default-features = false")
            })
        })
        // The package name is the last path component for every member here.
        .map(|member| {
            member
                .rsplit('/')
                .next()
                .unwrap_or(member.as_str())
                .to_string()
        })
        .collect();
    re_enablers.sort();
    assert!(
        !re_enablers.is_empty(),
        "no member was found depending on the root `heph` package — this test \
         is no longer reading the manifests it thinks it is"
    );

    let devenv = std::fs::read_to_string(root.join("devenv.nix")).expect("read devenv.nix");
    for script in ["lint", "fix"] {
        let body = devenv_script(&devenv, script);
        let line = clippy_lines(&body)
            .into_iter()
            .find(|line| line.contains("--no-default-features"))
            .unwrap_or_else(|| panic!("`{script}` has a --no-default-features clippy invocation"));
        let mut excluded = excludes(line);
        excluded.sort_unstable();

        let missing: Vec<&String> = re_enablers
            .iter()
            .filter(|name| !excluded.contains(&name.as_str()))
            .collect();
        assert!(
            missing.is_empty(),
            "`{script}`'s --no-default-features pass does not exclude {missing:?}. \
             Those members depend on the root `heph` package with default \
             features on, and cargo unifies features across the selection, so \
             `fuse-sandbox` is switched back on and the pass lints the feature-\
             *on* arm while reporting that it covered the off one.\n\
             Add `--exclude <name>` for each, or give the member's `heph` \
             dependency `default-features = false`."
        );

        // Equality, not just containment. An *extra* exclusion is the more
        // dangerous direction and a subset check waves it through: `--exclude
        // engine` or `--exclude driver-bridge` drops the two callers `stub.rs`
        // has to satisfy, and `--exclude sandboxfuse` drops the only package
        // the feature changes at all. Each turns the pass into a no-op that
        // still reports green, and none of them puts `fuser` back in the graph,
        // so the `cargo tree` guard in `lint` cannot see it either.
        let extra: Vec<&&str> = excluded
            .iter()
            .filter(|name| !re_enablers.iter().any(|r| r == *name))
            .collect();
        assert!(
            extra.is_empty(),
            "`{script}`'s --no-default-features pass excludes {extra:?}, which \
             do not re-enable `fuse-sandbox`. Excluding a package that is not a \
             re-enabler only shrinks what the pass lints — `engine` and \
             `driver-bridge` are the callers `crates/sandboxfuse/src/stub.rs` \
             must satisfy, and `sandboxfuse` is the only package the feature \
             changes — and neither the `cargo tree` guard nor the check above \
             can see the loss. Expected exactly {re_enablers:?}."
        );
    }
}

/// `fix` must select the same code as `lint`.
///
/// A `fix` that reaches less than `lint` leaves CI reporting lints with no
/// automated fix — and the person who hits it has to work out which of three
/// invocations produced the error before they can reproduce it.
#[test]
fn fix_selects_the_same_code_as_lint() {
    let devenv = std::fs::read_to_string(repo_root().join("devenv.nix")).expect("read devenv.nix");
    let fix = devenv_script(&devenv, "fix");
    let fix_lines = clippy_lines(&fix);

    for line in &fix_lines {
        assert!(
            line.contains("--fix"),
            "`{line}` is a bare clippy invocation inside `fix`; it must be \
             `cargo clippy --fix`"
        );
        assert!(
            line.contains("--workspace") && line.contains("--all-targets"),
            "`{line}` does not select the whole workspace and every target, so \
             `fix` cannot reach the code `lint` fails on"
        );
    }

    // Every feature selection `lint` checks must have a `fix` counterpart, or
    // CI reports a lint in code `fix` cannot reach. `--all-features` is the one
    // exemption: it selects no code that the default pass does not already
    // select in this workspace (every member feature is unified on by
    // `--workspace`), so a fourth rewriting pass would buy nothing.
    //
    // Both halves are asserted, not just the feature-off one. Checking only the
    // `--no-default-features` axis let `fix` lose its *default* pass entirely
    // and still pass every assertion above — the remaining feature-off line
    // carries `--fix`, `--workspace` and `--all-targets`, so nothing went red
    // while `fix` could no longer touch anything the first `lint` pass reports.
    let lint = devenv_script(&devenv, "lint");
    let lint_lines = clippy_lines(&lint);

    assert!(
        fix_lines
            .iter()
            .any(|line| !line.contains("--all-features")
                && !line.contains("--no-default-features")),
        "`fix` has no default-feature pass, so it cannot fix anything `lint`'s \
         first and largest pass reports. Found {fix_lines:?}"
    );

    if lint_lines
        .iter()
        .any(|line| line.contains("--no-default-features"))
    {
        assert!(
            fix_lines
                .iter()
                .any(|line| line.contains("--no-default-features")),
            "`lint` has a --no-default-features pass but `fix` does not, so CI \
             reports lints in that arm with no automated fix at all. Found \
             {fix_lines:?}"
        );
    }

    // One `fix` pass per `lint` pass, less the `--all-features` exemption.
    assert!(
        fix_lines.len() >= lint_lines.len().saturating_sub(1),
        "`lint` runs {} clippy passes and `fix` only {}. At most one (\
         --all-features) may be skipped; anything more leaves a selection \
         `lint` fails on that `fix` cannot reach.\nlint: {lint_lines:?}\nfix: \
         {fix_lines:?}",
        lint_lines.len(),
        fix_lines.len(),
    );
}

/// `cargo fmt --check` must cover every member too.
///
/// The fourth selection axis, and the last one still hand-maintained: the fmt
/// pass takes an explicit 34-entry `-p` list (`qualityCrates` in `devenv.nix`)
/// rather than `--all`. Add a member and forget the `-p`, and `lint` reports
/// green on an unformatted crate forever — the same silent hole as a member
/// that never gets clippy'd, one tool over.
#[test]
fn the_fmt_pass_covers_every_workspace_member() {
    let root = repo_root();
    let manifest = std::fs::read_to_string(root.join("Cargo.toml")).expect("read root Cargo.toml");
    let members = workspace_members(&manifest);
    let devenv = std::fs::read_to_string(root.join("devenv.nix")).expect("read devenv.nix");

    // Scoped to the `qualityCrates = "…"` value, not searched across the whole
    // file: `scripts.tst.exec` also carries `-p plugin-stabby` and `-p
    // plugin-sdk`, so a whole-file search stays green when either is deleted
    // from `qualityCrates` — satisfied by the `tst` line while `cargo fmt
    // --check` quietly stops looking at the crate.
    let (_, after) = devenv
        .split_once("qualityCrates = \"")
        .expect("devenv.nix defines qualityCrates");
    let (quality_crates, _) = after
        .split_once('"')
        .expect("the qualityCrates string is closed");
    let selected: Vec<&str> = quality_crates.split_whitespace().collect();

    // The package name is the last path component for every member here; the
    // root package (`heph`) is not in `members` and is listed separately.
    let missing: Vec<&str> = members
        .iter()
        .filter(|member| !LINTS_EXEMPT.contains(&member.as_str()))
        .map(|member| member.rsplit('/').next().unwrap_or(member.as_str()))
        .filter(|name| !selected.contains(name))
        .collect();

    assert!(
        missing.is_empty(),
        "these workspace members are not in `qualityCrates`, so `cargo fmt \
         --check` never looks at them and `lint` reports green on unformatted \
         code: {missing:?}"
    );
}

/// A job id and the text of its body, for every job in the workflow.
///
/// A job id is a two-space-indented `<id>:` alone on its line, below the
/// top-level `jobs:` key. Anchored on `jobs:` rather than matched everywhere,
/// because `on:` has `push:` and `pull_request:` at the same indent and they
/// are not jobs.
fn workflow_jobs(workflow: &str) -> Vec<(&str, String)> {
    let (_, body) = workflow
        .split_once("\njobs:\n")
        .expect("the workflow has a top-level `jobs:` key");

    let mut jobs: Vec<(&str, Vec<&str>)> = Vec::new();
    for line in body.lines() {
        let header = line
            .strip_prefix("  ")
            .filter(|rest| !rest.starts_with([' ', '#', '-']))
            .and_then(|rest| rest.strip_suffix(':'))
            .filter(|id| {
                !id.is_empty()
                    && id
                        .chars()
                        .all(|c| c.is_ascii_lowercase() || c.is_ascii_digit() || c == '_')
            });
        match header {
            Some(id) => jobs.push((id, Vec::new())),
            None => {
                if let Some((_, lines)) = jobs.last_mut() {
                    lines.push(line);
                }
            }
        }
    }
    jobs.into_iter()
        .map(|(id, lines)| (id, lines.join("\n")))
        .collect()
}

/// The `needs:` of a job body, tokenised.
///
/// Tokenised rather than substring-matched: `lint` is a prefix of
/// `lint_matrix`, so a `contains` check reports `lint` present when only
/// `lint_matrix` is.
fn job_needs(body: &str) -> Vec<&str> {
    body.lines()
        .map(str::trim)
        .find(|line| line.starts_with("needs:"))
        .map(|line| {
            line.strip_prefix("needs:")
                .unwrap_or(line)
                .trim()
                .trim_matches(['[', ']'])
                .split(',')
                .map(str::trim)
                .filter(|entry| !entry.is_empty())
                .collect()
        })
        .unwrap_or_default()
}

/// The `run:` step commands in a job body.
fn job_run_steps(body: &str) -> Vec<&str> {
    body.lines()
        .map(str::trim)
        .filter_map(|line| line.strip_prefix("run:"))
        .map(str::trim)
        .collect()
}

/// The concrete `runs-on:` labels in a job body.
///
/// Skips `${{ matrix.runs-on }}` and friends: on a matrix job the job-level
/// `runs-on` is an expression and the real labels live in `matrix.include`.
fn job_runners(body: &str) -> Vec<&str> {
    body.lines()
        .map(str::trim)
        .filter_map(|line| {
            line.strip_prefix("- ")
                .unwrap_or(line)
                .strip_prefix("runs-on:")
        })
        .map(str::trim)
        .filter(|label| !label.contains("${{"))
        .collect()
}

/// Job ids that actually run the `lint` script.
///
/// Derived from the `run:` steps rather than from the job name: a job that
/// keeps the name and the runner while running something narrower is the
/// regression, not the thing to trust.
fn lint_legs<'a>(jobs: &[(&'a str, String)]) -> Vec<&'a str> {
    jobs.iter()
        .filter(|(_, body)| job_run_steps(body).contains(&"lint"))
        .map(|(id, _)| *id)
        .collect()
}

/// The `matrix.include` entries of a job body, as `<key>: <value>` maps.
///
/// Parsed rather than pattern-matched on `os:`/`arch:` so the platform
/// assertions read the same coordinates the workflow does.
fn matrix_include(body: &str) -> Vec<Vec<(String, String)>> {
    let mut entries: Vec<Vec<(String, String)>> = Vec::new();
    let mut in_include = false;
    for line in body.lines() {
        if line.trim() == "include:" {
            in_include = true;
            continue;
        }
        if !in_include {
            continue;
        }
        let trimmed = line.trim();
        if trimmed.is_empty() || trimmed.starts_with('#') {
            continue;
        }
        // A new entry starts at `- key: value`; `steps:` ends the block.
        let (starts_entry, pair) = match trimmed.strip_prefix("- ") {
            Some(rest) => (true, rest),
            None => (false, trimmed),
        };
        if starts_entry {
            entries.push(Vec::new());
        } else if entries.is_empty() || !line.starts_with("            ") {
            break;
        }
        if let Some((key, value)) = pair.split_once(':')
            && let Some(last) = entries.last_mut()
        {
            last.push((key.trim().to_string(), value.trim().to_string()));
        }
    }
    entries
}

/// The step blocks of a job body, each starting at a `      - ` line.
///
/// Some invariants are per *step*, not per job: the `sccache stats` step
/// legitimately carries `if: always()`, so "the Lint step has no `if:`" cannot
/// be checked by scanning the whole job.
fn job_steps(body: &str) -> Vec<String> {
    let mut steps: Vec<Vec<&str>> = Vec::new();
    let mut in_steps = false;
    for line in body.lines() {
        if line.trim() == "steps:" {
            in_steps = true;
            continue;
        }
        if !in_steps {
            continue;
        }
        if line.starts_with("      - ") {
            steps.push(vec![line]);
        } else if let Some(last) = steps.last_mut() {
            last.push(line);
        }
    }
    steps.into_iter().map(|lines| lines.join("\n")).collect()
}

/// `text` with whole-line YAML comments removed.
///
/// A content assertion must not be satisfiable by prose. `workflow_jobs`
/// attributes a job's *leading* comment block to the job above it, so a
/// comment that merely mentions `needs.<dep>.result` would otherwise satisfy
/// the assertion that the aggregator checks it — reordering the two jobs is
/// enough to hand the aggregator that block and let it pass with its script
/// gutted.
fn without_comments(text: &str) -> String {
    text.lines()
        .filter(|line| !line.trim_start().starts_with('#'))
        .collect::<Vec<_>>()
        .join("\n")
}

/// The gate must run on macOS as well as Linux.
///
/// macOS-only code — the Mach `sweep_threads` block in `src/diag.rs`,
/// `crates/proc/src/proc_exec/imp_macos.rs`, `kqueue_macos.rs` — is compiled by
/// `Test darwin/arm64`, but nothing there passes `-D warnings`, so before the
/// darwin lint leg it was clippy-linted nowhere.
///
/// It is also the half that cannot fail loudly on its own: `#[expect]` is
/// fulfilled-or-error, so the crate-root test exemptions are pinned to whatever
/// lint set the gate actually runs. Drop the darwin leg and nothing goes red —
/// the macOS half of every `#[expect]` simply stops being checked. Hence a test.
#[test]
fn the_lint_gate_runs_on_macos_as_well_as_linux() {
    let workflow = std::fs::read_to_string(repo_root().join(".github/workflows/heph.yml"))
        .expect("read .github/workflows/heph.yml");
    let jobs = workflow_jobs(&workflow);
    let legs = lint_legs(&jobs);

    assert!(
        !legs.is_empty(),
        "no job in the workflow runs the `lint` script at all"
    );

    let runners: Vec<&str> = jobs
        .iter()
        .filter(|(id, _)| legs.contains(id))
        .flat_map(|(_, body)| job_runners(body))
        .collect();

    assert!(
        runners.iter().any(|label| label.contains("ubuntu")),
        "no lint leg runs on a Linux runner; found {runners:?}"
    );
    assert!(
        runners.iter().any(|label| label.contains("macos")),
        "no lint leg runs on a macOS runner, so macOS-only code — including the \
         Mach `sweep_threads` block in `src/diag.rs`, the largest unsafe region \
         in the tree — is clippy-linted nowhere, and the crate-root `#[expect]` \
         headers are only ever checked against the lints that fire on Linux. \
         Found {runners:?}"
    );
}

/// A lint leg must not be able to conclude `success` without linting.
///
/// The aggregator can only be as good as the legs' own conclusions, and there
/// are two one-line ways to make a leg green while clippy never ran:
/// `continue-on-error: true`, which converts a failure into a success, and an
/// `if:` on the Lint step, which can skip it entirely. Either makes
/// `needs.lint_matrix.result` `success` and the required `Lint` check green
/// over a platform that was not linted — the last remaining route to a silent
/// pass here, and invisible to every other test in this file.
#[test]
fn a_lint_leg_cannot_report_success_without_running_the_lint() {
    let workflow = std::fs::read_to_string(repo_root().join(".github/workflows/heph.yml"))
        .expect("read .github/workflows/heph.yml");
    let jobs = workflow_jobs(&workflow);
    let legs = lint_legs(&jobs);
    assert!(
        !legs.is_empty(),
        "no job in the workflow runs the `lint` script at all"
    );

    for (id, body) in jobs.iter().filter(|(id, _)| legs.contains(id)) {
        let body = without_comments(body);

        assert!(
            !body
                .lines()
                .any(|line| line.trim().starts_with("continue-on-error:")),
            "the `{id}` lint leg has a `continue-on-error:`. That turns a \
             clippy failure into a job that concludes `success`, so the leg's \
             own check goes green and `release` proceeds over a platform whose \
             lint failed."
        );

        let lint_step = job_steps(&body)
            .into_iter()
            .find(|step| job_run_steps(step).contains(&"lint"))
            .unwrap_or_else(|| panic!("`{id}` has a step running the `lint` script"));

        // Scoped to this step: `sccache stats` legitimately has `if: always()`.
        assert!(
            !lint_step.lines().any(|line| line.trim().starts_with("if:")),
            "the Lint step of the `{id}` leg carries an `if:`. A skipped step \
             does not fail its job, so the leg would conclude `success` with \
             clippy never having run, and its check would go green over an \
             unlinted platform.\n{lint_step}"
        );
    }
}

/// The lint job must be a matrix, and it must carry both supported OSes.
///
/// The legs *are* the status contexts now — there is no aggregator and no
/// context named plain `Lint` — so the matrix's shape is the gate's shape.
/// Three things are asserted because each fails silently:
///
///   - both platforms present, or a whole OS goes unlinted while the remaining
///     leg reports green (the macOS half is the one that was missing);
///   - `fail-fast: false`, or the first red leg *cancels* the other and the
///     platform you did not see reports `cancelled` rather than a result. On
///     the pass that matters — a lint that fires on one OS only — fail-fast
///     hides exactly the half you need;
///   - one leg per platform, so a duplicated coordinate cannot masquerade as
///     coverage of a second OS.
#[test]
fn the_lint_job_is_a_matrix_over_both_supported_oses() {
    let workflow = std::fs::read_to_string(repo_root().join(".github/workflows/heph.yml"))
        .expect("read .github/workflows/heph.yml");
    let jobs = workflow_jobs(&workflow);
    let legs = lint_legs(&jobs);
    assert_eq!(
        legs.len(),
        1,
        "expected exactly one job to run the `lint` script — the matrix. Found \
         {legs:?}"
    );

    let (id, body) = jobs
        .iter()
        .find(|(id, _)| legs.contains(id))
        .expect("the lint leg is a job");
    let body = without_comments(body);

    assert!(
        body.lines()
            .any(|line| line.trim().starts_with("strategy:")),
        "the `{id}` job has no `strategy:`, so it is not a matrix and cannot \
         cover more than one platform"
    );
    assert!(
        body.lines()
            .any(|line| line.replace(' ', "") == "fail-fast:false"),
        "the `{id}` matrix does not set `fail-fast: false`. With fail-fast on, \
         the first red leg cancels the other, so the platform you did not see \
         reports `cancelled` instead of a result — and a lint that fires on one \
         OS only is exactly the case that hides."
    );

    let coords: Vec<String> = matrix_include(&body)
        .iter()
        .filter_map(|entry| {
            let get = |k: &str| {
                entry
                    .iter()
                    .find(|(key, _)| key == k)
                    .map(|(_, value)| value.clone())
            };
            Some(format!("{}/{}", get("os")?, get("arch")?))
        })
        .collect();

    assert!(
        coords.iter().any(|c| c.starts_with("linux/")),
        "the `{id}` matrix has no linux leg; found {coords:?}"
    );
    assert!(
        coords.iter().any(|c| c.starts_with("darwin/")),
        "the `{id}` matrix has no darwin leg, so macOS-only code — including \
         the Mach `sweep_threads` block in `src/diag.rs`, the largest unsafe \
         region in the tree — is clippy-linted nowhere, and the crate-root \
         `#[expect]` headers are only ever checked against the lints that fire \
         on Linux. Found {coords:?}"
    );

    let mut unique = coords.clone();
    unique.sort();
    unique.dedup();
    assert_eq!(
        unique.len(),
        coords.len(),
        "the `{id}` matrix has a duplicated os/arch coordinate, so it looks \
         like it covers more platforms than it does: {coords:?}"
    );
}

/// The lint job must gate `release` and `cleanup`.
///
/// This is the *only* automatic consequence of a red lint that lives in the
/// repo. The status contexts are named per leg (`Lint linux/amd64`,
/// `Lint darwin/arm64`) and branch protection is configured outside the tree,
/// so nothing here can assert that a red lint blocks a merge — these two
/// `needs:` entries are the whole of what the workflow itself enforces. Drop
/// them and a red lint blocks nothing at all.
///
/// `needs:` on a matrix job waits for every leg and is satisfied only if all of
/// them succeeded — verified against a real run rather than assumed:
/// `bin_e2e` (`needs: [gen, build, …]`) started 4s after the *last* `build` leg
/// finished, not the first.
#[test]
fn lint_gates_release_and_cleanup() {
    let workflow = std::fs::read_to_string(repo_root().join(".github/workflows/heph.yml"))
        .expect("read .github/workflows/heph.yml");
    let jobs = workflow_jobs(&workflow);
    let legs = lint_legs(&jobs);
    assert!(
        !legs.is_empty(),
        "no job in the workflow runs the `lint` script at all, so the check \
         below would pass over an empty set"
    );

    for gate in ["release", "cleanup"] {
        let (_, body) = jobs
            .iter()
            .find(|(id, _)| *id == gate)
            .unwrap_or_else(|| panic!("the workflow defines a `{gate}` job"));
        let needs = job_needs(body);

        let missing: Vec<&&str> = legs.iter().filter(|leg| !needs.contains(leg)).collect();
        assert!(
            missing.is_empty(),
            "`{gate}` does not depend on the lint job(s) {missing:?}, so a red \
             lint blocks nothing downstream. Found needs: {needs:?}"
        );
    }
}
