[package]
name = "coreutils"
version = "0.1.0"
edition = "2024"

[lints]
workspace = true

[dependencies]
anyhow = "1.0.102"
xxhash-rust = { version = "0.8.15", features = ["xxh3", "std"] }
uu_basename = "0.10"
uu_base64 = "0.10"
uu_cat = "0.10"
uu_chmod = "0.10"
uu_comm = "0.10"
uu_cp = "0.10"
uu_cut = "0.10"
uu_date = "0.10"
uu_dirname = "0.10"
uu_echo = "0.10"
uu_env = "0.10"
uu_false = "0.10"
uu_head = "0.10"
uu_install = "0.10"
uu_ln = "0.10"
uu_md5sum = "0.10"
uu_mkdir = "0.10"
uu_mktemp = "0.10"
uu_mv = "0.10"
uu_nproc = "0.10"
uu_printf = "0.10"
uu_readlink = "0.10"
uu_realpath = "0.10"
uu_rm = "0.10"
uu_rmdir = "0.10"
uu_seq = "0.10"
uu_sha1sum = "0.10"
uu_sha256sum = "0.10"
uu_sha512sum = "0.10"
uu_sleep = "0.10"
uu_sort = "0.10"
uu_stat = "0.10"
uu_tail = "0.10"
uu_tee = "0.10"
uu_timeout = "0.10"
uu_touch = "0.10"
uu_tr = "0.10"
uu_true = "0.10"
uu_uniq = "0.10"
uu_wc = "0.10"

[dev-dependencies]
tempfile = "3"
uucore = "0.10"
