#!/usr/bin/env python3
"""Emit a virtual workspace manifest for the publish staging tree.

The staging tree contains only the crates that get published to crates.io
(the plugin-sdk closure) plus the generated proto crate. The published crates
declare `[lints] workspace = true`, so the synthetic root must carry the same
`[workspace.lints.*]` block as the real repo root — we slice it verbatim out of
the original manifest rather than duplicating it here (so it never drifts).

Usage: make_staging_root.py <path-to-real-root-Cargo.toml>  > staging/Cargo.toml
"""

import sys

# Member dirs in the staging tree (paths relative to the staging root).
MEMBERS = [
    "crates/core",
    "crates/model",
    "crates/htspec-derive",
    "crates/plugin",
    "crates/driver-support",
    "crates/plugin-abi",
    "crates/plugin-stabby",
    "crates/plugin-sdk",
    "gen/proto",
]


def slice_lints(root_toml: str) -> str:
    """Return the contiguous `[workspace.lints...]` section block."""
    lines = root_toml.splitlines()
    start = None
    for i, line in enumerate(lines):
        if line.startswith("[workspace.lints"):
            start = i
            break
    if start is None:
        return ""
    # Run until the next top-level table that is NOT a workspace.lints subtable.
    end = len(lines)
    for j in range(start + 1, len(lines)):
        s = lines[j]
        if s.startswith("[") and not s.startswith("[workspace.lints"):
            end = j
            break
    return "\n".join(lines[start:end]).rstrip()


def main() -> None:
    root = open(sys.argv[1], encoding="utf-8").read()
    members = ",\n".join(f'    "{m}"' for m in MEMBERS)
    out = (
        "# AUTOGENERATED by scripts/publish/make_staging_root.py — do not edit.\n"
        "# Virtual workspace containing only the crates published to crates.io.\n\n"
        "[workspace]\n"
        'resolver = "2"\n'
        f"members = [\n{members},\n]\n\n"
        f"{slice_lints(root)}\n"
    )
    sys.stdout.write(out)


if __name__ == "__main__":
    main()
