#[allow(clippy::module_inception)]
mod engine;
pub use engine::Engine;
pub use engine::Config;
mod result;
mod cwd;
pub use cwd::get_cwd;
pub use cwd::get_cwp;
mod root;
pub use root::get_root;
mod local_cache;
mod local_cache_fs;
mod query;
mod packages;
pub mod error;
pub mod provider;
pub mod driver;
pub mod request_state;
pub use result::EResult;
pub use result::ResultOptions;
pub use result::OutputMatcher;
mod matcher_spec;
pub mod driver_managed;
mod meta;
mod execute;
mod link;
