[package]
name = "secrets"
version = "0.1.0"
edition = "2024"

[lints]
workspace = true

[dependencies]
hcore = { package = "core", path = "../core" }
hmodel = { package = "model", path = "../model" }
hproc = { package = "proc", path = "../proc" }
hexecrunner = { package = "execrunner", path = "../execrunner" }
hplugin = { package = "plugin", path = "../plugin" }
hdriver_support = { package = "driver-support", path = "../driver-support" }
async-trait = "0.1"
tempfile = "3"
anyhow = "1.0.102"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tracing = "0.1"
aho-corasick = "1.1"
base64 = "0.22"
chrono = { version = "0.4", default-features = false, features = ["std"] }
humantime = "2.3.0"
tokio = { version = "1.52.3", features = ["sync", "time"] }

[dev-dependencies]
tokio = { version = "1.52.3", features = ["rt", "rt-multi-thread", "macros", "time"] }
