#ifndef HEPH_FFI_H
#define HEPH_FFI_H

/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Opaque handle for KV store
 */
typedef struct KvStoreHandle KvStoreHandle;

/**
 * Free a string allocated by Rust
 */
void heph_free_string(char *s);

/**
 * Test function - returns "Hello from Rust!"
 */
char *heph_hello(void);

/**
 * Generate a new UUID v4
 */
char *heph_uuid_new(void);

/**
 * Parse a target reference and return package:target format
 * Returns NULL on error
 */
char *heph_tref_parse(const char *input);

/**
 * Parse a target reference in package context
 */
char *heph_tref_parse_in_package(const char *input, const char *pkg);

/**
 * Get the package from a parsed target reference
 */
char *heph_tref_get_package(const char *input);

/**
 * Get the target name from a parsed target reference
 */
char *heph_tref_get_target(const char *input);

/**
 * Open a SQLite KV store at the given path
 * Returns NULL on error
 */
struct KvStoreHandle *heph_kv_open(const char *path);

/**
 * Open an in-memory SQLite KV store
 * Returns NULL on error
 */
struct KvStoreHandle *heph_kv_open_memory(void);

/**
 * Close and free a KV store handle
 */
void heph_kv_close(struct KvStoreHandle *handle);

/**
 * Get a value by key
 * Returns NULL if key not found or on error
 * Caller must free the returned string with heph_free_string
 */
char *heph_kv_get(struct KvStoreHandle *handle, const char *key);

/**
 * Set a key-value pair
 * Returns 0 on success, -1 on error
 */
int32_t heph_kv_set(struct KvStoreHandle *handle, const char *key, const char *value);

/**
 * Delete a key
 * Returns 0 on success, -1 on error
 */
int32_t heph_kv_delete(struct KvStoreHandle *handle, const char *key);

/**
 * Check if a key exists
 * Returns 1 if exists, 0 if not exists, -1 on error
 */
int32_t heph_kv_exists(struct KvStoreHandle *handle, const char *key);

#endif  /* HEPH_FFI_H */
