[package]
name = "plugin-devenv-cdylib"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[lints]
workspace = true

[dependencies]
hplugin-devenv = { package = "plugin-devenv", path = "../plugin-devenv" }
hdriver-support = { package = "driver-support", path = "../driver-support" }
plugin-sdk = { path = "../plugin-sdk", features = ["stabby"] }
stabby = "72.1.8"
anyhow = "1.0.102"
tracing = "0.1"
