# to use, set: export OTEL_EXPORTER_OTLP_ENDPOINT=http://localhost:4317
services:
  otel-lgtm:
    environment:
      ENABLE_LOGS_ALL: "true"
    volumes:
      - data:/data
    build: .
    ports:
      - "3000:3000"
      - "4317:4317"
      - "4318:4318"
volumes:
  data:
