use anyhow::Context;
use async_trait::async_trait;
use hcore::debug_hash::DebugHasher;
use hcore::hasync::Cancellable;
use hdriver_support::driver_managed::{ManagedDriver, ManagedRunRequest, ManagedRunResponse};
use hplugin::driver::targetdef::{CacheConfig, Input, InputMode, TargetDef};
use hplugin::driver::{
    ApplyTransitiveRequest, ApplyTransitiveResponse, ConfigRequest, ConfigResponse, ParseRequest,
    ParseResponse, TargetAddr,
};
use hplugin::htspec::Spec;
use std::collections::HashMap;
use std::hash::{Hash, Hasher};
use std::sync::Arc;
use xxhash_rust::xxh3::Xxh3Default;

/// Config for a `js_package_info` target (provider-generated by the `js`
/// provider's `Provider::get`). `#[derive(Spec)]` provides the parser and the
/// LSP schema.
#[derive(Spec)]
struct JsPackageInfoSpec {
    /// The package's own `package.json` `"name"` field.
    #[spec(required)]
    name: String,
    /// Declared-dependency edges, grouped by the `package.json` field they
    /// came from (`"dependencies"` / `"dev_dependencies"`) — each entry is
    /// either a sibling workspace member's own target addr, or a
    /// `js_install` addr, per `pluginjs::deps::resolve_package_deps`.
    /// Mirrors the Go plugin's grouped-`deps` config convention
    /// (`GoGolistSpec::deps`).
    deps: HashMap<String, Vec<String>>,
}

#[derive(Clone, Hash, serde::Serialize, serde::Deserialize)]
struct JsPackageInfoDef {
    name: String,
    dep_inputs: Vec<Input>,
}

/// Bump to invalidate every cached `js_package_info` artifact whenever this
/// driver's def shape changes.
const JS_PACKAGE_INFO_FORMAT_VERSION: u32 = 2;

/// The per-package metadata target every discovered JS/TS package resolves
/// to. It carries the package's declared-dependency closure as target-dep
/// `Input`s (workspace-internal siblings by addr, third-party packages via
/// their `js_install` addr — see `ai-docs/js-plugin-plan.md`'s M1
/// milestone), so later drivers (typecheck/test/bundle) can walk the
/// dependency DAG from here. It still produces no outputs of its own — pure
/// wiring, no build behavior yet.
pub struct JsPackageInfoDriver;

impl JsPackageInfoDriver {
    pub fn new() -> Self {
        Self
    }
}

impl Default for JsPackageInfoDriver {
    fn default() -> Self {
        Self::new()
    }
}

#[async_trait]
impl ManagedDriver for JsPackageInfoDriver {
    fn config(&self, _req: ConfigRequest) -> anyhow::Result<ConfigResponse> {
        Ok(ConfigResponse {
            name: "js_package_info".to_string(),
        })
    }

    fn schema(&self) -> hplugin::driver::DriverSchema {
        JsPackageInfoSpec::schema()
    }

    async fn parse(
        &self,
        req: ParseRequest,
        _ctoken: &(dyn Cancellable + Send + Sync),
    ) -> anyhow::Result<ParseResponse> {
        let pkg = req.target_spec.addr.package.clone();
        let spec = JsPackageInfoSpec::from(&req.target_spec.config)
            .context("parse js_package_info config")?;

        // Dep groups arrive from a HashMap (`deps`'s config value) — sort by
        // group name so `dep_inputs` order (and thus the hash) is
        // deterministic across parses, not walk/hashmap-iteration order.
        // Same regression class as the Go plugin's `_golist` `dep_inputs`
        // (see driver_golist.rs's `test_parse_dep_inputs_order_is_deterministic`).
        let mut dep_groups: Vec<&String> = spec.deps.keys().collect();
        dep_groups.sort();
        let mut dep_inputs: Vec<Input> = Vec::new();
        for group in dep_groups {
            let addrs = spec.deps.get(group).expect("group key from same map");
            for (i, addr_str) in addrs.iter().enumerate() {
                dep_inputs.push(Input {
                    r#ref: TargetAddr::parse(addr_str, &pkg)
                        .with_context(|| format!("parse dep addr {addr_str}"))?,
                    mode: InputMode::Standard,
                    origin_id: format!("dep|{group}|{i}"),
                    annotations: Default::default(),
                    hashed: true,
                    runtime: true,
                });
            }
        }

        let def = JsPackageInfoDef {
            name: spec.name,
            dep_inputs: dep_inputs.clone(),
        };

        let hash = {
            let mut h = DebugHasher::new(Xxh3Default::new(), || {
                format!("js_package_info_{}", req.target_spec.addr.format())
            });
            JS_PACKAGE_INFO_FORMAT_VERSION.hash(&mut h);
            def.hash(&mut h);
            format!("{:x}", h.finish()).into_bytes()
        };

        Ok(ParseResponse {
            target_def: TargetDef {
                addr: req.target_spec.addr.clone(),
                labels: req.target_spec.labels.clone(),
                raw_def: Arc::new(def),
                inputs: dep_inputs,
                outputs: vec![],
                support_files: vec![],
                // Nothing produced to cache — caching this target would only
                // add bookkeeping. The dep `Input`s still register real
                // target-dep DAG edges regardless of caching.
                cache: CacheConfig::off(),
                pty: false,
                hash,
                transparent: false,
            },
        })
    }

    async fn apply_transitive(
        &self,
        req: ApplyTransitiveRequest,
        _ctoken: &(dyn Cancellable + Send + Sync),
    ) -> anyhow::Result<ApplyTransitiveResponse> {
        Ok(ApplyTransitiveResponse {
            target_def: req.target_def,
        })
    }

    async fn run<'a, 'io>(
        &self,
        _req: ManagedRunRequest<'a, 'io>,
        _ctoken: &(dyn Cancellable + Send + Sync),
    ) -> anyhow::Result<ManagedRunResponse> {
        Ok(ManagedRunResponse { artifacts: vec![] })
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use hcore::hasync::StdCancellationToken;
    use hcore::htvalue::Value;
    use hmodel::htaddr::Addr;
    use hmodel::htpkg::PkgBuf;
    use hplugin::provider::TargetSpec;
    use std::collections::HashMap;

    fn driver() -> JsPackageInfoDriver {
        JsPackageInfoDriver::new()
    }

    fn ctoken() -> StdCancellationToken {
        StdCancellationToken::new()
    }

    fn make_parse_request(pkg: &str, name: &str) -> ParseRequest {
        let mut config: HashMap<String, Value> = HashMap::new();
        config.insert("name".to_string(), Value::String(name.to_string()));
        ParseRequest {
            request_id: "test".to_string(),
            target_spec: Arc::new(TargetSpec {
                addr: Addr::new(
                    PkgBuf::from(pkg),
                    "package_info".to_string(),
                    Default::default(),
                ),
                driver: "js_package_info".to_string(),
                config,
                ..Default::default()
            }),
        }
    }

    #[tokio::test]
    async fn driver_name_is_js_package_info() {
        let resp = driver().config(ConfigRequest {}).unwrap();
        assert_eq!(resp.name, "js_package_info");
    }

    #[tokio::test]
    async fn parse_missing_name_errors() {
        let ct = ctoken();
        let req = ParseRequest {
            request_id: "test".to_string(),
            target_spec: Arc::new(TargetSpec {
                addr: Addr::new(
                    PkgBuf::from("mypkg"),
                    "package_info".to_string(),
                    Default::default(),
                ),
                driver: "js_package_info".to_string(),
                ..Default::default()
            }),
        };
        assert!(driver().parse(req, &ct).await.is_err());
    }

    #[tokio::test]
    async fn parse_produces_no_inputs_or_outputs() {
        let ct = ctoken();
        let req = make_parse_request("mypkg", "my-pkg");
        let resp = driver().parse(req, &ct).await.unwrap();
        assert!(resp.target_def.inputs.is_empty());
        assert!(resp.target_def.outputs.is_empty());
        assert!(!resp.target_def.cache.enabled);
    }

    #[tokio::test]
    async fn parse_hash_is_deterministic_and_name_sensitive() {
        let ct = ctoken();
        let resp_a = driver()
            .parse(make_parse_request("mypkg", "my-pkg"), &ct)
            .await
            .unwrap();
        let resp_b = driver()
            .parse(make_parse_request("mypkg", "my-pkg"), &ct)
            .await
            .unwrap();
        assert_eq!(resp_a.target_def.hash, resp_b.target_def.hash);

        let resp_c = driver()
            .parse(make_parse_request("mypkg", "other-pkg"), &ct)
            .await
            .unwrap();
        assert_ne!(resp_a.target_def.hash, resp_c.target_def.hash);
    }

    #[tokio::test]
    async fn run_produces_no_artifacts() {
        use hplugin::driver::{RunInput, RunRequest};
        use std::path::PathBuf;

        let ct = ctoken();
        let req = make_parse_request("mypkg", "my-pkg");
        let parsed = driver().parse(req, &ct).await.unwrap();
        let request_id = "test".to_string();
        let run_req = ManagedRunRequest {
            request: RunRequest {
                request_id: &request_id,
                target: &parsed.target_def,
                tree_root_path: PathBuf::new(),
                inputs: Vec::<RunInput>::new(),
                hashin: "deadbeef",
                stdin: None,
                stdout: None,
                stderr: None,
                sandbox_dir: PathBuf::new(),
            },
            sandbox_dir: PathBuf::new(),
            sandbox_ws_dir: PathBuf::new(),
            sandbox_pkg_dir: PathBuf::new(),
            inputs: Vec::new(),
        };
        let resp = driver().run(run_req, &ct).await.unwrap();
        assert!(resp.artifacts.is_empty());
    }

    fn make_parse_request_with_deps(
        pkg: &str,
        name: &str,
        deps: Vec<(&str, Vec<&str>)>,
    ) -> ParseRequest {
        let mut config: HashMap<String, Value> = HashMap::new();
        config.insert("name".to_string(), Value::String(name.to_string()));
        let deps_map: HashMap<String, Value> = deps
            .into_iter()
            .map(|(k, vs)| {
                (
                    k.to_string(),
                    Value::List(
                        vs.into_iter()
                            .map(|v| Value::String(v.to_string()))
                            .collect(),
                    ),
                )
            })
            .collect();
        config.insert("deps".to_string(), Value::Map(deps_map));
        ParseRequest {
            request_id: "test".to_string(),
            target_spec: Arc::new(TargetSpec {
                addr: Addr::new(
                    PkgBuf::from(pkg),
                    "package_info".to_string(),
                    Default::default(),
                ),
                driver: "js_package_info".to_string(),
                config,
                ..Default::default()
            }),
        }
    }

    #[tokio::test]
    async fn parse_deps_become_target_dep_inputs() {
        let ct = ctoken();
        let req = make_parse_request_with_deps(
            "packages/a",
            "a",
            vec![(
                "dependencies",
                vec!["//@heph/js/thirdparty/lodash@4.17.21:js_install"],
            )],
        );
        let resp = driver().parse(req, &ct).await.unwrap();
        assert_eq!(resp.target_def.inputs.len(), 1);
        assert_eq!(resp.target_def.inputs[0].origin_id, "dep|dependencies|0");
    }

    // Regression: dep groups came from a HashMap, so `dep_inputs` order
    // varied across runs, making the hash unstable — same class of bug as
    // the Go plugin's `_golist` (driver_golist.rs). Order must be sorted by
    // group name.
    #[tokio::test]
    async fn parse_dep_inputs_order_is_deterministic() {
        let ct = ctoken();
        let mk = || {
            make_parse_request_with_deps(
                "packages/a",
                "a",
                vec![
                    ("zsrc", vec!["//packages/z:package_info"]),
                    ("dev_dependencies", vec!["//packages/d:package_info"]),
                    ("dependencies", vec!["//packages/b:package_info"]),
                ],
            )
        };
        let resp_a = driver().parse(mk(), &ct).await.unwrap();
        let resp_b = driver().parse(mk(), &ct).await.unwrap();

        let ids_a: Vec<&str> = resp_a
            .target_def
            .inputs
            .iter()
            .map(|i| i.origin_id.as_str())
            .collect();
        let ids_b: Vec<&str> = resp_b
            .target_def
            .inputs
            .iter()
            .map(|i| i.origin_id.as_str())
            .collect();
        assert_eq!(ids_a, ids_b);
        assert_eq!(
            ids_a,
            vec!["dep|dependencies|0", "dep|dev_dependencies|0", "dep|zsrc|0"]
        );
        assert_eq!(resp_a.target_def.hash, resp_b.target_def.hash);
    }
}
